<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function field_format_link_to_colorbox_field_formatter_info()
{
    return array(
        'link_to_colorbox_formatter' => array( //Machine name of the formatter
            'label' => t('Link to colorbox'),
            'field types' => array('image'), //This will only be available to text fields
            'settings' => array('image_style' => '', 'image_link' => ''),
//                'pic_size' => 'small', //give a default value for when the form is first loaded
//                'tooltip' => 'Link to user Facebook page', //ditto
//            ),
        ),
    );
}

function field_format_link_to_colorbox_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state)
{
    //This gets the view_mode where our settings are stored
    $display = $instance['display'][$view_mode];
    $settings = $display['settings'];

    $image_styles = image_style_options(FALSE, PASS_THROUGH);
    $element['image_style'] = array(
        '#title' => t('Image style'),
        '#type' => 'select',
        '#default_value' => $settings['image_style'],
        '#empty_option' => t('None (original image)'),
        '#options' => $image_styles,
    );
//    $link_types = array(
//        'content' => t('Content'),
//        'file' => t('File'),
//    );
//    $element['image_link'] = array(
//        '#title' => t('Link image to'),
//        '#type' => 'select',
//        '#default_value' => $settings['image_link'],
//        '#empty_option' => t('Nothing'),
//        '#options' => $link_types,
//    );
    return $element;
}

function field_format_link_to_colorbox_field_formatter_settings_summary($field, $instance, $view_mode)
{
    $display = $instance['display'][$view_mode];
    $settings = $display['settings'];

    $summary = array();

    $image_styles = image_style_options(FALSE, PASS_THROUGH);
    // Unset possible 'No defined styles' option.
    unset($image_styles['']);
    // Styles could be lost because of enabled/disabled modules that defines
    // their styles in code.
    if (isset($image_styles[$settings['image_style']])) {
        $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
    } else {
        $summary[] = t('Original image');
    }
//    if (isset($link_types[$settings['image_link']])) {
//        $summary[] = $link_types[$settings['image_link']];
//    }
    return implode('<br />', $summary);
}

function field_format_link_to_colorbox_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display)
{
    $element = array();


    foreach ($items as $delta => $item) {
        $uri = entity_uri($entity_type, $entity);
        $uri['options']['attributes']['class'][] = 'colorbox-node';
        $element[$delta] = array(
            '#theme' => 'image_formatter',
            '#item' => $item,
            '#image_style' => $display['settings']['image_style'],
            '#path' => isset($uri) ? $uri : '',
        );
    }


    return $element;


}
