<?php
/**
 * @file
 * f_ct_product.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function f_ct_product_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Defui Enim',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'cdef54b8-fd27-429a-aa30-fdced7f135de',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '08ae577d-e81c-44e0-8a08-726061de6bac',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Commoveo defui nibh occuro os quidne refero sino tum voco. Accumsan conventio typicus. Commodo eligo jumentum vulpes. Abico brevitas euismod nulla wisi. Amet capto causa nobis quadrum saepius vulpes.

Diam dolor in nobis obruo pecus plaga si suscipit utinam. Consectetuer dolore jumentum pneum proprius secundum tum valetudo voco vulputate.

Aliquip aptent euismod haero premo sagaciter. Adipiscing ea erat ibidem oppeto premo refero valde valetudo verto. Antehabeo cogo interdico jugis mauris nisl sed vero vicis. Eligo iustum mauris neo obruo os pecus zelus. Abdo aptent autem caecus paulatim scisco. Abdo abico ad facilisi jus nisl pala singularis suscipit. Aliquam dolor esca exputo feugiat persto usitas. At ea enim iustum natu.

Capto jus macto populus velit vereor virtus. Capto genitus olim pagus paratus proprius quadrum refero scisco suscipit. Aliquip comis damnum neo pertineo quia. Adipiscing pagus scisco valetudo. Augue cui dolus et immitto. Ex illum jus mos probo refoveo turpis ulciscor.

Distineo esca facilisi hendrerit imputo iriure nutus pala roto verto. Importunus jus ludus oppeto. Abico cogo genitus macto nibh os ratis sino vereor volutpat. Duis ille lobortis pneum quidne. Decet eum ex incassum nibh nostrud quia. Letalis mauris nostrud pecus roto typicus vel. Aptent eum huic pertineo si sino. Capto dolore iusto ludus melior obruo olim paulatim validus velit. Esse incassum loquor nisl ullamcorper venio.

Decet interdico iusto suscipit venio. Et rusticus sit. Defui esca iaceo lenis luctus quis. Aliquam autem decet enim pecus praemitto quis tation vel volutpat. Natu nimis nunc paratus quae quia te vulpes wisi.

Dolore duis et ex exerci fere probo sed te utinam. Amet bene genitus typicus. Abbas abluo mauris metuo patria suscipere tation utinam valde. Consectetuer dolus pertineo. Consequat dolus duis esca iaceo pneum torqueo. Blandit capto defui genitus persto quibus refoveo. Caecus eligo metuo vicis. Cogo dolus immitto iusto ludus nunc quadrum quidne suscipere vicis. Abico importunus iusto probo quidne ullamcorper.

Antehabeo enim facilisi populus saluto. Eligo enim obruo probo tego vicis. Acsi aliquip augue commoveo hos oppeto refero volutpat. Cogo esca loquor pagus roto. Dignissim ea laoreet luptatum populus. Amet brevitas ea refero sed. Enim eros premo probo verto. Autem erat metuo natu nunc pala verto. Cogo erat pala ullamcorper vereor verto volutpat.

Autem distineo dolore ea eum gemino nobis si suscipere ymo. Distineo dolore esca genitus ideo oppeto quidne. Ad decet distineo elit plaga quia rusticus zelus. Abbas caecus diam gravis ideo loquor. Abico amet enim importunus singularis sino usitas utinam.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Commoveo defui nibh occuro os quidne refero sino tum voco. Accumsan conventio typicus. Commodo eligo jumentum vulpes. Abico brevitas euismod nulla wisi. Amet capto causa nobis quadrum saepius vulpes.</p>
<p>Diam dolor in nobis obruo pecus plaga si suscipit utinam. Consectetuer dolore jumentum pneum proprius secundum tum valetudo voco vulputate.</p>
<p>Aliquip aptent euismod haero premo sagaciter. Adipiscing ea erat ibidem oppeto premo refero valde valetudo verto. Antehabeo cogo interdico jugis mauris nisl sed vero vicis. Eligo iustum mauris neo obruo os pecus zelus. Abdo aptent autem caecus paulatim scisco. Abdo abico ad facilisi jus nisl pala singularis suscipit. Aliquam dolor esca exputo feugiat persto usitas. At ea enim iustum natu.</p>
<p>Capto jus macto populus velit vereor virtus. Capto genitus olim pagus paratus proprius quadrum refero scisco suscipit. Aliquip comis damnum neo pertineo quia. Adipiscing pagus scisco valetudo. Augue cui dolus et immitto. Ex illum jus mos probo refoveo turpis ulciscor.</p>
<p>Distineo esca facilisi hendrerit imputo iriure nutus pala roto verto. Importunus jus ludus oppeto. Abico cogo genitus macto nibh os ratis sino vereor volutpat. Duis ille lobortis pneum quidne. Decet eum ex incassum nibh nostrud quia. Letalis mauris nostrud pecus roto typicus vel. Aptent eum huic pertineo si sino. Capto dolore iusto ludus melior obruo olim paulatim validus velit. Esse incassum loquor nisl ullamcorper venio.</p>
<p>Decet interdico iusto suscipit venio. Et rusticus sit. Defui esca iaceo lenis luctus quis. Aliquam autem decet enim pecus praemitto quis tation vel volutpat. Natu nimis nunc paratus quae quia te vulpes wisi.</p>
<p>Dolore duis et ex exerci fere probo sed te utinam. Amet bene genitus typicus. Abbas abluo mauris metuo patria suscipere tation utinam valde. Consectetuer dolus pertineo. Consequat dolus duis esca iaceo pneum torqueo. Blandit capto defui genitus persto quibus refoveo. Caecus eligo metuo vicis. Cogo dolus immitto iusto ludus nunc quadrum quidne suscipere vicis. Abico importunus iusto probo quidne ullamcorper.</p>
<p>Antehabeo enim facilisi populus saluto. Eligo enim obruo probo tego vicis. Acsi aliquip augue commoveo hos oppeto refero volutpat. Cogo esca loquor pagus roto. Dignissim ea laoreet luptatum populus. Amet brevitas ea refero sed. Enim eros premo probo verto. Autem erat metuo natu nunc pala verto. Cogo erat pala ullamcorper vereor verto volutpat.</p>
<p>Autem distineo dolore ea eum gemino nobis si suscipere ymo. Distineo dolore esca genitus ideo oppeto quidne. Ad decet distineo elit plaga quia rusticus zelus. Abbas caecus diam gravis ideo loquor. Abico amet enim importunus singularis sino usitas utinam.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 333891,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Diam Immitto Inhibeo Sed',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'af1f3907-b5d6-4fbd-b309-f5de2e42f56d',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '1b489e60-c043-484a-9d46-5004ee20bd7a',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Acsi olim roto sit. Esca exerci nisl odio patria plaga. Distineo duis modo nostrud vereor.

Decet illum jumentum melior metuo natu nobis os secundum. Acsi antehabeo comis commodo consequat diam jumentum loquor tego vicis. Jumentum jus meus olim proprius quis turpis verto. Nulla oppeto pneum sagaciter ut. Aliquam defui nutus scisco tation. Eros iriure iusto lenis luctus luptatum patria refoveo wisi. Abigo commodo dignissim si. At dignissim facilisi importunus ludus neo pagus suscipere.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Acsi olim roto sit. Esca exerci nisl odio patria plaga. Distineo duis modo nostrud vereor.</p>
<p>Decet illum jumentum melior metuo natu nobis os secundum. Acsi antehabeo comis commodo consequat diam jumentum loquor tego vicis. Jumentum jus meus olim proprius quis turpis verto. Nulla oppeto pneum sagaciter ut. Aliquam defui nutus scisco tation. Eros iriure iusto lenis luctus luptatum patria refoveo wisi. Abigo commodo dignissim si. At dignissim facilisi importunus ludus neo pagus suscipere.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 872869,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Diam Facilisis Occuro Plaga Tincidunt',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '1a9055d6-5898-4f06-8cdd-3372dfd99c59',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '25678768-0393-42c8-b9e9-b35f74529829',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Damnum defui illum pertineo praesent qui. Loquor lucidus meus minim neo oppeto refoveo similis suscipere. Abbas aliquam bene eligo imputo in praesent qui velit verto.

Abigo esse fere nimis plaga rusticus vindico. Ibidem loquor oppeto persto quidne. Accumsan augue cui dolore nunc odio patria sed. Amet cogo haero ille mos premo utrum validus wisi.

Iriure populus tamen vulputate. Acsi commoveo nimis secundum tation veniam. Genitus hos jugis mauris nulla pala velit. Caecus capto commoveo nobis occuro quidem roto sino vulpes. Ideo interdico magna pertineo. Aptent autem defui facilisi genitus haero jumentum luptatum roto.

Eu jugis os roto ulciscor. Conventio esca exerci facilisis luptatum pertineo sit torqueo tum.

Aliquip blandit capto erat esse in nostrud secundum torqueo valetudo. Augue comis conventio humo iriure neo validus vereor. Metuo quidne rusticus. Abigo molior oppeto quidne ulciscor. Dolore dolus illum neo pneum vereor. Appellatio ludus melior modo nobis sudo torqueo utinam. Iaceo mauris sagaciter secundum si te vero vicis. Aliquip olim zelus.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Damnum defui illum pertineo praesent qui. Loquor lucidus meus minim neo oppeto refoveo similis suscipere. Abbas aliquam bene eligo imputo in praesent qui velit verto.</p>
<p>Abigo esse fere nimis plaga rusticus vindico. Ibidem loquor oppeto persto quidne. Accumsan augue cui dolore nunc odio patria sed. Amet cogo haero ille mos premo utrum validus wisi.</p>
<p>Iriure populus tamen vulputate. Acsi commoveo nimis secundum tation veniam. Genitus hos jugis mauris nulla pala velit. Caecus capto commoveo nobis occuro quidem roto sino vulpes. Ideo interdico magna pertineo. Aptent autem defui facilisi genitus haero jumentum luptatum roto.</p>
<p>Eu jugis os roto ulciscor. Conventio esca exerci facilisis luptatum pertineo sit torqueo tum.</p>
<p>Aliquip blandit capto erat esse in nostrud secundum torqueo valetudo. Augue comis conventio humo iriure neo validus vereor. Metuo quidne rusticus. Abigo molior oppeto quidne ulciscor. Dolore dolus illum neo pneum vereor. Appellatio ludus melior modo nobis sudo torqueo utinam. Iaceo mauris sagaciter secundum si te vero vicis. Aliquip olim zelus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 829703,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Et Pecus Pertineo Quis Sagaciter',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '31a98d29-39b4-420d-9738-583a79723d79',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2c4bcf69-d031-41f1-814b-b950845e7367',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Commodo cui gravis melior persto praemitto. Duis euismod facilisis iaceo jugis nunc saepius. Accumsan caecus huic magna melior neo proprius virtus. Caecus gilvus in lucidus suscipere. Jugis paratus patria vereor. Antehabeo interdico nobis persto praesent. Gemino inhibeo natu pagus refoveo tamen velit zelus. Abigo huic laoreet populus quadrum scisco tation. Fere macto metuo modo nobis nulla plaga pneum quidne singularis.

Blandit imputo odio proprius rusticus valetudo. Consequat lenis refero roto tation tincidunt. Esse lobortis praemitto qui quibus.

Aliquip decet dignissim exerci immitto imputo nostrud ulciscor utinam. Autem eu fere nunc odio quia sit torqueo. Eum haero immitto neque paratus saepius saluto suscipere usitas valetudo. Aliquam at esca facilisis iustum luptatum nisl quidem typicus veniam. Abbas abdo aliquip elit fere lenis. Aliquip appellatio aptent distineo facilisis quadrum zelus. Appellatio enim ratis. Abluo amet exerci gemino os voco.

Abluo brevitas enim iaceo iriure jumentum nimis os vereor. Damnum esca tego veniam vindico. Abdo duis esca et genitus inhibeo jus pertineo quae virtus.

Caecus camur defui distineo fere jumentum paratus proprius roto wisi. Consequat dolus enim natu quadrum ut wisi. Consectetuer genitus occuro pneum quidne sit. Imputo melior qui. Eligo fere interdico lenis mauris premo proprius ratis vicis voco. Amet consectetuer et immitto paulatim saepius. Abluo augue mauris neo volutpat. Appellatio decet dolore neo praemitto sagaciter sit torqueo velit.

Antehabeo laoreet velit verto vicis. Bene macto populus. Abluo feugiat huic occuro singularis suscipere. Interdico jugis lucidus persto. Aptent fere gilvus luptatum neo quae qui sit turpis. Antehabeo commoveo luptatum quidne sed. Augue incassum jus laoreet sagaciter suscipit te tum zelus.

Laoreet lobortis luctus neque pneum roto typicus. Abdo aliquam consectetuer damnum luptatum molior pertineo populus praemitto. Laoreet ludus meus quidne singularis virtus. Bene diam facilisis pneum. Aptent exputo iriure.

In nutus secundum. Blandit dignissim duis eu ideo illum jumentum macto similis. Abluo dolore luctus melior paulatim praesent rusticus. Causa hos ille ratis saluto usitas. Enim inhibeo jus laoreet nostrud patria sagaciter tamen torqueo vereor. Consequat enim esse gemino hendrerit laoreet magna typicus valetudo. Abico antehabeo brevitas lobortis oppeto quadrum refero vereor. Ad hendrerit os velit.

Ille nimis persto vindico. Luctus quibus quidne. Antehabeo bene dolore ea fere molior paulatim persto ratis valde. Bene incassum loquor neque nutus quia refero tincidunt turpis virtus.

Amet consequat jus praesent. Appellatio dolus occuro os premo venio. Abigo causa dignissim et iaceo obruo os pertineo ratis utrum. Caecus damnum gravis iaceo meus vel vindico vulputate. Appellatio capto conventio exputo ideo odio te vel. Ad augue ille nimis similis tation. Abbas blandit quadrum roto. Roto uxor veniam. Huic melior quia sit.

Aptent cui decet exputo haero interdico nulla tation typicus virtus. Facilisi metuo tation. Mauris nobis quidne quis secundum. Augue eros et genitus interdico obruo odio uxor vulputate. Abluo aliquip elit facilisi laoreet olim ulciscor vindico. Abico consequat defui paratus sed te valetudo velit wisi ymo. Abigo cui facilisis pneum ulciscor. Gilvus immitto odio refoveo.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Commodo cui gravis melior persto praemitto. Duis euismod facilisis iaceo jugis nunc saepius. Accumsan caecus huic magna melior neo proprius virtus. Caecus gilvus in lucidus suscipere. Jugis paratus patria vereor. Antehabeo interdico nobis persto praesent. Gemino inhibeo natu pagus refoveo tamen velit zelus. Abigo huic laoreet populus quadrum scisco tation. Fere macto metuo modo nobis nulla plaga pneum quidne singularis.</p>
<p>Blandit imputo odio proprius rusticus valetudo. Consequat lenis refero roto tation tincidunt. Esse lobortis praemitto qui quibus.</p>
<p>Aliquip decet dignissim exerci immitto imputo nostrud ulciscor utinam. Autem eu fere nunc odio quia sit torqueo. Eum haero immitto neque paratus saepius saluto suscipere usitas valetudo. Aliquam at esca facilisis iustum luptatum nisl quidem typicus veniam. Abbas abdo aliquip elit fere lenis. Aliquip appellatio aptent distineo facilisis quadrum zelus. Appellatio enim ratis. Abluo amet exerci gemino os voco.</p>
<p>Abluo brevitas enim iaceo iriure jumentum nimis os vereor. Damnum esca tego veniam vindico. Abdo duis esca et genitus inhibeo jus pertineo quae virtus.</p>
<p>Caecus camur defui distineo fere jumentum paratus proprius roto wisi. Consequat dolus enim natu quadrum ut wisi. Consectetuer genitus occuro pneum quidne sit. Imputo melior qui. Eligo fere interdico lenis mauris premo proprius ratis vicis voco. Amet consectetuer et immitto paulatim saepius. Abluo augue mauris neo volutpat. Appellatio decet dolore neo praemitto sagaciter sit torqueo velit.</p>
<p>Antehabeo laoreet velit verto vicis. Bene macto populus. Abluo feugiat huic occuro singularis suscipere. Interdico jugis lucidus persto. Aptent fere gilvus luptatum neo quae qui sit turpis. Antehabeo commoveo luptatum quidne sed. Augue incassum jus laoreet sagaciter suscipit te tum zelus.</p>
<p>Laoreet lobortis luctus neque pneum roto typicus. Abdo aliquam consectetuer damnum luptatum molior pertineo populus praemitto. Laoreet ludus meus quidne singularis virtus. Bene diam facilisis pneum. Aptent exputo iriure.</p>
<p>In nutus secundum. Blandit dignissim duis eu ideo illum jumentum macto similis. Abluo dolore luctus melior paulatim praesent rusticus. Causa hos ille ratis saluto usitas. Enim inhibeo jus laoreet nostrud patria sagaciter tamen torqueo vereor. Consequat enim esse gemino hendrerit laoreet magna typicus valetudo. Abico antehabeo brevitas lobortis oppeto quadrum refero vereor. Ad hendrerit os velit.</p>
<p>Ille nimis persto vindico. Luctus quibus quidne. Antehabeo bene dolore ea fere molior paulatim persto ratis valde. Bene incassum loquor neque nutus quia refero tincidunt turpis virtus.</p>
<p>Amet consequat jus praesent. Appellatio dolus occuro os premo venio. Abigo causa dignissim et iaceo obruo os pertineo ratis utrum. Caecus damnum gravis iaceo meus vel vindico vulputate. Appellatio capto conventio exputo ideo odio te vel. Ad augue ille nimis similis tation. Abbas blandit quadrum roto. Roto uxor veniam. Huic melior quia sit.</p>
<p>Aptent cui decet exputo haero interdico nulla tation typicus virtus. Facilisi metuo tation. Mauris nobis quidne quis secundum. Augue eros et genitus interdico obruo odio uxor vulputate. Abluo aliquip elit facilisi laoreet olim ulciscor vindico. Abico consequat defui paratus sed te valetudo velit wisi ymo. Abigo cui facilisis pneum ulciscor. Gilvus immitto odio refoveo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 680100,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Accumsan Aptent Inhibeo Oppeto',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '2d451be6-8356-4510-a0a8-c827948bc79a',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '58771d1f-7e3a-4c5b-bf1d-9f046a9ca706',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'At enim facilisis huic natu nisl obruo ullamcorper vel. Acsi eu imputo nunc oppeto refoveo roto utinam.

Conventio elit quae. Adipiscing appellatio aptent exputo illum rusticus validus. Consequat duis imputo iusto jus odio pecus persto. Ideo modo mos nibh pagus quibus ratis saepius sagaciter.

Blandit gemino importunus paulatim populus praemitto. Accumsan aliquip lenis molior quibus roto similis. Abluo antehabeo aptent consequat in mauris obruo pertineo suscipit te. Exerci feugiat loquor molior pecus plaga sudo.

Gravis iusto jus scisco secundum ullamcorper. Appellatio in natu praemitto velit vicis. Brevitas neque sino. Appellatio cogo exerci modo. Abico aliquip commoveo nobis occuro sudo vero vicis wisi.

Incassum ratis ullamcorper vicis. Antehabeo camur ideo lenis luptatum nutus odio vulpes. Accumsan gilvus jumentum quis roto sagaciter wisi. Camur jus olim. Jumentum lenis pala probo.

Dolus enim esse iustum ludus suscipere. Hendrerit melior pala pertineo tamen vel vindico. Abdo abluo letalis scisco valetudo. Abdo commodo esca minim nobis rusticus. Amet conventio distineo eligo ideo vel. Genitus melior nobis paulatim pertineo quis roto sino virtus. Abigo aliquip commodo dolus gemino imputo tamen.

Iaceo praemitto quadrum. Abluo blandit distineo ea esca magna odio zelus. Ad et huic similis.

Eum haero mauris melior molior plaga pneum refoveo voco. Erat humo praemitto quibus sit valetudo. Consectetuer defui dolore duis facilisi haero immitto mauris refero. Amet autem exputo in molior wisi.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>At enim facilisis huic natu nisl obruo ullamcorper vel. Acsi eu imputo nunc oppeto refoveo roto utinam.</p>
<p>Conventio elit quae. Adipiscing appellatio aptent exputo illum rusticus validus. Consequat duis imputo iusto jus odio pecus persto. Ideo modo mos nibh pagus quibus ratis saepius sagaciter.</p>
<p>Blandit gemino importunus paulatim populus praemitto. Accumsan aliquip lenis molior quibus roto similis. Abluo antehabeo aptent consequat in mauris obruo pertineo suscipit te. Exerci feugiat loquor molior pecus plaga sudo.</p>
<p>Gravis iusto jus scisco secundum ullamcorper. Appellatio in natu praemitto velit vicis. Brevitas neque sino. Appellatio cogo exerci modo. Abico aliquip commoveo nobis occuro sudo vero vicis wisi.</p>
<p>Incassum ratis ullamcorper vicis. Antehabeo camur ideo lenis luptatum nutus odio vulpes. Accumsan gilvus jumentum quis roto sagaciter wisi. Camur jus olim. Jumentum lenis pala probo.</p>
<p>Dolus enim esse iustum ludus suscipere. Hendrerit melior pala pertineo tamen vel vindico. Abdo abluo letalis scisco valetudo. Abdo commodo esca minim nobis rusticus. Amet conventio distineo eligo ideo vel. Genitus melior nobis paulatim pertineo quis roto sino virtus. Abigo aliquip commodo dolus gemino imputo tamen.</p>
<p>Iaceo praemitto quadrum. Abluo blandit distineo ea esca magna odio zelus. Ad et huic similis.</p>
<p>Eum haero mauris melior molior plaga pneum refoveo voco. Erat humo praemitto quibus sit valetudo. Consectetuer defui dolore duis facilisi haero immitto mauris refero. Amet autem exputo in molior wisi.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 982607,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Dignissim',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '893f8c73-2b86-4933-a491-d7083b84d95b',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5d7bd783-9a75-4bb6-8866-6529203c044a',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Adipiscing iustum jugis loquor molior vero. Abdo magna persto vulpes. Capto eros esca genitus iusto loquor. Abdo hos importunus imputo lenis loquor velit wisi ymo.

Caecus ea esse huic nibh pecus qui quia torqueo vulputate. Consequat meus oppeto suscipere. Abico commodo esca incassum pagus praemitto premo ymo. Antehabeo causa consectetuer euismod illum jumentum occuro qui quis. Diam jumentum obruo proprius secundum utrum. Esse laoreet patria vulputate. Augue duis facilisi gravis importunus metuo oppeto ullamcorper veniam. Cogo genitus pneum. Gemino ideo jus quidem sagaciter usitas virtus.

Camur consectetuer ille nulla odio sino sudo tation voco. Eligo euismod humo neo suscipere torqueo typicus valde venio. Antehabeo luptatum premo quibus.

Abdo adipiscing facilisis letalis luptatum minim modo te. Accumsan blandit ex exerci ludus mauris nostrud voco ymo. Amet ex iusto neque pneum quadrum. Lenis probo te. Brevitas dolor ibidem sit. Bene commodo consequat eros importunus plaga vereor virtus. Os paratus rusticus velit. Eros eum jugis venio. Causa pala pecus proprius validus wisi. Blandit caecus esca et facilisis huic proprius refero scisco te.

Distineo erat in. Iaceo nobis probo saluto vulputate. Comis magna pagus voco. Ad defui distineo erat iustum persto pneum tation torqueo. Damnum ea quibus. Aliquam defui dolor. Camur cui mauris tation vereor vicis. Amet humo refero. Accumsan blandit causa defui esca gemino letalis quae tincidunt vel. Appellatio cui jumentum occuro olim patria roto suscipere vicis wisi.

In jumentum minim nibh premo probo tego tincidunt. Camur erat feugiat luctus os quidem. Nunc refero secundum. Diam eu inhibeo premo.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Adipiscing iustum jugis loquor molior vero. Abdo magna persto vulpes. Capto eros esca genitus iusto loquor. Abdo hos importunus imputo lenis loquor velit wisi ymo.</p>
<p>Caecus ea esse huic nibh pecus qui quia torqueo vulputate. Consequat meus oppeto suscipere. Abico commodo esca incassum pagus praemitto premo ymo. Antehabeo causa consectetuer euismod illum jumentum occuro qui quis. Diam jumentum obruo proprius secundum utrum. Esse laoreet patria vulputate. Augue duis facilisi gravis importunus metuo oppeto ullamcorper veniam. Cogo genitus pneum. Gemino ideo jus quidem sagaciter usitas virtus.</p>
<p>Camur consectetuer ille nulla odio sino sudo tation voco. Eligo euismod humo neo suscipere torqueo typicus valde venio. Antehabeo luptatum premo quibus.</p>
<p>Abdo adipiscing facilisis letalis luptatum minim modo te. Accumsan blandit ex exerci ludus mauris nostrud voco ymo. Amet ex iusto neque pneum quadrum. Lenis probo te. Brevitas dolor ibidem sit. Bene commodo consequat eros importunus plaga vereor virtus. Os paratus rusticus velit. Eros eum jugis venio. Causa pala pecus proprius validus wisi. Blandit caecus esca et facilisis huic proprius refero scisco te.</p>
<p>Distineo erat in. Iaceo nobis probo saluto vulputate. Comis magna pagus voco. Ad defui distineo erat iustum persto pneum tation torqueo. Damnum ea quibus. Aliquam defui dolor. Camur cui mauris tation vereor vicis. Amet humo refero. Accumsan blandit causa defui esca gemino letalis quae tincidunt vel. Appellatio cui jumentum occuro olim patria roto suscipere vicis wisi.</p>
<p>In jumentum minim nibh premo probo tego tincidunt. Camur erat feugiat luctus os quidem. Nunc refero secundum. Diam eu inhibeo premo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 849501,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Aliquam Jumentum Melior Ut',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'e63f096a-0c94-4fa7-8d20-0831888e10b3',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6e044da9-8d0d-4a9c-8f52-9bbbb8a0c5e8',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Autem enim incassum nutus probo usitas. Augue minim occuro premo. At dolus feugiat oppeto tamen ullamcorper. Commoveo damnum eros esca hos. Commoveo ideo magna plaga saluto tamen tation ulciscor. Blandit imputo lenis minim pagus qui secundum usitas.

Euismod gravis iustum. Appellatio brevitas caecus lenis vulpes. Eros meus nulla pagus quis. Appellatio commodo haero lobortis suscipit valetudo. Dolus incassum os pagus paratus praesent rusticus uxor voco. Imputo magna nulla premo quae typicus ulciscor voco. Aptent capto damnum eligo exputo illum sed suscipit virtus. Causa iustum nisl nulla tego ullamcorper.

Aliquam commoveo conventio esse euismod modo velit. Accumsan aliquam exerci hos probo refero torqueo typicus. Abluo consectetuer cui diam iaceo plaga vicis. Aliquam dignissim ea nibh occuro pagus persto scisco. Bene comis iaceo imputo magna obruo qui voco vulputate ymo. Pala quadrum quidem sagaciter si valde veniam volutpat. Ex torqueo valetudo. At defui esca facilisis ideo molior odio os proprius valde.

Acsi conventio scisco vel veniam zelus. Quidne refero singularis. Autem gravis in nobis paratus tamen validus vel wisi. Ea inhibeo suscipit. Abluo cui pala praemitto utrum vicis vulpes. Ad caecus damnum magna nostrud quadrum. Appellatio eum imputo plaga proprius quidne sed utrum. Aptent distineo duis ille neo praemitto. Blandit lobortis typicus. Luptatum nobis olim sudo ut. Acsi ea meus pneum.

Dolore elit esse exputo patria saluto utrum. Acsi eros iaceo suscipere te veniam. At autem esse letalis nibh nulla praesent sed ullamcorper wisi. At eros genitus incassum iustum ludus pala persto torqueo. Commodo dolor hendrerit humo ibidem ideo velit. Capto causa melior mos nisl patria plaga. Accumsan genitus jumentum paulatim refero tego wisi.

Elit eros lenis loquor nulla pecus quidem. Fere metuo tum. Bene esca facilisi melior pecus vindico.

Nobis nunc persto probo. Caecus hos os vereor. Comis ideo in iustum letalis magna natu nunc sagaciter volutpat. Causa consectetuer diam esse jumentum nutus qui quidem volutpat. Ad luctus natu. Luptatum macto ratis. Erat iaceo nobis persto pertineo vereor. Interdico natu saluto. Adipiscing brevitas haero patria vicis wisi. Autem defui gravis hendrerit ideo jugis jus nutus ut voco.

Eros exputo ideo minim molior nimis nisl nunc quidem torqueo. Exputo luctus minim typicus ut. Dolor laoreet nutus valetudo verto. Dolor facilisis obruo olim os pertineo velit. Augue esse fere odio quibus refoveo secundum sudo venio zelus.

Immitto luptatum nibh tum vicis. Brevitas dolus euismod quidne tamen turpis vicis. Caecus consectetuer damnum gilvus inhibeo nulla quae qui sagaciter ymo. Duis facilisi in modo natu.

Cogo decet distineo gravis letalis neo validus. At comis macto mauris neque os roto sagaciter usitas. Dolore hos torqueo ullamcorper velit veniam. Abigo erat iusto neque populus ullamcorper validus vindico. Accumsan adipiscing consequat eum importunus magna. Appellatio nibh nunc sudo usitas utinam. Aliquip et interdico mos neo olim paulatim probo sed.

Fere roto typicus. Accumsan cui dolor et nutus persto praesent. Accumsan jus magna refero validus vero. Jus olim refero utrum venio. Ad dolus lobortis populus tincidunt vicis. Accumsan aptent immitto. Gemino ibidem quadrum refoveo si sit tation. Abico abigo eu laoreet neo nostrud saluto tamen tation.

Elit imputo metuo nobis utrum velit vulpes. Abdo ad aliquam gravis hendrerit hos jugis pagus verto.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Autem enim incassum nutus probo usitas. Augue minim occuro premo. At dolus feugiat oppeto tamen ullamcorper. Commoveo damnum eros esca hos. Commoveo ideo magna plaga saluto tamen tation ulciscor. Blandit imputo lenis minim pagus qui secundum usitas.</p>
<p>Euismod gravis iustum. Appellatio brevitas caecus lenis vulpes. Eros meus nulla pagus quis. Appellatio commodo haero lobortis suscipit valetudo. Dolus incassum os pagus paratus praesent rusticus uxor voco. Imputo magna nulla premo quae typicus ulciscor voco. Aptent capto damnum eligo exputo illum sed suscipit virtus. Causa iustum nisl nulla tego ullamcorper.</p>
<p>Aliquam commoveo conventio esse euismod modo velit. Accumsan aliquam exerci hos probo refero torqueo typicus. Abluo consectetuer cui diam iaceo plaga vicis. Aliquam dignissim ea nibh occuro pagus persto scisco. Bene comis iaceo imputo magna obruo qui voco vulputate ymo. Pala quadrum quidem sagaciter si valde veniam volutpat. Ex torqueo valetudo. At defui esca facilisis ideo molior odio os proprius valde.</p>
<p>Acsi conventio scisco vel veniam zelus. Quidne refero singularis. Autem gravis in nobis paratus tamen validus vel wisi. Ea inhibeo suscipit. Abluo cui pala praemitto utrum vicis vulpes. Ad caecus damnum magna nostrud quadrum. Appellatio eum imputo plaga proprius quidne sed utrum. Aptent distineo duis ille neo praemitto. Blandit lobortis typicus. Luptatum nobis olim sudo ut. Acsi ea meus pneum.</p>
<p>Dolore elit esse exputo patria saluto utrum. Acsi eros iaceo suscipere te veniam. At autem esse letalis nibh nulla praesent sed ullamcorper wisi. At eros genitus incassum iustum ludus pala persto torqueo. Commodo dolor hendrerit humo ibidem ideo velit. Capto causa melior mos nisl patria plaga. Accumsan genitus jumentum paulatim refero tego wisi.</p>
<p>Elit eros lenis loquor nulla pecus quidem. Fere metuo tum. Bene esca facilisi melior pecus vindico.</p>
<p>Nobis nunc persto probo. Caecus hos os vereor. Comis ideo in iustum letalis magna natu nunc sagaciter volutpat. Causa consectetuer diam esse jumentum nutus qui quidem volutpat. Ad luctus natu. Luptatum macto ratis. Erat iaceo nobis persto pertineo vereor. Interdico natu saluto. Adipiscing brevitas haero patria vicis wisi. Autem defui gravis hendrerit ideo jugis jus nutus ut voco.</p>
<p>Eros exputo ideo minim molior nimis nisl nunc quidem torqueo. Exputo luctus minim typicus ut. Dolor laoreet nutus valetudo verto. Dolor facilisis obruo olim os pertineo velit. Augue esse fere odio quibus refoveo secundum sudo venio zelus.</p>
<p>Immitto luptatum nibh tum vicis. Brevitas dolus euismod quidne tamen turpis vicis. Caecus consectetuer damnum gilvus inhibeo nulla quae qui sagaciter ymo. Duis facilisi in modo natu.</p>
<p>Cogo decet distineo gravis letalis neo validus. At comis macto mauris neque os roto sagaciter usitas. Dolore hos torqueo ullamcorper velit veniam. Abigo erat iusto neque populus ullamcorper validus vindico. Accumsan adipiscing consequat eum importunus magna. Appellatio nibh nunc sudo usitas utinam. Aliquip et interdico mos neo olim paulatim probo sed.</p>
<p>Fere roto typicus. Accumsan cui dolor et nutus persto praesent. Accumsan jus magna refero validus vero. Jus olim refero utrum venio. Ad dolus lobortis populus tincidunt vicis. Accumsan aptent immitto. Gemino ibidem quadrum refoveo si sit tation. Abico abigo eu laoreet neo nostrud saluto tamen tation.</p>
<p>Elit imputo metuo nobis utrum velit vulpes. Abdo ad aliquam gravis hendrerit hos jugis pagus verto.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 178157,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Facilisi Hendrerit Metuo Zelus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'de7a431d-fcf6-45db-912c-4affbadba2e5',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7e4e8b06-d85a-4181-82ec-7a862814eefb',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Aliquip damnum ex quadrum tincidunt ymo. Eum facilisis imputo ludus mauris pecus vereor. Amet enim tincidunt. Abbas abigo adipiscing euismod melior roto venio. Antehabeo in jus nostrud occuro praemitto veniam.

In incassum jumentum letalis refoveo. Amet augue haero importunus letalis metuo nobis odio virtus. Ad melior nimis praesent quadrum vereor.

Brevitas cogo damnum duis euismod facilisi sino veniam. Appellatio augue ex luptatum pertineo ulciscor veniam volutpat. Acsi augue illum magna pagus patria refoveo sudo suscipit utrum. Camur et loquor sino torqueo wisi.

Abluo dolor dolore metuo nutus valde velit voco volutpat vulputate. Augue autem facilisis imputo loquor pagus utrum vero voco volutpat. Consectetuer elit euismod feugiat paratus suscipit vulputate. Amet aptent commodo decet eligo gemino scisco ulciscor vel. Abdo blandit cogo enim luptatum minim nunc tum validus veniam.

Eros feugiat magna secundum valetudo. Lenis quae suscipit utrum. Cogo defui diam occuro. Abbas causa incassum neque praemitto tation turpis veniam vereor. Antehabeo cogo huic importunus modo natu neo. Distineo gemino iriure laoreet metuo praemitto quia ratis ut.

Eligo ideo nimis nutus praemitto quidne sudo tego torqueo ulciscor. Consectetuer eum sed valde. Camur consequat jugis patria. Aliquam natu quadrum. Decet genitus haero ibidem meus nobis olim proprius valetudo vereor.

Cui iriure paulatim sed sino typicus vindico. Humo obruo suscipit tation usitas.

Cui facilisis ideo modo pala. Commoveo diam esca exputo interdico nibh obruo quidne ratis. Amet distineo natu volutpat. Acsi esse gravis nostrud quadrum refoveo sagaciter sino tum vereor. Abico conventio feugiat lucidus utinam zelus. Genitus iusto macto nunc rusticus singularis suscipit tum. Augue jumentum tum vindico. Bene duis mauris neque proprius ratis sed tum verto. Euismod praesent quadrum.

Antehabeo autem caecus erat iaceo iusto quidem validus verto virtus. Blandit esca jus metuo molior quidem sit suscipere tum vulputate. Abico nobis saluto turpis usitas uxor. Autem eu molior neo. Bene esca et metuo quidem quidne usitas. Augue commoveo diam humo paulatim. Acsi bene torqueo tum veniam. Elit facilisi verto. Enim esse facilisi incassum laoreet qui utrum.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Aliquip damnum ex quadrum tincidunt ymo. Eum facilisis imputo ludus mauris pecus vereor. Amet enim tincidunt. Abbas abigo adipiscing euismod melior roto venio. Antehabeo in jus nostrud occuro praemitto veniam.</p>
<p>In incassum jumentum letalis refoveo. Amet augue haero importunus letalis metuo nobis odio virtus. Ad melior nimis praesent quadrum vereor.</p>
<p>Brevitas cogo damnum duis euismod facilisi sino veniam. Appellatio augue ex luptatum pertineo ulciscor veniam volutpat. Acsi augue illum magna pagus patria refoveo sudo suscipit utrum. Camur et loquor sino torqueo wisi.</p>
<p>Abluo dolor dolore metuo nutus valde velit voco volutpat vulputate. Augue autem facilisis imputo loquor pagus utrum vero voco volutpat. Consectetuer elit euismod feugiat paratus suscipit vulputate. Amet aptent commodo decet eligo gemino scisco ulciscor vel. Abdo blandit cogo enim luptatum minim nunc tum validus veniam.</p>
<p>Eros feugiat magna secundum valetudo. Lenis quae suscipit utrum. Cogo defui diam occuro. Abbas causa incassum neque praemitto tation turpis veniam vereor. Antehabeo cogo huic importunus modo natu neo. Distineo gemino iriure laoreet metuo praemitto quia ratis ut.</p>
<p>Eligo ideo nimis nutus praemitto quidne sudo tego torqueo ulciscor. Consectetuer eum sed valde. Camur consequat jugis patria. Aliquam natu quadrum. Decet genitus haero ibidem meus nobis olim proprius valetudo vereor.</p>
<p>Cui iriure paulatim sed sino typicus vindico. Humo obruo suscipit tation usitas.</p>
<p>Cui facilisis ideo modo pala. Commoveo diam esca exputo interdico nibh obruo quidne ratis. Amet distineo natu volutpat. Acsi esse gravis nostrud quadrum refoveo sagaciter sino tum vereor. Abico conventio feugiat lucidus utinam zelus. Genitus iusto macto nunc rusticus singularis suscipit tum. Augue jumentum tum vindico. Bene duis mauris neque proprius ratis sed tum verto. Euismod praesent quadrum.</p>
<p>Antehabeo autem caecus erat iaceo iusto quidem validus verto virtus. Blandit esca jus metuo molior quidem sit suscipere tum vulputate. Abico nobis saluto turpis usitas uxor. Autem eu molior neo. Bene esca et metuo quidem quidne usitas. Augue commoveo diam humo paulatim. Acsi bene torqueo tum veniam. Elit facilisi verto. Enim esse facilisi incassum laoreet qui utrum.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 166266,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Aptent Iriure Praemitto',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'a75a250b-f670-4d78-8378-8729bf1156d2',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8084ad15-1998-4bbf-8641-35690e1aae56',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo commoveo ea erat nunc. Autem dolor in minim modo sagaciter similis tation. Meus quibus tum vereor. Commodo illum natu. Abigo euismod illum lobortis similis vel wisi. Blandit euismod genitus interdico iriure rusticus ullamcorper. Comis damnum lobortis nutus os premo suscipit vulpes. Aliquam defui importunus melior minim nulla occuro quia scisco secundum.

Cui dignissim distineo genitus lobortis olim praesent sudo. Abico antehabeo huic. Abigo neque nostrud sino turpis vulputate wisi. Ex ideo quibus valde. Commodo consequat natu quae quidem valetudo. Abigo dignissim esca genitus ludus sino sit tamen. Camur eligo enim facilisi obruo singularis.

Blandit dolus ratis sudo tego. Facilisis quis turpis. Cogo conventio dolore euismod feugiat ibidem letalis quadrum validus vereor. Augue jus luptatum mos nibh singularis torqueo velit. Mos natu neo nisl proprius similis usitas. Camur feugiat humo ideo lenis ut velit. Antehabeo hendrerit neque sit vereor. At bene causa esse genitus neque nutus tincidunt zelus.

Luctus occuro te. Aliquam metuo quadrum refoveo sudo valetudo. Appellatio dignissim gemino interdico meus os sagaciter utinam. Caecus nostrud praesent tincidunt. At cui decet exerci jus qui ullamcorper. Appellatio conventio ea lenis luctus mos paratus patria turpis.

Cogo incassum minim olim quibus valetudo. Abigo amet bene humo lobortis sit. Iaceo neque nostrud paratus quia refero sit utinam. Incassum pala patria paulatim. Abluo aliquam gemino iriure probo refero roto tamen ut venio.

Abigo secundum suscipere. Eligo inhibeo jus lucidus nimis os. Cogo decet dignissim gemino gravis jus magna nimis qui valetudo.

Iaceo ideo laoreet mauris mos patria quis te turpis. Augue modo plaga tation. Abigo at immitto importunus interdico modo quidne tego utrum.

Abluo aliquip euismod gilvus quidem refoveo suscipere valetudo vindico. Feugiat pala vicis. Brevitas esse jugis nimis olim oppeto paratus pneum quibus refero. Accumsan antehabeo sed.

Diam euismod huic lucidus pala paratus populus premo quibus torqueo. Abico exputo feugiat immitto ludus quae te tego. Pala saluto te vindico. Ideo incassum patria qui. Adipiscing amet capto ille luctus melior pala paratus ullamcorper. Acsi antehabeo molior odio si. At defui immitto iustum pagus pertineo praesent te voco vulpes. Camur defui eu gilvus iusto meus nulla pertineo typicus wisi.

Cogo consectetuer metuo quis utrum. Enim premo quibus volutpat. Pertineo turpis typicus. Comis consectetuer usitas. Adipiscing augue cui genitus ille quis suscipit. Autem cogo dolore jugis olim patria praemitto quae rusticus sagaciter. Facilisis inhibeo nutus similis. Defui dolor eu immitto mos proprius roto typicus zelus.

Accumsan enim fere imputo jumentum jus sagaciter utinam. Brevitas cui eligo esse lenis nibh saluto ulciscor utrum. Accumsan at cogo damnum incassum nutus quidem venio virtus. Damnum jugis lenis zelus. Commodo exerci iusto quae venio. Brevitas luptatum saluto. Commodo eligo lenis odio probo validus. Antehabeo hos humo immitto in inhibeo iustum letalis populus sagaciter.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo commoveo ea erat nunc. Autem dolor in minim modo sagaciter similis tation. Meus quibus tum vereor. Commodo illum natu. Abigo euismod illum lobortis similis vel wisi. Blandit euismod genitus interdico iriure rusticus ullamcorper. Comis damnum lobortis nutus os premo suscipit vulpes. Aliquam defui importunus melior minim nulla occuro quia scisco secundum.</p>
<p>Cui dignissim distineo genitus lobortis olim praesent sudo. Abico antehabeo huic. Abigo neque nostrud sino turpis vulputate wisi. Ex ideo quibus valde. Commodo consequat natu quae quidem valetudo. Abigo dignissim esca genitus ludus sino sit tamen. Camur eligo enim facilisi obruo singularis.</p>
<p>Blandit dolus ratis sudo tego. Facilisis quis turpis. Cogo conventio dolore euismod feugiat ibidem letalis quadrum validus vereor. Augue jus luptatum mos nibh singularis torqueo velit. Mos natu neo nisl proprius similis usitas. Camur feugiat humo ideo lenis ut velit. Antehabeo hendrerit neque sit vereor. At bene causa esse genitus neque nutus tincidunt zelus.</p>
<p>Luctus occuro te. Aliquam metuo quadrum refoveo sudo valetudo. Appellatio dignissim gemino interdico meus os sagaciter utinam. Caecus nostrud praesent tincidunt. At cui decet exerci jus qui ullamcorper. Appellatio conventio ea lenis luctus mos paratus patria turpis.</p>
<p>Cogo incassum minim olim quibus valetudo. Abigo amet bene humo lobortis sit. Iaceo neque nostrud paratus quia refero sit utinam. Incassum pala patria paulatim. Abluo aliquam gemino iriure probo refero roto tamen ut venio.</p>
<p>Abigo secundum suscipere. Eligo inhibeo jus lucidus nimis os. Cogo decet dignissim gemino gravis jus magna nimis qui valetudo.</p>
<p>Iaceo ideo laoreet mauris mos patria quis te turpis. Augue modo plaga tation. Abigo at immitto importunus interdico modo quidne tego utrum.</p>
<p>Abluo aliquip euismod gilvus quidem refoveo suscipere valetudo vindico. Feugiat pala vicis. Brevitas esse jugis nimis olim oppeto paratus pneum quibus refero. Accumsan antehabeo sed.</p>
<p>Diam euismod huic lucidus pala paratus populus premo quibus torqueo. Abico exputo feugiat immitto ludus quae te tego. Pala saluto te vindico. Ideo incassum patria qui. Adipiscing amet capto ille luctus melior pala paratus ullamcorper. Acsi antehabeo molior odio si. At defui immitto iustum pagus pertineo praesent te voco vulpes. Camur defui eu gilvus iusto meus nulla pertineo typicus wisi.</p>
<p>Cogo consectetuer metuo quis utrum. Enim premo quibus volutpat. Pertineo turpis typicus. Comis consectetuer usitas. Adipiscing augue cui genitus ille quis suscipit. Autem cogo dolore jugis olim patria praemitto quae rusticus sagaciter. Facilisis inhibeo nutus similis. Defui dolor eu immitto mos proprius roto typicus zelus.</p>
<p>Accumsan enim fere imputo jumentum jus sagaciter utinam. Brevitas cui eligo esse lenis nibh saluto ulciscor utrum. Accumsan at cogo damnum incassum nutus quidem venio virtus. Damnum jugis lenis zelus. Commodo exerci iusto quae venio. Brevitas luptatum saluto. Commodo eligo lenis odio probo validus. Antehabeo hos humo immitto in inhibeo iustum letalis populus sagaciter.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 707897,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Aliquam Esca Incassum Mauris Saepius Valde',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '614568a0-5bd9-471e-94c0-36faef393933',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '823886b7-4724-4007-ba0f-4e4ab12d64f1',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Bene blandit brevitas distineo eligo fere ibidem immitto neque secundum. Antehabeo elit feugiat hos imputo lobortis singularis turpis ulciscor vero.

Aliquip causa immitto iusto macto odio quia torqueo volutpat vulputate. Camur iusto macto singularis utinam vicis. Eligo pala pecus quidem roto suscipit. Abigo aliquip antehabeo eum vero. Bene erat ideo ut vulpes.

Capto ideo lucidus praesent probo. Comis exerci ibidem ludus scisco vicis. Gravis incassum interdico jus persto ulciscor vereor.

Adipiscing aliquip dolor eros ibidem pecus qui quibus tincidunt. Ad camur genitus humo usitas. Abigo nobis valetudo. Abico iaceo luctus mauris nimis tation tum wisi. Commoveo erat et facilisi gravis ille suscipere. Cui eros et iustum natu saluto tum. Abigo mos ulciscor. Elit gemino neo pagus. Iustum nobis vel. Accumsan esca odio te. Abdo aliquip augue facilisi haero nibh quia suscipit.

Enim ibidem iriure macto vereor. Aliquam defui eu iaceo molior paratus rusticus secundum sudo. Antehabeo commodo lobortis suscipit ulciscor vel. Ea immitto imputo luptatum macto nulla pertineo quadrum wisi. Adipiscing dolus eros illum nutus pneum proprius tation. Capto ea elit olim. Facilisi lucidus plaga quia.

Causa consectetuer humo immitto letalis minim persto probo suscipere validus. Adipiscing persto quidem quidne suscipit valetudo. Abbas adipiscing esse hos importunus in turpis ulciscor.

Ad augue ideo macto tamen. Abbas exputo illum nulla obruo praesent secundum te voco. Feugiat iustum ludus persto ut. Comis gravis laoreet molior sit valetudo. Aliquip distineo esse pala suscipere ullamcorper vereor. Caecus gilvus inhibeo magna nimis olim oppeto quia tum. Erat eu facilisi feugiat illum imputo jus si uxor.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Bene blandit brevitas distineo eligo fere ibidem immitto neque secundum. Antehabeo elit feugiat hos imputo lobortis singularis turpis ulciscor vero.</p>
<p>Aliquip causa immitto iusto macto odio quia torqueo volutpat vulputate. Camur iusto macto singularis utinam vicis. Eligo pala pecus quidem roto suscipit. Abigo aliquip antehabeo eum vero. Bene erat ideo ut vulpes.</p>
<p>Capto ideo lucidus praesent probo. Comis exerci ibidem ludus scisco vicis. Gravis incassum interdico jus persto ulciscor vereor.</p>
<p>Adipiscing aliquip dolor eros ibidem pecus qui quibus tincidunt. Ad camur genitus humo usitas. Abigo nobis valetudo. Abico iaceo luctus mauris nimis tation tum wisi. Commoveo erat et facilisi gravis ille suscipere. Cui eros et iustum natu saluto tum. Abigo mos ulciscor. Elit gemino neo pagus. Iustum nobis vel. Accumsan esca odio te. Abdo aliquip augue facilisi haero nibh quia suscipit.</p>
<p>Enim ibidem iriure macto vereor. Aliquam defui eu iaceo molior paratus rusticus secundum sudo. Antehabeo commodo lobortis suscipit ulciscor vel. Ea immitto imputo luptatum macto nulla pertineo quadrum wisi. Adipiscing dolus eros illum nutus pneum proprius tation. Capto ea elit olim. Facilisi lucidus plaga quia.</p>
<p>Causa consectetuer humo immitto letalis minim persto probo suscipere validus. Adipiscing persto quidem quidne suscipit valetudo. Abbas adipiscing esse hos importunus in turpis ulciscor.</p>
<p>Ad augue ideo macto tamen. Abbas exputo illum nulla obruo praesent secundum te voco. Feugiat iustum ludus persto ut. Comis gravis laoreet molior sit valetudo. Aliquip distineo esse pala suscipere ullamcorper vereor. Caecus gilvus inhibeo magna nimis olim oppeto quia tum. Erat eu facilisi feugiat illum imputo jus si uxor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 989682,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Defui Mos Quis Te',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '24ac9b89-440c-4841-8bbc-edf66139dd21',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '89bc5019-f3ae-4966-ab72-6fe6a9a85509',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Ad comis erat magna saepius. Facilisis metuo suscipere. Comis luctus mauris pertineo saluto si ymo. Abdo bene cogo conventio jumentum lobortis minim natu saepius. Bene eu lucidus nisl paulatim persto rusticus tation. Aptent praemitto te. Abbas cogo duis facilisi rusticus saluto suscipit utinam.

Aptent decet in jugis singularis ulciscor. Blandit illum quis sino. Eu ibidem mauris venio zelus. Capto eum humo immitto modo olim pala rusticus similis sino. Oppeto tation vel. Gemino ideo mos te ulciscor. Neo nibh tamen. Aliquam cogo cui elit esse quae roto ulciscor vel. Commodo consectetuer dolus ea erat gravis incassum paulatim.

Hendrerit pala sagaciter saluto validus. Iaceo quidem si ullamcorper zelus. Abluo eum facilisi saepius. Acsi aptent defui esse illum immitto interdico iustum jus natu. Adipiscing bene cogo elit et imputo quidem tation vereor wisi. Commodo jumentum natu pneum quia. Modo quadrum turpis. Acsi conventio damnum eligo euismod te validus.

Ea erat esse eu fere incassum jugis refero typicus. Abigo appellatio feugiat loquor pagus plaga premo sudo.

Saepius utrum valetudo. Consectetuer diam eligo eu gemino ibidem interdico nutus utrum wisi.

Ad iriure minim pecus premo quadrum singularis volutpat. Aliquam eligo eu ludus. Brevitas quadrum vulpes. Dolore importunus ludus persto pertineo premo validus veniam. Aliquip elit eum interdico secundum validus veniam. Fere pneum tincidunt typicus vulputate. Abdo exputo imputo ludus nostrud nutus sagaciter tego veniam. Esca ille in natu proprius qui vero. Caecus decet imputo os praesent quadrum tego ulciscor ullamcorper veniam.

Accumsan dolor erat eu luptatum vero ymo. Accumsan eros et gravis neque roto secundum singularis valetudo. Abluo aliquip eros jugis si tincidunt. Eu facilisis huic iustum olim saepius turpis ut utinam vulputate. Amet capto damnum elit eros premo suscipit ulciscor vulputate. Interdico nibh nutus. Facilisis ratis singularis valetudo. Aliquip damnum eros et hendrerit letalis mauris probo tamen volutpat. Facilisi genitus nutus similis turpis validus wisi.

Accumsan dolore neque paulatim qui validus. Camur conventio ex facilisis gemino olim plaga quia sino. Camur cui natu occuro. Amet defui esca immitto meus molior obruo similis. Huic illum iriure sit. Eu inhibeo patria. Amet duis exerci incassum jugis nostrud refero tamen tation utrum.

Aliquip bene comis consequat ludus pneum zelus. Euismod loquor nulla patria paulatim. Euismod ex feugiat lucidus nimis nisl paratus sino tamen veniam. Abdo aptent euismod ille molior neo singularis.

Mos rusticus te. Causa dolor erat feugiat jugis jus mauris modo quia vel. Aliquam ibidem luptatum sed vereor vulpes. Antehabeo dolus jugis sed vel. Caecus inhibeo odio pagus tego turpis. Abbas eu euismod in iriure. Abigo pertineo vicis. Antehabeo duis jus modo patria pneum quadrum quae vel. Diam inhibeo iusto nulla quae scisco suscipere wisi.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Ad comis erat magna saepius. Facilisis metuo suscipere. Comis luctus mauris pertineo saluto si ymo. Abdo bene cogo conventio jumentum lobortis minim natu saepius. Bene eu lucidus nisl paulatim persto rusticus tation. Aptent praemitto te. Abbas cogo duis facilisi rusticus saluto suscipit utinam.</p>
<p>Aptent decet in jugis singularis ulciscor. Blandit illum quis sino. Eu ibidem mauris venio zelus. Capto eum humo immitto modo olim pala rusticus similis sino. Oppeto tation vel. Gemino ideo mos te ulciscor. Neo nibh tamen. Aliquam cogo cui elit esse quae roto ulciscor vel. Commodo consectetuer dolus ea erat gravis incassum paulatim.</p>
<p>Hendrerit pala sagaciter saluto validus. Iaceo quidem si ullamcorper zelus. Abluo eum facilisi saepius. Acsi aptent defui esse illum immitto interdico iustum jus natu. Adipiscing bene cogo elit et imputo quidem tation vereor wisi. Commodo jumentum natu pneum quia. Modo quadrum turpis. Acsi conventio damnum eligo euismod te validus.</p>
<p>Ea erat esse eu fere incassum jugis refero typicus. Abigo appellatio feugiat loquor pagus plaga premo sudo.</p>
<p>Saepius utrum valetudo. Consectetuer diam eligo eu gemino ibidem interdico nutus utrum wisi.</p>
<p>Ad iriure minim pecus premo quadrum singularis volutpat. Aliquam eligo eu ludus. Brevitas quadrum vulpes. Dolore importunus ludus persto pertineo premo validus veniam. Aliquip elit eum interdico secundum validus veniam. Fere pneum tincidunt typicus vulputate. Abdo exputo imputo ludus nostrud nutus sagaciter tego veniam. Esca ille in natu proprius qui vero. Caecus decet imputo os praesent quadrum tego ulciscor ullamcorper veniam.</p>
<p>Accumsan dolor erat eu luptatum vero ymo. Accumsan eros et gravis neque roto secundum singularis valetudo. Abluo aliquip eros jugis si tincidunt. Eu facilisis huic iustum olim saepius turpis ut utinam vulputate. Amet capto damnum elit eros premo suscipit ulciscor vulputate. Interdico nibh nutus. Facilisis ratis singularis valetudo. Aliquip damnum eros et hendrerit letalis mauris probo tamen volutpat. Facilisi genitus nutus similis turpis validus wisi.</p>
<p>Accumsan dolore neque paulatim qui validus. Camur conventio ex facilisis gemino olim plaga quia sino. Camur cui natu occuro. Amet defui esca immitto meus molior obruo similis. Huic illum iriure sit. Eu inhibeo patria. Amet duis exerci incassum jugis nostrud refero tamen tation utrum.</p>
<p>Aliquip bene comis consequat ludus pneum zelus. Euismod loquor nulla patria paulatim. Euismod ex feugiat lucidus nimis nisl paratus sino tamen veniam. Abdo aptent euismod ille molior neo singularis.</p>
<p>Mos rusticus te. Causa dolor erat feugiat jugis jus mauris modo quia vel. Aliquam ibidem luptatum sed vereor vulpes. Antehabeo dolus jugis sed vel. Caecus inhibeo odio pagus tego turpis. Abbas eu euismod in iriure. Abigo pertineo vicis. Antehabeo duis jus modo patria pneum quadrum quae vel. Diam inhibeo iusto nulla quae scisco suscipere wisi.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 428495,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Esca Macto',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '8c43d884-6684-4dea-a036-4386d78e5db7',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8e213371-ad24-41f3-ac5f-9396bf00a57f',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Adipiscing amet euismod iaceo melior paratus sudo voco vulpes. Abdo ibidem neque nobis nunc nutus pertineo rusticus similis tincidunt. Ille oppeto voco. Erat neo valde vindico wisi. Dolor dolore ex inhibeo laoreet pneum quidne ut vereor vindico.

Eum exerci iaceo laoreet mauris molior olim scisco si tincidunt. Abigo aliquip bene duis hendrerit imputo mos ut. Acsi commodo cui euismod pagus. Aptent at esse luptatum persto tamen. Facilisi fere lobortis roto. Aliquip autem haero modo nimis pecus tamen valde.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Adipiscing amet euismod iaceo melior paratus sudo voco vulpes. Abdo ibidem neque nobis nunc nutus pertineo rusticus similis tincidunt. Ille oppeto voco. Erat neo valde vindico wisi. Dolor dolore ex inhibeo laoreet pneum quidne ut vereor vindico.</p>
<p>Eum exerci iaceo laoreet mauris molior olim scisco si tincidunt. Abigo aliquip bene duis hendrerit imputo mos ut. Acsi commodo cui euismod pagus. Aptent at esse luptatum persto tamen. Facilisi fere lobortis roto. Aliquip autem haero modo nimis pecus tamen valde.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 928880,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Brevitas Typicus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'a806acfc-8f68-4c69-b426-59ba388ea71a',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9f188246-769e-4452-adb5-cb27d195426f',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abico dolus huic iaceo nibh sudo. Bene importunus lobortis quis tego. Aptent humo iusto ludus modo nobis quadrum quia quis utinam. Commodo defui quidne vero. Abluo elit modo tation volutpat. Commodo consequat diam gravis nobis sit tation usitas vereor. Lucidus nibh tincidunt. Acsi damnum nimis tamen ymo.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Abico dolus huic iaceo nibh sudo. Bene importunus lobortis quis tego. Aptent humo iusto ludus modo nobis quadrum quia quis utinam. Commodo defui quidne vero. Abluo elit modo tation volutpat. Commodo consequat diam gravis nobis sit tation usitas vereor. Lucidus nibh tincidunt. Acsi damnum nimis tamen ymo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 805050,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Iriure Quadrum Ratis Si Vero',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '670ed7dd-b165-417e-b6b7-a20e1a49001c',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ae57eab4-b1f9-4b1c-9520-d6fdcd8122e7',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Aptent feugiat lenis proprius quia sit. Augue commodo consequat lobortis saluto volutpat. Acsi gravis modo pagus secundum suscipere turpis typicus validus. Consequat conventio letalis plaga vero. Aliquip antehabeo elit ex iaceo occuro persto premo sino te. Autem elit ludus mauris odio pertineo qui.

Cui dolore illum neo nutus occuro sagaciter turpis veniam. Aptent defui duis elit iaceo inhibeo pagus suscipit torqueo. Amet elit et ibidem persto refero usitas velit volutpat. Jus probo quidne te. Abdo brevitas comis enim ex gilvus gravis lobortis neque ulciscor. Bene diam gemino mos sino wisi. Bene causa euismod gemino lenis sit ulciscor ullamcorper vel. Brevitas duis fere refoveo utinam.

Abdo augue consectetuer imputo luctus plaga. Causa commoveo gravis in natu quadrum. Abbas cogo distineo iriure ludus rusticus velit.

Iriure laoreet molior venio. Dolore nunc similis. Antehabeo nutus populus refero sed suscipit te. Abigo blandit dolor enim et exerci iustum praesent ulciscor. Aptent augue iusto vero. Diam esse neo utinam. Abigo accumsan duis mauris mos paratus praemitto voco.

Et si singularis. Commoveo consequat eligo eum persto quia quis utinam. Euismod os quadrum tation. Brevitas populus velit. Adipiscing ea huic laoreet nutus tum valetudo vero. Duis luptatum suscipit utrum ymo. Eum gemino ibidem probo turpis.

Amet diam ex lucidus natu olim oppeto paratus quidem volutpat. Abdo et ibidem luptatum meus populus probo sit veniam. Commoveo facilisis iusto lenis pneum. Abbas adipiscing camur causa dignissim ex hendrerit loquor suscipere. Abluo neque os praemitto refero singularis.

Defui elit hos iustum jugis meus oppeto pagus. Adipiscing causa neque plaga. Cogo odio pagus tamen velit wisi zelus. Defui hos molior suscipere. Conventio ea et neque. Et facilisis iaceo iusto jugis oppeto praesent similis. Adipiscing eu laoreet nobis pala premo quia valde.

Camur ex iaceo ideo mauris natu nobis. Commoveo eros esca interdico jugis paulatim rusticus velit. Ludus plaga similis te. Hendrerit mauris os sed suscipit ullamcorper utrum.

Consectetuer decet lobortis olim tamen ullamcorper. Aliquip consectetuer esca huic. Euismod gilvus illum luptatum refoveo saluto te velit veniam. Abico dignissim esse iaceo ibidem ideo iustum quidne sudo vereor. Cui molior populus sino. Abico diam distineo eligo gravis ideo nisl pala populus sit.

Bene iaceo ideo metuo nibh nostrud similis. At causa ea exputo nulla usitas. Caecus neque nibh nostrud. Augue eligo erat oppeto singularis ut. Autem esse exerci importunus incassum nibh scisco. Esse hos jumentum praesent ratis rusticus sit. Exputo jus paratus praemitto premo secundum velit venio verto.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Aptent feugiat lenis proprius quia sit. Augue commodo consequat lobortis saluto volutpat. Acsi gravis modo pagus secundum suscipere turpis typicus validus. Consequat conventio letalis plaga vero. Aliquip antehabeo elit ex iaceo occuro persto premo sino te. Autem elit ludus mauris odio pertineo qui.</p>
<p>Cui dolore illum neo nutus occuro sagaciter turpis veniam. Aptent defui duis elit iaceo inhibeo pagus suscipit torqueo. Amet elit et ibidem persto refero usitas velit volutpat. Jus probo quidne te. Abdo brevitas comis enim ex gilvus gravis lobortis neque ulciscor. Bene diam gemino mos sino wisi. Bene causa euismod gemino lenis sit ulciscor ullamcorper vel. Brevitas duis fere refoveo utinam.</p>
<p>Abdo augue consectetuer imputo luctus plaga. Causa commoveo gravis in natu quadrum. Abbas cogo distineo iriure ludus rusticus velit.</p>
<p>Iriure laoreet molior venio. Dolore nunc similis. Antehabeo nutus populus refero sed suscipit te. Abigo blandit dolor enim et exerci iustum praesent ulciscor. Aptent augue iusto vero. Diam esse neo utinam. Abigo accumsan duis mauris mos paratus praemitto voco.</p>
<p>Et si singularis. Commoveo consequat eligo eum persto quia quis utinam. Euismod os quadrum tation. Brevitas populus velit. Adipiscing ea huic laoreet nutus tum valetudo vero. Duis luptatum suscipit utrum ymo. Eum gemino ibidem probo turpis.</p>
<p>Amet diam ex lucidus natu olim oppeto paratus quidem volutpat. Abdo et ibidem luptatum meus populus probo sit veniam. Commoveo facilisis iusto lenis pneum. Abbas adipiscing camur causa dignissim ex hendrerit loquor suscipere. Abluo neque os praemitto refero singularis.</p>
<p>Defui elit hos iustum jugis meus oppeto pagus. Adipiscing causa neque plaga. Cogo odio pagus tamen velit wisi zelus. Defui hos molior suscipere. Conventio ea et neque. Et facilisis iaceo iusto jugis oppeto praesent similis. Adipiscing eu laoreet nobis pala premo quia valde.</p>
<p>Camur ex iaceo ideo mauris natu nobis. Commoveo eros esca interdico jugis paulatim rusticus velit. Ludus plaga similis te. Hendrerit mauris os sed suscipit ullamcorper utrum.</p>
<p>Consectetuer decet lobortis olim tamen ullamcorper. Aliquip consectetuer esca huic. Euismod gilvus illum luptatum refoveo saluto te velit veniam. Abico dignissim esse iaceo ibidem ideo iustum quidne sudo vereor. Cui molior populus sino. Abico diam distineo eligo gravis ideo nisl pala populus sit.</p>
<p>Bene iaceo ideo metuo nibh nostrud similis. At causa ea exputo nulla usitas. Caecus neque nibh nostrud. Augue eligo erat oppeto singularis ut. Autem esse exerci importunus incassum nibh scisco. Esse hos jumentum praesent ratis rusticus sit. Exputo jus paratus praemitto premo secundum velit venio verto.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 264745,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Ratis Roto',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'a8d281ac-9fbf-42a9-b96e-09fa644325d1',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b1d90605-7ad0-4fd2-a9dd-d27559f8f483',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Causa exputo feugiat humo mauris valde vero. Imputo persto valde. Eros exputo ibidem praemitto verto. Neque pecus usitas validus zelus.

Augue et lobortis nobis occuro proprius quidem sit. Appellatio camur cui facilisis ratis uxor valde velit. Elit huic interdico macto minim nibh odio refoveo valde veniam. Abdo eum ludus macto scisco sino validus. Acsi appellatio brevitas lobortis singularis. Comis quia saepius suscipere veniam vindico vulpes. Damnum facilisis ibidem ille lobortis nisl si sino.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Causa exputo feugiat humo mauris valde vero. Imputo persto valde. Eros exputo ibidem praemitto verto. Neque pecus usitas validus zelus.</p>
<p>Augue et lobortis nobis occuro proprius quidem sit. Appellatio camur cui facilisis ratis uxor valde velit. Elit huic interdico macto minim nibh odio refoveo valde veniam. Abdo eum ludus macto scisco sino validus. Acsi appellatio brevitas lobortis singularis. Comis quia saepius suscipere veniam vindico vulpes. Damnum facilisis ibidem ille lobortis nisl si sino.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 834215,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Antehabeo Causa Eros Sed Velit',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '0e165b0e-30b5-4e59-8a75-ac0eca759034',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c371a3d4-befd-4cbd-9940-d8a97faaf36a',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Dignissim elit lenis letalis pneum virtus volutpat. Abigo ibidem iriure jus mauris sed tincidunt uxor. Ex hos neque ulciscor veniam. Brevitas cui eros et exputo haero suscipere utrum vicis. At erat jugis molior neque oppeto pneum. Abico capto eros gemino nulla praemitto tamen tation utinam. Adipiscing esse minim vicis.

Capto elit gemino importunus jugis neo paratus plaga. Dignissim iustum jugis mos nisl quidem vicis. Decet imputo molior neo. Acsi consectetuer damnum inhibeo ludus validus. Capto conventio facilisis gemino ille minim voco.

Abbas aptent caecus capto consequat eros pertineo. Abluo accumsan quia. Diam modo sudo virtus. Aliquam feugiat oppeto persto quidem refero.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Dignissim elit lenis letalis pneum virtus volutpat. Abigo ibidem iriure jus mauris sed tincidunt uxor. Ex hos neque ulciscor veniam. Brevitas cui eros et exputo haero suscipere utrum vicis. At erat jugis molior neque oppeto pneum. Abico capto eros gemino nulla praemitto tamen tation utinam. Adipiscing esse minim vicis.</p>
<p>Capto elit gemino importunus jugis neo paratus plaga. Dignissim iustum jugis mos nisl quidem vicis. Decet imputo molior neo. Acsi consectetuer damnum inhibeo ludus validus. Capto conventio facilisis gemino ille minim voco.</p>
<p>Abbas aptent caecus capto consequat eros pertineo. Abluo accumsan quia. Diam modo sudo virtus. Aliquam feugiat oppeto persto quidem refero.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 624010,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Brevitas Duis Illum Velit Vero',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'da7da936-bef8-40cc-bb89-9759bfb64cb5',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'cafe3220-20ca-4287-8357-4c7c0405f75c',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Gravis importunus luptatum nisl nutus pertineo praemitto praesent rusticus. Accumsan enim eu feugiat nobis. Aliquip eum hendrerit illum jumentum probo refero tum. Aliquip caecus qui utrum. Abdo abico aliquam tation. Erat sit tego tum. Hos imputo luptatum praemitto sudo vel verto. Abico eum ibidem in macto nobis nostrud praemitto te ymo. Abigo at duis fere magna paratus voco. Comis oppeto voco ymo.

Brevitas commodo eligo facilisi gilvus magna secundum vulpes. Gemino torqueo vero. Enim ex facilisis os. Genitus humo te tincidunt ullamcorper verto. Adipiscing cui damnum natu neo olim sino. Esca macto quia sudo tego. Erat gilvus sit. Eu huic metuo obruo probo sed sudo. Conventio persto quadrum quae. Lenis oppeto validus vel. Acsi augue iriure luptatum neo nostrud wisi.

Erat hos quibus. Appellatio defui iriure mos neo tum zelus. Inhibeo luctus praesent. Causa obruo os roto. Abbas accumsan mos pneum tego. Enim interdico nutus validus vulpes. Abbas antehabeo dolore luptatum natu. Bene duis eros inhibeo jumentum validus vulputate. Eligo facilisi ideo jugis laoreet neo populus. Nutus oppeto pertineo quibus ullamcorper ut valetudo venio vero.

',
        'summary' => NULL,
        'format' => 'filtered_html',
        'safe_value' => '<p>Gravis importunus luptatum nisl nutus pertineo praemitto praesent rusticus. Accumsan enim eu feugiat nobis. Aliquip eum hendrerit illum jumentum probo refero tum. Aliquip caecus qui utrum. Abdo abico aliquam tation. Erat sit tego tum. Hos imputo luptatum praemitto sudo vel verto. Abico eum ibidem in macto nobis nostrud praemitto te ymo. Abigo at duis fere magna paratus voco. Comis oppeto voco ymo.</p>
<p>Brevitas commodo eligo facilisi gilvus magna secundum vulpes. Gemino torqueo vero. Enim ex facilisis os. Genitus humo te tincidunt ullamcorper verto. Adipiscing cui damnum natu neo olim sino. Esca macto quia sudo tego. Erat gilvus sit. Eu huic metuo obruo probo sed sudo. Conventio persto quadrum quae. Lenis oppeto validus vel. Acsi augue iriure luptatum neo nostrud wisi.</p>
<p>Erat hos quibus. Appellatio defui iriure mos neo tum zelus. Inhibeo luctus praesent. Causa obruo os roto. Abbas accumsan mos pneum tego. Enim interdico nutus validus vulpes. Abbas antehabeo dolore luptatum natu. Bene duis eros inhibeo jumentum validus vulputate. Eligo facilisi ideo jugis laoreet neo populus. Nutus oppeto pertineo quibus ullamcorper ut valetudo venio vero.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 957411,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Letalis Mauris Meus Patria Si',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '996dfefa-c97e-43f3-a863-feabee305c35',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd45cf66b-8e35-4aa6-a8e5-97ed1799e888',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abluo cui humo venio. Distineo eligo erat esca immitto lenis letalis nimis velit venio. Consectetuer enim ibidem luctus meus pecus sit.

Ad decet luptatum molior patria sagaciter vereor. Eligo hos jus roto singularis validus.

Eum iusto pecus populus praemitto quadrum vicis. Autem ea ideo iusto jugis tum. Accumsan at diam fere loquor pecus premo quidne ratis wisi.

At camur capto eu lenis loquor neque olim pertineo. Ad amet cui minim nimis qui roto typicus. Feugiat haero luctus natu nimis quis ulciscor ut. Defui eu laoreet nobis praesent suscipit ymo. Elit obruo occuro. Augue illum oppeto paulatim te. Acsi consequat distineo quis usitas zelus. Bene conventio iustum tamen torqueo. Appellatio elit lenis minim olim proprius quidem.

Erat lucidus luctus olim tincidunt ullamcorper. In iriure melior populus. Ad duis eum facilisis lenis minim pneum premo tego volutpat. Damnum defui esse gravis metuo ymo. Abdo causa saepius uxor. Aptent obruo paulatim pertineo sed usitas valetudo verto vulputate. At commoveo diam lucidus metuo nimis paulatim utinam vicis.

Elit erat facilisi plaga qui valde. Consectetuer hos natu refero saepius secundum sino tation. Ex feugiat genitus ibidem meus modo vulputate. Abluo hendrerit ibidem laoreet quia suscipit valde. Brevitas commoveo haero lucidus. Abico consectetuer duis patria populus. Appellatio comis facilisis ille nimis refero ulciscor. Aptent dolore elit sudo valde veniam virtus. Accumsan amet commoveo damnum gravis lucidus macto nostrud tamen.

Abigo adipiscing ibidem molior nostrud pecus secundum uxor vereor. Feugiat jus te. Caecus diam importunus. Antehabeo imputo natu nobis probo quidem refoveo roto tego vulputate. Brevitas defui enim hendrerit saluto sino sudo vereor voco vulpes. Comis et iustum macto neque paratus utinam vulpes ymo.

Ex iaceo jumentum pagus proprius refero scisco singularis sino te. Acsi blandit dolor ea eros loquor quadrum. Conventio ibidem patria quae sino. Loquor saepius venio. Conventio dolore eum iusto loquor nimis pala premo tincidunt typicus.

Capto magna rusticus ulciscor. Loquor minim quibus. Defui sagaciter utrum venio. Esca ille jumentum nisl quidem ut voco. Enim patria refero. Ex fere huic in mos oppeto refero tego torqueo. Commodo consequat fere olim premo venio zelus.

Consequat huic letalis modo sit typicus zelus. Abbas abigo comis distineo gemino jugis magna plaga valetudo. Aptent ille nimis qui ratis singularis sudo. Diam ex nobis vicis. Commoveo paulatim torqueo valde vulpes. Comis commoveo gilvus interdico premo utrum. Ad aliquam commodo exerci laoreet lucidus metuo nisl paulatim. Amet aptent conventio haero in probo quadrum ullamcorper usitas.

Causa iaceo illum macto oppeto roto turpis validus velit. Camur commoveo mauris vero verto voco. Aliquam ludus nobis pagus pala turpis velit. Iusto luptatum meus quibus. At humo utrum. In luptatum macto nutus suscipit verto ymo. Camur magna minim saluto volutpat. Aptent capto commoveo. Diam oppeto saepius saluto. Defui gemino gilvus humo inhibeo meus odio praesent tum ulciscor.

Eum imputo letalis. Distineo enim melior natu singularis suscipere validus. Caecus hos natu saepius sino valetudo vero.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Abluo cui humo venio. Distineo eligo erat esca immitto lenis letalis nimis velit venio. Consectetuer enim ibidem luctus meus pecus sit.</p>
<p>Ad decet luptatum molior patria sagaciter vereor. Eligo hos jus roto singularis validus.</p>
<p>Eum iusto pecus populus praemitto quadrum vicis. Autem ea ideo iusto jugis tum. Accumsan at diam fere loquor pecus premo quidne ratis wisi.</p>
<p>At camur capto eu lenis loquor neque olim pertineo. Ad amet cui minim nimis qui roto typicus. Feugiat haero luctus natu nimis quis ulciscor ut. Defui eu laoreet nobis praesent suscipit ymo. Elit obruo occuro. Augue illum oppeto paulatim te. Acsi consequat distineo quis usitas zelus. Bene conventio iustum tamen torqueo. Appellatio elit lenis minim olim proprius quidem.</p>
<p>Erat lucidus luctus olim tincidunt ullamcorper. In iriure melior populus. Ad duis eum facilisis lenis minim pneum premo tego volutpat. Damnum defui esse gravis metuo ymo. Abdo causa saepius uxor. Aptent obruo paulatim pertineo sed usitas valetudo verto vulputate. At commoveo diam lucidus metuo nimis paulatim utinam vicis.</p>
<p>Elit erat facilisi plaga qui valde. Consectetuer hos natu refero saepius secundum sino tation. Ex feugiat genitus ibidem meus modo vulputate. Abluo hendrerit ibidem laoreet quia suscipit valde. Brevitas commoveo haero lucidus. Abico consectetuer duis patria populus. Appellatio comis facilisis ille nimis refero ulciscor. Aptent dolore elit sudo valde veniam virtus. Accumsan amet commoveo damnum gravis lucidus macto nostrud tamen.</p>
<p>Abigo adipiscing ibidem molior nostrud pecus secundum uxor vereor. Feugiat jus te. Caecus diam importunus. Antehabeo imputo natu nobis probo quidem refoveo roto tego vulputate. Brevitas defui enim hendrerit saluto sino sudo vereor voco vulpes. Comis et iustum macto neque paratus utinam vulpes ymo.</p>
<p>Ex iaceo jumentum pagus proprius refero scisco singularis sino te. Acsi blandit dolor ea eros loquor quadrum. Conventio ibidem patria quae sino. Loquor saepius venio. Conventio dolore eum iusto loquor nimis pala premo tincidunt typicus.</p>
<p>Capto magna rusticus ulciscor. Loquor minim quibus. Defui sagaciter utrum venio. Esca ille jumentum nisl quidem ut voco. Enim patria refero. Ex fere huic in mos oppeto refero tego torqueo. Commodo consequat fere olim premo venio zelus.</p>
<p>Consequat huic letalis modo sit typicus zelus. Abbas abigo comis distineo gemino jugis magna plaga valetudo. Aptent ille nimis qui ratis singularis sudo. Diam ex nobis vicis. Commoveo paulatim torqueo valde vulpes. Comis commoveo gilvus interdico premo utrum. Ad aliquam commodo exerci laoreet lucidus metuo nisl paulatim. Amet aptent conventio haero in probo quadrum ullamcorper usitas.</p>
<p>Causa iaceo illum macto oppeto roto turpis validus velit. Camur commoveo mauris vero verto voco. Aliquam ludus nobis pagus pala turpis velit. Iusto luptatum meus quibus. At humo utrum. In luptatum macto nutus suscipit verto ymo. Camur magna minim saluto volutpat. Aptent capto commoveo. Diam oppeto saepius saluto. Defui gemino gilvus humo inhibeo meus odio praesent tum ulciscor.</p>
<p>Eum imputo letalis. Distineo enim melior natu singularis suscipere validus. Caecus hos natu saepius sino valetudo vero.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 315856,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Importunus Modo Quae Verto Vicis Wisi',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'ba717a14-33d7-4995-973e-4e78677c0978',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f2e9c8c6-3eab-4b7a-968e-e8155e2d4f1c',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Consequat erat fere macto metuo pertineo pneum rusticus utrum. Appellatio bene damnum dolore odio quidem sagaciter tego utinam vulpes.

Jumentum quibus quidne tum vel. Amet commodo commoveo consequat fere incassum laoreet pala ut valde. Jugis luptatum quidem voco. Aliquam hendrerit mauris nulla pertineo quidem saluto.

Abigo adipiscing ille in premo veniam. Amet lenis probo ulciscor. Abico aliquam cui damnum exerci valde validus. Ex illum nostrud olim pecus. Comis eu gilvus interdico rusticus zelus. Decet eu interdico paratus sit uxor.

Haero qui typicus. At bene capto exerci melior nimis. Brevitas exerci illum jus paulatim pertineo torqueo. Iusto jus letalis odio sudo. Abigo aliquam consectetuer oppeto refero si vulpes. Abigo brevitas commoveo in roto. Blandit commoveo cui facilisi ideo refero utrum validus veniam.

Defui eligo feugiat illum letalis luctus usitas veniam verto. Comis erat gemino nobis roto saluto singularis tego utrum vel.

Conventio iriure pagus pala quadrum quae ratis singularis tation torqueo. Ideo loquor premo velit. Brevitas dolor euismod jus ludus quidne sagaciter saluto tego verto. Nibh suscipere venio. Meus nunc occuro. Esca occuro pagus pala qui torqueo tum vicis. Aptent bene commoveo metuo typicus.

',
        'summary' => NULL,
        'format' => 'full_html',
        'safe_value' => '<p>Consequat erat fere macto metuo pertineo pneum rusticus utrum. Appellatio bene damnum dolore odio quidem sagaciter tego utinam vulpes.</p>
<p>Jumentum quibus quidne tum vel. Amet commodo commoveo consequat fere incassum laoreet pala ut valde. Jugis luptatum quidem voco. Aliquam hendrerit mauris nulla pertineo quidem saluto.</p>
<p>Abigo adipiscing ille in premo veniam. Amet lenis probo ulciscor. Abico aliquam cui damnum exerci valde validus. Ex illum nostrud olim pecus. Comis eu gilvus interdico rusticus zelus. Decet eu interdico paratus sit uxor.</p>
<p>Haero qui typicus. At bene capto exerci melior nimis. Brevitas exerci illum jus paulatim pertineo torqueo. Iusto jus letalis odio sudo. Abigo aliquam consectetuer oppeto refero si vulpes. Abigo brevitas commoveo in roto. Blandit commoveo cui facilisi ideo refero utrum validus veniam.</p>
<p>Defui eligo feugiat illum letalis luctus usitas veniam verto. Comis erat gemino nobis roto saluto singularis tego utrum vel.</p>
<p>Conventio iriure pagus pala quadrum quae ratis singularis tation torqueo. Ideo loquor premo velit. Brevitas dolor euismod jus ludus quidne sagaciter saluto tego verto. Nibh suscipere venio. Meus nunc occuro. Esca occuro pagus pala qui torqueo tum vicis. Aptent bene commoveo metuo typicus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 451873,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-30 05:43:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Consequat Iustum Nobis Valde',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '460d96a1-2ff9-4740-9222-32c2973125bd',
  'type' => 'product',
  'language' => 'und',
  'created' => 1427694223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f513db91-b477-4c01-afec-38eec99962cd',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Aliquip blandit dolor luctus meus pertineo singularis valde velit vindico. Aliquam cogo facilisis letalis pagus premo. Capto eros obruo probo. Accumsan acsi amet lenis proprius qui quidne roto utinam. Capto dolor ideo loquor lucidus persto pertineo roto torqueo vel. Acsi amet autem bene ea minim pneum ullamcorper vindico zelus. Commoveo gravis ibidem letalis mos tamen.

Aliquam amet appellatio diam eros iriure neo ulciscor. Abico bene caecus gravis hendrerit luptatum nulla quibus volutpat. Damnum molior proprius quia si suscipere. Conventio euismod saluto. Ad adipiscing lobortis molior plaga quia sudo. Causa jus loquor luptatum pagus persto plaga saepius.

Abluo ad facilisis genitus importunus lucidus pecus saluto. Antehabeo capto damnum exerci jumentum pertineo ullamcorper.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Aliquip blandit dolor luctus meus pertineo singularis valde velit vindico. Aliquam cogo facilisis letalis pagus premo. Capto eros obruo probo. Accumsan acsi amet lenis proprius qui quidne roto utinam. Capto dolor ideo loquor lucidus persto pertineo roto torqueo vel. Acsi amet autem bene ea minim pneum ullamcorper vindico zelus. Commoveo gravis ibidem letalis mos tamen.</p>
<p>Aliquam amet appellatio diam eros iriure neo ulciscor. Abico bene caecus gravis hendrerit luptatum nulla quibus volutpat. Damnum molior proprius quia si suscipere. Conventio euismod saluto. Ad adipiscing lobortis molior plaga quia sudo. Causa jus loquor luptatum pagus persto plaga saepius.</p>
<p>Abluo ad facilisis genitus importunus lucidus pecus saluto. Antehabeo capto damnum exerci jumentum pertineo ullamcorper.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 73298,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-30 05:43:43 +0000',
);
  return $nodes;
}
