<?php
/**
 * @file
 * f_ct_catalog.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function f_ct_catalog_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Capto Praesent',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c9af66a6-fbd5-462e-887a-f351a445bf8f',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426722255,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0d30b06b-5ce0-431b-a269-162be83d0544',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Cogo distineo eros esse laoreet nisl sit utrum. Esse lobortis paratus tego. Aptent cui distineo iriure luctus quidne sudo tego vel vulputate. Erat gravis meus nutus sino. Esse paratus venio. Decet dolor erat eum exerci nulla nunc praesent quis torqueo. Accumsan eligo qui. Appellatio gilvus ille iusto loquor modo praesent uxor.

Accumsan erat euismod quidne. Abigo defui probo. Commodo enim euismod ibidem imputo quidne. Aliquam autem commoveo esse letalis ratis scisco te vicis. Capto tamen valetudo. Diam pertineo plaga vicis. Acsi antehabeo et eu te vulputate. Euismod eum molior sino. Aliquam erat ex gemino lucidus meus minim neque tincidunt typicus.

Conventio elit feugiat genitus. Bene dolus exputo lucidus ludus macto occuro vicis. Comis iriure metuo utinam.

Aliquam consectetuer gilvus inhibeo nutus praemitto uxor. Antehabeo exputo iusto ludus nulla roto vereor zelus. Autem eu euismod nulla valetudo vindico. Elit ille natu vero. Aptent humo roto valetudo. Damnum dolor nimis pecus refero. Aliquam appellatio blandit dolus eligo hendrerit immitto jus validus vereor.

Adipiscing consectetuer damnum pagus volutpat. Gilvus immitto natu populus saluto typicus zelus. Conventio illum probo tamen venio.

Accumsan adipiscing decet in modo obruo roto sed torqueo. Aliquip commodo consequat ea erat neo praesent proprius. Dignissim elit persto quae. Aliquam defui macto nutus secundum. Aptent esse exerci ideo nisl pagus persto quadrum quidem. Aliquip defui ideo imputo iriure lucidus tamen torqueo. Blandit duis ibidem magna tamen typicus ullamcorper.

Decet defui ea ex iustum natu obruo saepius utinam wisi. Decet importunus lenis paulatim tamen. Amet blandit caecus lucidus metuo olim ut voco vulputate wisi. Abdo damnum mos valetudo verto. Eu letalis refoveo tego verto. Diam et exputo immitto lobortis molior nibh nunc refero ut. Feugiat ille magna molior olim.

Acsi autem obruo pala premo saluto voco. Distineo humo lucidus neque nobis os probo quidne secundum volutpat. Ad pagus probo. Eligo eum nunc saepius suscipere tego. Defui dolus esca esse mos nibh secundum tego. Abdo adipiscing enim ex ulciscor.

Dignissim genitus sino validus wisi ymo. Abbas consequat et facilisi feugiat quia similis valetudo. Abigo iaceo nimis saluto. Et ex incassum obruo quis scisco singularis utrum. Comis gilvus loquor meus patria refero sudo. Abluo camur elit enim erat gilvus jugis os sagaciter. Abluo laoreet pertineo premo quidem si tamen valetudo.

Aptent autem ibidem interdico jus laoreet mos os plaga. Commoveo dignissim jugis. Dolus luptatum scisco valetudo vulputate. Abigo et gravis illum sit zelus. Augue caecus cui dolus enim ideo letalis vereor. Camur lobortis nunc. Genitus haero iriure quibus te turpis. Abluo dignissim distineo eu importunus iriure magna valetudo validus. Humo quidem similis suscipere usitas vulpes. Cui esca haero hendrerit ille nisl suscipit.

Letalis neo si veniam. Ex hendrerit nulla populus sit ymo. Aliquam camur lenis sudo vel virtus. Abigo ideo iriure praemitto refero. Ad conventio damnum importunus quia. Antehabeo lenis sino. Enim patria roto saluto singularis ullamcorper ut validus vindico volutpat.

Decet ex oppeto ymo. Abigo adipiscing ea jus metuo neque quia rusticus ullamcorper.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Cogo distineo eros esse laoreet nisl sit utrum. Esse lobortis paratus tego. Aptent cui distineo iriure luctus quidne sudo tego vel vulputate. Erat gravis meus nutus sino. Esse paratus venio. Decet dolor erat eum exerci nulla nunc praesent quis torqueo. Accumsan eligo qui. Appellatio gilvus ille iusto loquor modo praesent uxor.</p>
<p>Accumsan erat euismod quidne. Abigo defui probo. Commodo enim euismod ibidem imputo quidne. Aliquam autem commoveo esse letalis ratis scisco te vicis. Capto tamen valetudo. Diam pertineo plaga vicis. Acsi antehabeo et eu te vulputate. Euismod eum molior sino. Aliquam erat ex gemino lucidus meus minim neque tincidunt typicus.</p>
<p>Conventio elit feugiat genitus. Bene dolus exputo lucidus ludus macto occuro vicis. Comis iriure metuo utinam.</p>
<p>Aliquam consectetuer gilvus inhibeo nutus praemitto uxor. Antehabeo exputo iusto ludus nulla roto vereor zelus. Autem eu euismod nulla valetudo vindico. Elit ille natu vero. Aptent humo roto valetudo. Damnum dolor nimis pecus refero. Aliquam appellatio blandit dolus eligo hendrerit immitto jus validus vereor.</p>
<p>Adipiscing consectetuer damnum pagus volutpat. Gilvus immitto natu populus saluto typicus zelus. Conventio illum probo tamen venio.</p>
<p>Accumsan adipiscing decet in modo obruo roto sed torqueo. Aliquip commodo consequat ea erat neo praesent proprius. Dignissim elit persto quae. Aliquam defui macto nutus secundum. Aptent esse exerci ideo nisl pagus persto quadrum quidem. Aliquip defui ideo imputo iriure lucidus tamen torqueo. Blandit duis ibidem magna tamen typicus ullamcorper.</p>
<p>Decet defui ea ex iustum natu obruo saepius utinam wisi. Decet importunus lenis paulatim tamen. Amet blandit caecus lucidus metuo olim ut voco vulputate wisi. Abdo damnum mos valetudo verto. Eu letalis refoveo tego verto. Diam et exputo immitto lobortis molior nibh nunc refero ut. Feugiat ille magna molior olim.</p>
<p>Acsi autem obruo pala premo saluto voco. Distineo humo lucidus neque nobis os probo quidne secundum volutpat. Ad pagus probo. Eligo eum nunc saepius suscipere tego. Defui dolus esca esse mos nibh secundum tego. Abdo adipiscing enim ex ulciscor.</p>
<p>Dignissim genitus sino validus wisi ymo. Abbas consequat et facilisi feugiat quia similis valetudo. Abigo iaceo nimis saluto. Et ex incassum obruo quis scisco singularis utrum. Comis gilvus loquor meus patria refero sudo. Abluo camur elit enim erat gilvus jugis os sagaciter. Abluo laoreet pertineo premo quidem si tamen valetudo.</p>
<p>Aptent autem ibidem interdico jus laoreet mos os plaga. Commoveo dignissim jugis. Dolus luptatum scisco valetudo vulputate. Abigo et gravis illum sit zelus. Augue caecus cui dolus enim ideo letalis vereor. Camur lobortis nunc. Genitus haero iriure quibus te turpis. Abluo dignissim distineo eu importunus iriure magna valetudo validus. Humo quidem similis suscipere usitas vulpes. Cui esca haero hendrerit ille nisl suscipit.</p>
<p>Letalis neo si veniam. Ex hendrerit nulla populus sit ymo. Aliquam camur lenis sudo vel virtus. Abigo ideo iriure praemitto refero. Ad conventio damnum importunus quia. Antehabeo lenis sino. Enim patria roto saluto singularis ullamcorper ut validus vindico volutpat.</p>
<p>Decet ex oppeto ymo. Abigo adipiscing ea jus metuo neque quia rusticus ullamcorper.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 758158,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 05:44:15 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Camur Pala Torqueo Vulputate',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '9534de48-7f09-4723-b6e0-c2f0e4742487',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426517234,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '16034d82-c1cd-4f55-81b2-c55b708c15d5',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Jumentum molior plaga sed. Aliquam capto exerci iaceo in meus nostrud pala vel vulpes. Blandit feugiat genitus iustum macto suscipere ulciscor ullamcorper veniam. Aliquam caecus letalis neo pecus plaga turpis ut veniam.

Aliquip commodo commoveo gilvus importunus in nutus refero venio. Blandit cogo jus metuo pagus tamen. Aliquip capto eu facilisis interdico luptatum quis si tincidunt.

Accumsan causa haero importunus mauris os utrum valetudo. Abico facilisi immitto imputo odio. Ad at blandit consectetuer ea enim euismod nisl refero. Abico at dolore immitto iriure iusto lucidus populus similis utrum. Aliquam camur euismod importunus pagus pneum. Iustum loquor saepius volutpat. Blandit commoveo euismod neque nobis plaga. Abdo augue damnum dolore illum neque pertineo tamen turpis vulputate.

Facilisis feugiat nulla patria vicis. Elit facilisis suscipit velit. Eu ibidem jugis nibh rusticus tego validus verto. Jumentum loquor nunc refoveo similis. Dignissim eum feugiat gravis humo velit. Cui dolore gilvus inhibeo luctus populus quidem vero. Abico bene eros fere inhibeo odio tation utrum vel. Abbas ad dolore erat eum gemino pala premo qui sino.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Jumentum molior plaga sed. Aliquam capto exerci iaceo in meus nostrud pala vel vulpes. Blandit feugiat genitus iustum macto suscipere ulciscor ullamcorper veniam. Aliquam caecus letalis neo pecus plaga turpis ut veniam.</p>
<p>Aliquip commodo commoveo gilvus importunus in nutus refero venio. Blandit cogo jus metuo pagus tamen. Aliquip capto eu facilisis interdico luptatum quis si tincidunt.</p>
<p>Accumsan causa haero importunus mauris os utrum valetudo. Abico facilisi immitto imputo odio. Ad at blandit consectetuer ea enim euismod nisl refero. Abico at dolore immitto iriure iusto lucidus populus similis utrum. Aliquam camur euismod importunus pagus pneum. Iustum loquor saepius volutpat. Blandit commoveo euismod neque nobis plaga. Abdo augue damnum dolore illum neque pertineo tamen turpis vulputate.</p>
<p>Facilisis feugiat nulla patria vicis. Elit facilisis suscipit velit. Eu ibidem jugis nibh rusticus tego validus verto. Jumentum loquor nunc refoveo similis. Dignissim eum feugiat gravis humo velit. Cui dolore gilvus inhibeo luctus populus quidem vero. Abico bene eros fere inhibeo odio tation utrum vel. Abbas ad dolore erat eum gemino pala premo qui sino.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 873421,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-16 20:47:14 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Appellatio Gilvus Voco',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '6bdbae9c-0b31-4ade-b6e8-239e956d4a9d',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426751980,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '16a31b74-0164-4f4b-b321-13b1d766ff19',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abico cogo damnum iriure jumentum neo torqueo valetudo. Esse et haero ibidem similis tation wisi zelus. Elit gravis iusto lenis modo neo quidne secundum tation. Brevitas commoveo damnum letalis neque quis te velit voco ymo. Abigo antehabeo feugiat iaceo imputo obruo tum uxor. Capto laoreet si uxor. Accumsan conventio jus luptatum metuo pala quibus. At duis gemino iustum minim oppeto.

Aliquam nunc paulatim volutpat. Causa elit iusto pertineo typicus. Abico capto illum iusto ludus qui secundum sit ulciscor. Ideo nisl saepius. At brevitas commodo consequat eum immitto nobis nostrud roto. Causa feugiat pagus probo si tego validus. Cui luctus nibh secundum. Consequat ille utinam. Aliquip camur consectetuer obruo rusticus vero. Consectetuer imputo natu velit wisi. Ille letalis refoveo.

Cogo ideo iustum lenis ludus praemitto probo ratis saepius. Abbas odio refoveo. Neo paratus ratis vereor vulputate. Conventio illum lucidus modo virtus. Abigo gravis mos sudo tum. Abdo dolor incassum inhibeo jugis ludus nimis similis venio. Comis hos nobis. Dolus in sino vulpes. Conventio molior mos nobis tation.

Exputo iusto meus obruo proprius rusticus tincidunt. Ad diam metuo. Bene distineo eum nulla olim proprius quae vulpes. Adipiscing aptent odio refero.

Esse huic lobortis vereor vulputate. Abigo consectetuer nobis. Commodo te verto. Accumsan acsi proprius. Acsi adipiscing eligo jugis magna mauris molior pecus sit vel.

Immitto modo neo occuro ut volutpat. Acsi eros macto minim natu pertineo refero valetudo vel vicis. At augue decet diam ex mauris quadrum tego torqueo turpis. Illum ludus pertineo quidem. Blandit enim lucidus. Abico abluo acsi aliquam at exputo illum nutus praesent tum. Cogo diam immitto patria tincidunt. Appellatio jugis populus praemitto turpis. Capto comis decet defui esse in iusto nibh quibus te.

Abigo aptent duis eligo euismod fere. Commodo consequat facilisis. Acsi adipiscing erat loquor metuo. Dolore lucidus si tego. Facilisis fere obruo pagus similis torqueo utinam validus. Causa duis lobortis macto odio quae venio ymo. Adipiscing amet aptent exputo illum ulciscor vindico wisi. Cogo exputo iriure metuo quidne refero. Abigo accumsan blandit. Caecus commoveo ludus mauris nunc sit valetudo vicis.

Abbas distineo duis neo quae quidne wisi. Abigo ad quidem scisco uxor vindico.

Adipiscing bene duis hendrerit nobis nulla saepius tation valde veniam. Camur imputo minim natu sino utrum. Abigo accumsan brevitas consectetuer luctus scisco. Iriure luptatum neo pneum praesent velit. Aliquip cogo dolus erat letalis nimis refoveo saepius torqueo vereor. Appellatio capto distineo eros huic ludus melior velit. Bene ea facilisi humo jus nobis populus praemitto saluto valetudo.

Accumsan dolus eu minim refero sed verto vulputate. Capto feugiat praemitto ratis roto. Abbas comis inhibeo iriure os plaga suscipere suscipit ut vicis. Amet lucidus premo utrum ymo. At causa conventio damnum huic ideo luctus nulla utinam volutpat. Causa esse gilvus mos. Augue commodo consequat iusto quibus quidne.

Augue causa comis enim ille importunus ludus meus pagus suscipit. Abdo esse praesent vulpes. Inhibeo luptatum nisl velit. Bene iaceo pecus populus quadrum rusticus singularis valetudo vero voco. Gilvus obruo pala plaga refero veniam. Autem defui inhibeo nobis pala pecus quis refoveo sit.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abico cogo damnum iriure jumentum neo torqueo valetudo. Esse et haero ibidem similis tation wisi zelus. Elit gravis iusto lenis modo neo quidne secundum tation. Brevitas commoveo damnum letalis neque quis te velit voco ymo. Abigo antehabeo feugiat iaceo imputo obruo tum uxor. Capto laoreet si uxor. Accumsan conventio jus luptatum metuo pala quibus. At duis gemino iustum minim oppeto.</p>
<p>Aliquam nunc paulatim volutpat. Causa elit iusto pertineo typicus. Abico capto illum iusto ludus qui secundum sit ulciscor. Ideo nisl saepius. At brevitas commodo consequat eum immitto nobis nostrud roto. Causa feugiat pagus probo si tego validus. Cui luctus nibh secundum. Consequat ille utinam. Aliquip camur consectetuer obruo rusticus vero. Consectetuer imputo natu velit wisi. Ille letalis refoveo.</p>
<p>Cogo ideo iustum lenis ludus praemitto probo ratis saepius. Abbas odio refoveo. Neo paratus ratis vereor vulputate. Conventio illum lucidus modo virtus. Abigo gravis mos sudo tum. Abdo dolor incassum inhibeo jugis ludus nimis similis venio. Comis hos nobis. Dolus in sino vulpes. Conventio molior mos nobis tation.</p>
<p>Exputo iusto meus obruo proprius rusticus tincidunt. Ad diam metuo. Bene distineo eum nulla olim proprius quae vulpes. Adipiscing aptent odio refero.</p>
<p>Esse huic lobortis vereor vulputate. Abigo consectetuer nobis. Commodo te verto. Accumsan acsi proprius. Acsi adipiscing eligo jugis magna mauris molior pecus sit vel.</p>
<p>Immitto modo neo occuro ut volutpat. Acsi eros macto minim natu pertineo refero valetudo vel vicis. At augue decet diam ex mauris quadrum tego torqueo turpis. Illum ludus pertineo quidem. Blandit enim lucidus. Abico abluo acsi aliquam at exputo illum nutus praesent tum. Cogo diam immitto patria tincidunt. Appellatio jugis populus praemitto turpis. Capto comis decet defui esse in iusto nibh quibus te.</p>
<p>Abigo aptent duis eligo euismod fere. Commodo consequat facilisis. Acsi adipiscing erat loquor metuo. Dolore lucidus si tego. Facilisis fere obruo pagus similis torqueo utinam validus. Causa duis lobortis macto odio quae venio ymo. Adipiscing amet aptent exputo illum ulciscor vindico wisi. Cogo exputo iriure metuo quidne refero. Abigo accumsan blandit. Caecus commoveo ludus mauris nunc sit valetudo vicis.</p>
<p>Abbas distineo duis neo quae quidne wisi. Abigo ad quidem scisco uxor vindico.</p>
<p>Adipiscing bene duis hendrerit nobis nulla saepius tation valde veniam. Camur imputo minim natu sino utrum. Abigo accumsan brevitas consectetuer luctus scisco. Iriure luptatum neo pneum praesent velit. Aliquip cogo dolus erat letalis nimis refoveo saepius torqueo vereor. Appellatio capto distineo eros huic ludus melior velit. Bene ea facilisi humo jus nobis populus praemitto saluto valetudo.</p>
<p>Accumsan dolus eu minim refero sed verto vulputate. Capto feugiat praemitto ratis roto. Abbas comis inhibeo iriure os plaga suscipere suscipit ut vicis. Amet lucidus premo utrum ymo. At causa conventio damnum huic ideo luctus nulla utinam volutpat. Causa esse gilvus mos. Augue commodo consequat iusto quibus quidne.</p>
<p>Augue causa comis enim ille importunus ludus meus pagus suscipit. Abdo esse praesent vulpes. Inhibeo luptatum nisl velit. Bene iaceo pecus populus quadrum rusticus singularis valetudo vero voco. Gilvus obruo pala plaga refero veniam. Autem defui inhibeo nobis pala pecus quis refoveo sit.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 359061,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-19 13:59:40 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'At',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '478c8167-122f-4f14-aa87-a5f06d1b145f',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426257280,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '18ef35fb-1a74-4e86-a685-8ab7c0514159',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abico aliquam eligo loquor ludus olim oppeto patria valetudo vulputate. Appellatio bene defui humo iaceo jus nutus torqueo valetudo. Consectetuer distineo euismod hos nisl nunc pagus premo velit venio. Damnum jumentum mauris paratus roto si singularis. Comis conventio hos obruo saepius tation vero. Ad erat sed. Accumsan camur enim exerci humo pala volutpat. Abigo importunus quidne sed.

Abluo blandit haero iriure molior premo tincidunt. Gemino jumentum lenis neque nutus similis ullamcorper ut. Hendrerit natu saepius. Esca hendrerit melior molior nunc probo quis saepius. Commodo ille veniam vulpes. Consectetuer defui luctus. Aliquip antehabeo blandit inhibeo laoreet obruo quadrum tation venio. Defui dolor dolore gilvus illum imputo os tum usitas. Ea exputo gemino interdico laoreet letalis mauris pecus populus quis.

Caecus diam elit esse euismod facilisi persto rusticus si valetudo. Exputo inhibeo odio patria praemitto uxor vero. Damnum gemino verto. Distineo eligo esca oppeto os patria quidem singularis. Aliquip camur magna oppeto patria tum.

Esse in utrum. Et feugiat hendrerit humo iaceo. Iaceo iriure jumentum magna metuo paulatim pecus turpis. Abigo appellatio dolor esse interdico iriure obruo tum ullamcorper. Dolus duis eu letalis macto neo pecus premo verto voco. Bene exerci ideo in letalis nimis sed. Letalis occuro veniam. Fere gravis incassum luctus modo pagus plaga praemitto si.

Eu facilisis ludus luptatum odio si validus vero. Neo premo ulciscor voco. Ea iriure lenis persto praemitto suscipere tincidunt ulciscor ullamcorper uxor. Cogo facilisis ideo plaga quis tego. Luptatum modo turpis. Abbas haero iustum proprius similis torqueo verto vindico vulpes. Blandit ideo immitto lucidus molior nibh nisl os secundum si. Aptent diam duis facilisis macto praemitto scisco tamen.

Dignissim ea magna refero. Abluo pagus rusticus sino turpis. Abbas aliquam aptent hendrerit inhibeo molior pertineo quae verto. Neo occuro quia tum zelus.

Enim euismod facilisi immitto meus neo odio tincidunt vulputate. Immitto pala plaga uxor. Esse euismod mauris valetudo. Abluo aliquam eligo hos in macto metuo neo voco. Hos praemitto quis singularis. Distineo neque os pertineo ulciscor. Dignissim gravis iriure molior natu persto quae roto typicus valetudo. Conventio exerci genitus immitto qui.

Abdo letalis mauris sit uxor. Acsi autem blandit gilvus pneum probo refoveo velit. Caecus eligo refoveo ut utinam verto. Comis duis eligo premo suscipit wisi. Exputo nisl saepius secundum validus veniam volutpat. Feugiat magna nobis. Abico exputo modo neo neque quibus ut velit. Distineo enim euismod interdico iriure lenis nobis qui sino vulpes.

Abico blandit conventio os. Antehabeo loquor minim. Erat exputo incassum loquor lucidus neo olim venio. Caecus consectetuer ex meus patria tation. Consequat distineo nostrud. Adipiscing aliquam capto quadrum. Abbas amet elit genitus letalis lucidus roto suscipit tincidunt ulciscor. Acsi ad adipiscing distineo suscipere.

Abluo bene diam eros euismod facilisis neo nutus. Causa esca ideo ille nisl pneum quis torqueo volutpat. Dolor eligo eum praesent ratis secundum torqueo uxor vulpes. Camur comis decet luctus qui. Abigo causa ideo occuro premo probo tego typicus wisi. Eligo haero veniam. At dolus ea elit. Defui te tum.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abico aliquam eligo loquor ludus olim oppeto patria valetudo vulputate. Appellatio bene defui humo iaceo jus nutus torqueo valetudo. Consectetuer distineo euismod hos nisl nunc pagus premo velit venio. Damnum jumentum mauris paratus roto si singularis. Comis conventio hos obruo saepius tation vero. Ad erat sed. Accumsan camur enim exerci humo pala volutpat. Abigo importunus quidne sed.</p>
<p>Abluo blandit haero iriure molior premo tincidunt. Gemino jumentum lenis neque nutus similis ullamcorper ut. Hendrerit natu saepius. Esca hendrerit melior molior nunc probo quis saepius. Commodo ille veniam vulpes. Consectetuer defui luctus. Aliquip antehabeo blandit inhibeo laoreet obruo quadrum tation venio. Defui dolor dolore gilvus illum imputo os tum usitas. Ea exputo gemino interdico laoreet letalis mauris pecus populus quis.</p>
<p>Caecus diam elit esse euismod facilisi persto rusticus si valetudo. Exputo inhibeo odio patria praemitto uxor vero. Damnum gemino verto. Distineo eligo esca oppeto os patria quidem singularis. Aliquip camur magna oppeto patria tum.</p>
<p>Esse in utrum. Et feugiat hendrerit humo iaceo. Iaceo iriure jumentum magna metuo paulatim pecus turpis. Abigo appellatio dolor esse interdico iriure obruo tum ullamcorper. Dolus duis eu letalis macto neo pecus premo verto voco. Bene exerci ideo in letalis nimis sed. Letalis occuro veniam. Fere gravis incassum luctus modo pagus plaga praemitto si.</p>
<p>Eu facilisis ludus luptatum odio si validus vero. Neo premo ulciscor voco. Ea iriure lenis persto praemitto suscipere tincidunt ulciscor ullamcorper uxor. Cogo facilisis ideo plaga quis tego. Luptatum modo turpis. Abbas haero iustum proprius similis torqueo verto vindico vulpes. Blandit ideo immitto lucidus molior nibh nisl os secundum si. Aptent diam duis facilisis macto praemitto scisco tamen.</p>
<p>Dignissim ea magna refero. Abluo pagus rusticus sino turpis. Abbas aliquam aptent hendrerit inhibeo molior pertineo quae verto. Neo occuro quia tum zelus.</p>
<p>Enim euismod facilisi immitto meus neo odio tincidunt vulputate. Immitto pala plaga uxor. Esse euismod mauris valetudo. Abluo aliquam eligo hos in macto metuo neo voco. Hos praemitto quis singularis. Distineo neque os pertineo ulciscor. Dignissim gravis iriure molior natu persto quae roto typicus valetudo. Conventio exerci genitus immitto qui.</p>
<p>Abdo letalis mauris sit uxor. Acsi autem blandit gilvus pneum probo refoveo velit. Caecus eligo refoveo ut utinam verto. Comis duis eligo premo suscipit wisi. Exputo nisl saepius secundum validus veniam volutpat. Feugiat magna nobis. Abico exputo modo neo neque quibus ut velit. Distineo enim euismod interdico iriure lenis nobis qui sino vulpes.</p>
<p>Abico blandit conventio os. Antehabeo loquor minim. Erat exputo incassum loquor lucidus neo olim venio. Caecus consectetuer ex meus patria tation. Consequat distineo nostrud. Adipiscing aliquam capto quadrum. Abbas amet elit genitus letalis lucidus roto suscipit tincidunt ulciscor. Acsi ad adipiscing distineo suscipere.</p>
<p>Abluo bene diam eros euismod facilisis neo nutus. Causa esca ideo ille nisl pneum quis torqueo volutpat. Dolor eligo eum praesent ratis secundum torqueo uxor vulpes. Camur comis decet luctus qui. Abigo causa ideo occuro premo probo tego typicus wisi. Eligo haero veniam. At dolus ea elit. Defui te tum.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 530448,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-13 20:34:40 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Letalis Utrum',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '61b83cc3-fec6-48b3-b3ae-17a122ac7ff6',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426371480,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '24a5df28-1e43-487f-82f4-8f4cae754f4b',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo dolus nutus paratus. Enim melior paratus praesent quis sudo. Abico appellatio mauris minim. Abdo et feugiat jumentum paratus probo qui sagaciter utinam ymo.

Facilisi incassum oppeto refoveo sagaciter. Blandit obruo tation vel. Cogo euismod facilisis illum luptatum occuro paratus quae. Augue comis ille velit. Dolor esse iriure metuo occuro premo turpis utinam velit. Amet augue cogo letalis pecus torqueo. Ad exputo luctus meus neque ulciscor venio. Dignissim exputo gravis hos lobortis populus sino tum utinam.

Aliquip distineo hendrerit loquor lucidus. Dolore melior nisl nunc tincidunt. Facilisi iustum tincidunt. Caecus exerci facilisis humo inhibeo iustum odio pneum roto typicus. Autem commodo humo iriure obruo scisco tamen. At hendrerit lucidus ludus pecus tamen torqueo valde. Cui incassum mos neo nisl populus. Ex gilvus natu nostrud ratis venio. Bene dolor feugiat importunus luptatum paratus quidne.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo dolus nutus paratus. Enim melior paratus praesent quis sudo. Abico appellatio mauris minim. Abdo et feugiat jumentum paratus probo qui sagaciter utinam ymo.</p>
<p>Facilisi incassum oppeto refoveo sagaciter. Blandit obruo tation vel. Cogo euismod facilisis illum luptatum occuro paratus quae. Augue comis ille velit. Dolor esse iriure metuo occuro premo turpis utinam velit. Amet augue cogo letalis pecus torqueo. Ad exputo luctus meus neque ulciscor venio. Dignissim exputo gravis hos lobortis populus sino tum utinam.</p>
<p>Aliquip distineo hendrerit loquor lucidus. Dolore melior nisl nunc tincidunt. Facilisi iustum tincidunt. Caecus exerci facilisis humo inhibeo iustum odio pneum roto typicus. Autem commodo humo iriure obruo scisco tamen. At hendrerit lucidus ludus pecus tamen torqueo valde. Cui incassum mos neo nisl populus. Ex gilvus natu nostrud ratis venio. Bene dolor feugiat importunus luptatum paratus quidne.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 252565,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-15 04:18:00 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Ex Nibh',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '56cf2401-ee51-4e66-a737-fdcb2498b9af',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426714209,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '24b9cde1-e7c4-43f1-b6fd-5934e2f2e872',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Nutus refoveo sagaciter. Exputo facilisi odio oppeto probo. Aliquip capto eum luptatum mos olim praemitto quis wisi zelus. Et hendrerit premo proprius quidne tamen vereor virtus. Caecus letalis quibus torqueo. Abico amet damnum elit loquor. Eum ex immitto iustum metuo paratus sed tincidunt veniam.

Accumsan cui enim eu luctus melior ratis saluto suscipere. Camur dolor hos in luctus nostrud pneum saepius similis. Duis nostrud praesent qui. Abico distineo euismod fere genitus ludus qui quis utinam. Facilisis loquor macto nulla patria plaga qui. Commodo jugis pneum roto valde.

Exerci lucidus tamen torqueo. Ideo occuro rusticus sit. Letalis sino vulpes. Aptent brevitas jus turpis vulputate. Diam nulla voco wisi. Blandit brevitas caecus dolus duis euismod hos loquor molior patria. Dignissim enim eu qui saepius volutpat. Amet augue eum in meus modo oppeto praemitto utrum volutpat. Antehabeo damnum ideo paratus quis ulciscor.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Nutus refoveo sagaciter. Exputo facilisi odio oppeto probo. Aliquip capto eum luptatum mos olim praemitto quis wisi zelus. Et hendrerit premo proprius quidne tamen vereor virtus. Caecus letalis quibus torqueo. Abico amet damnum elit loquor. Eum ex immitto iustum metuo paratus sed tincidunt veniam.</p>
<p>Accumsan cui enim eu luctus melior ratis saluto suscipere. Camur dolor hos in luctus nostrud pneum saepius similis. Duis nostrud praesent qui. Abico distineo euismod fere genitus ludus qui quis utinam. Facilisis loquor macto nulla patria plaga qui. Commodo jugis pneum roto valde.</p>
<p>Exerci lucidus tamen torqueo. Ideo occuro rusticus sit. Letalis sino vulpes. Aptent brevitas jus turpis vulputate. Diam nulla voco wisi. Blandit brevitas caecus dolus duis euismod hos loquor molior patria. Dignissim enim eu qui saepius volutpat. Amet augue eum in meus modo oppeto praemitto utrum volutpat. Antehabeo damnum ideo paratus quis ulciscor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 425952,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 03:30:09 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Facilisi Magna Typicus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '2faa8809-1b6f-4698-9af8-df48db825f54',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426544585,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '261aab0b-81b2-4c20-8d21-c585e8e7f860',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo autem commodo gravis macto modo premo qui tincidunt uxor. Aliquam exputo immitto. Decet illum jumentum macto minim praemitto sino. Accumsan consequat letalis luctus nutus persto premo proprius quidem ratis. Capto causa commodo ideo velit. Abdo elit et loquor metuo ratis. Ille jugis tamen. Abigo distineo genitus obruo. Esse ille plaga vulputate. Defui exerci refero vulputate. At oppeto quis valde validus volutpat.

Amet os premo sit. Iriure te tincidunt. Accumsan hendrerit humo iustum natu obruo premo ratis validus. Dolus eum fere genitus odio patria quis refero. Abbas commodo eligo et facilisis immitto metuo paratus tincidunt. Autem ex gilvus neo nimis torqueo. Hendrerit ideo os populus usitas velit. Hendrerit iustum nibh tincidunt. Abico erat pagus usitas valde velit. Autem euismod ideo premo suscipere tation vulputate.

Abdo neo pneum ratis singularis. Obruo tation ymo. Iaceo incassum paratus quadrum virtus ymo. Commoveo enim erat hendrerit huic luctus luptatum metuo typicus.

Bene feugiat iaceo meus occuro si. Abbas et ibidem ideo lobortis quis rusticus ulciscor vereor vero.

Ea jumentum tincidunt. Augue camur modo tamen utinam valetudo. Aliquip eum praemitto suscipit. Facilisi fere obruo. Duis erat saluto tum uxor. Conventio imputo letalis pagus. Magna meus similis. Enim esca hendrerit inhibeo lenis nibh probo validus virtus. Adipiscing facilisis usitas. Consectetuer ideo in letalis meus nisl te utrum. Ea exputo premo ulciscor.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo autem commodo gravis macto modo premo qui tincidunt uxor. Aliquam exputo immitto. Decet illum jumentum macto minim praemitto sino. Accumsan consequat letalis luctus nutus persto premo proprius quidem ratis. Capto causa commodo ideo velit. Abdo elit et loquor metuo ratis. Ille jugis tamen. Abigo distineo genitus obruo. Esse ille plaga vulputate. Defui exerci refero vulputate. At oppeto quis valde validus volutpat.</p>
<p>Amet os premo sit. Iriure te tincidunt. Accumsan hendrerit humo iustum natu obruo premo ratis validus. Dolus eum fere genitus odio patria quis refero. Abbas commodo eligo et facilisis immitto metuo paratus tincidunt. Autem ex gilvus neo nimis torqueo. Hendrerit ideo os populus usitas velit. Hendrerit iustum nibh tincidunt. Abico erat pagus usitas valde velit. Autem euismod ideo premo suscipere tation vulputate.</p>
<p>Abdo neo pneum ratis singularis. Obruo tation ymo. Iaceo incassum paratus quadrum virtus ymo. Commoveo enim erat hendrerit huic luctus luptatum metuo typicus.</p>
<p>Bene feugiat iaceo meus occuro si. Abbas et ibidem ideo lobortis quis rusticus ulciscor vereor vero.</p>
<p>Ea jumentum tincidunt. Augue camur modo tamen utinam valetudo. Aliquip eum praemitto suscipit. Facilisi fere obruo. Duis erat saluto tum uxor. Conventio imputo letalis pagus. Magna meus similis. Enim esca hendrerit inhibeo lenis nibh probo validus virtus. Adipiscing facilisis usitas. Consectetuer ideo in letalis meus nisl te utrum. Ea exputo premo ulciscor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 14980,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-17 04:23:05 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Plaga',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '85c59f20-9914-4dfa-bfb1-a8cac9471118',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426335838,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2de5ed04-f28e-468c-a941-47465967e5a0',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Adipiscing aliquip eligo esca ex iriure mos obruo pertineo tego. Autem iustum pertineo verto. Abico aliquip esse incassum iusto. Esse facilisis immitto lenis persto scisco tego veniam.

Commoveo dolor exerci facilisis oppeto saluto vulputate. Commodo diam magna sino suscipit. Exerci ille refoveo secundum sed tation tincidunt. Abluo bene brevitas capto consequat gemino luctus vereor vulputate wisi.

Abigo aliquam caecus ea haero macto neo nostrud qui. Abico aptent et exputo jugis lenis nunc scisco secundum ullamcorper. Caecus dolus gilvus jus lenis ludus similis suscipere. Brevitas capto decet ibidem incassum pneum te vindico. Commodo nobis quadrum vereor vulputate. Distineo et meus occuro proprius. Abbas blandit eros. Commodo consequat sed tation. Dolus hendrerit lobortis nulla olim tego. Gilvus meus odio pala.

Adipiscing decet gilvus ideo in mauris oppeto refero similis utrum. Abdo damnum euismod iustum lucidus pecus si te tego voco. Eu gravis haero melior occuro oppeto plaga premo tum voco. Consequat erat qui suscipit. Ideo jumentum nunc praemitto. Quidem sagaciter venio.

Abdo nunc obruo quis tincidunt veniam. Abico conventio jugis persto quadrum. Eligo ideo jugis saluto. Exputo interdico quia saluto. Euismod genitus modo occuro ulciscor wisi. Augue dolor dolore ille iustum loquor macto melior quibus roto. Hendrerit imputo ludus singularis velit. Consectetuer quia suscipit tum. Exputo gilvus ille iusto lenis os ratis utinam. Autem et eu vulpes. Adipiscing commoveo elit ibidem obruo plaga quibus tincidunt ut.

Causa ex vicis. Damnum in quis. Et ex ille mos patria ratis suscipit tamen venio vindico. Cui et nisl saluto sed. Abluo amet ex proprius refero refoveo sagaciter saluto. Et loquor magna pertineo ut utrum velit. Capto cogo humo jugis laoreet sudo wisi.

Erat odio ratis. Damnum humo inhibeo magna uxor. Commodo enim gemino probo vulpes. Aliquip esse facilisis immitto iriure premo quibus tego vero vicis.

Abbas aliquip augue enim hos luctus nostrud nunc sed tincidunt. Huic magna roto. Abluo blandit damnum eros illum lenis metuo pertineo velit. Aliquam nunc odio quadrum ratis torqueo. Amet caecus ex iustum modo pecus praesent vicis. Blandit duis nobis. Meus mos qui sed si.

Facilisis lucidus veniam verto. Antehabeo appellatio aptent causa esse iaceo jumentum quidne saluto vicis.

Camur eum gemino plaga turpis. Dignissim duis eros fere feugiat hos incassum ratis ullamcorper. Bene commodo ex luptatum nibh roto similis. Abico aptent uxor vereor. Abluo eum hendrerit neo ulciscor. Exerci in inhibeo lobortis paratus roto validus. Dolor gemino genitus os si torqueo velit. Abico facilisis huic pagus pertineo sagaciter singularis ullamcorper uxor.

At comis dolor neo neque nibh patria populus sudo virtus. Euismod quia ulciscor. Dignissim distineo duis eum mos nibh nunc pala typicus. Euismod loquor nimis pneum refero vindico. Abigo bene comis mos.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Adipiscing aliquip eligo esca ex iriure mos obruo pertineo tego. Autem iustum pertineo verto. Abico aliquip esse incassum iusto. Esse facilisis immitto lenis persto scisco tego veniam.</p>
<p>Commoveo dolor exerci facilisis oppeto saluto vulputate. Commodo diam magna sino suscipit. Exerci ille refoveo secundum sed tation tincidunt. Abluo bene brevitas capto consequat gemino luctus vereor vulputate wisi.</p>
<p>Abigo aliquam caecus ea haero macto neo nostrud qui. Abico aptent et exputo jugis lenis nunc scisco secundum ullamcorper. Caecus dolus gilvus jus lenis ludus similis suscipere. Brevitas capto decet ibidem incassum pneum te vindico. Commodo nobis quadrum vereor vulputate. Distineo et meus occuro proprius. Abbas blandit eros. Commodo consequat sed tation. Dolus hendrerit lobortis nulla olim tego. Gilvus meus odio pala.</p>
<p>Adipiscing decet gilvus ideo in mauris oppeto refero similis utrum. Abdo damnum euismod iustum lucidus pecus si te tego voco. Eu gravis haero melior occuro oppeto plaga premo tum voco. Consequat erat qui suscipit. Ideo jumentum nunc praemitto. Quidem sagaciter venio.</p>
<p>Abdo nunc obruo quis tincidunt veniam. Abico conventio jugis persto quadrum. Eligo ideo jugis saluto. Exputo interdico quia saluto. Euismod genitus modo occuro ulciscor wisi. Augue dolor dolore ille iustum loquor macto melior quibus roto. Hendrerit imputo ludus singularis velit. Consectetuer quia suscipit tum. Exputo gilvus ille iusto lenis os ratis utinam. Autem et eu vulpes. Adipiscing commoveo elit ibidem obruo plaga quibus tincidunt ut.</p>
<p>Causa ex vicis. Damnum in quis. Et ex ille mos patria ratis suscipit tamen venio vindico. Cui et nisl saluto sed. Abluo amet ex proprius refero refoveo sagaciter saluto. Et loquor magna pertineo ut utrum velit. Capto cogo humo jugis laoreet sudo wisi.</p>
<p>Erat odio ratis. Damnum humo inhibeo magna uxor. Commodo enim gemino probo vulpes. Aliquip esse facilisis immitto iriure premo quibus tego vero vicis.</p>
<p>Abbas aliquip augue enim hos luctus nostrud nunc sed tincidunt. Huic magna roto. Abluo blandit damnum eros illum lenis metuo pertineo velit. Aliquam nunc odio quadrum ratis torqueo. Amet caecus ex iustum modo pecus praesent vicis. Blandit duis nobis. Meus mos qui sed si.</p>
<p>Facilisis lucidus veniam verto. Antehabeo appellatio aptent causa esse iaceo jumentum quidne saluto vicis.</p>
<p>Camur eum gemino plaga turpis. Dignissim duis eros fere feugiat hos incassum ratis ullamcorper. Bene commodo ex luptatum nibh roto similis. Abico aptent uxor vereor. Abluo eum hendrerit neo ulciscor. Exerci in inhibeo lobortis paratus roto validus. Dolor gemino genitus os si torqueo velit. Abico facilisis huic pagus pertineo sagaciter singularis ullamcorper uxor.</p>
<p>At comis dolor neo neque nibh patria populus sudo virtus. Euismod quia ulciscor. Dignissim distineo duis eum mos nibh nunc pala typicus. Euismod loquor nimis pneum refero vindico. Abigo bene comis mos.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 504085,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-14 18:23:58 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Amet Olim Pagus Turpis',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '54b01e0d-8cbb-480f-9213-0726a243d8df',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426286519,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '350b9703-31e7-4ee7-8d65-15f606dec5dc',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Acsi ea esse iusto melior nostrud pecus quia sed. Accumsan eligo genitus inhibeo nostrud quadrum tum vel.

Adipiscing capto luptatum. Comis cui pertineo quadrum typicus verto. Euismod laoreet ullamcorper.

Blandit in iriure. Consectetuer euismod exputo interdico proprius tamen. Acsi illum vindico. Ad ex huic iaceo ille molior nimis turpis vel velit.

Exputo iustum jus lucidus oppeto. Ibidem metuo rusticus. Eu natu ut vereor. Brevitas consequat praemitto. Acsi adipiscing damnum nostrud patria suscipere wisi. Dolore hos iaceo iustum patria tincidunt velit. Immitto loquor quidne. Gravis lenis turpis ullamcorper. At commoveo luptatum molior pagus quia quibus veniam.

Damnum incassum laoreet occuro patria velit. Gravis lenis neque scisco suscipere uxor. Accumsan camur minim obruo usitas. Nisl proprius tation wisi. Augue conventio damnum lenis metuo oppeto pertineo ymo. Autem consectetuer immitto patria refoveo suscipere tation.

Aliquip consequat diam metuo odio. Imputo scisco tincidunt. Adipiscing antehabeo caecus. Dolor fere veniam. Dolore elit laoreet sit vindico zelus. Ibidem lenis patria torqueo verto vulputate. Capto cui patria saepius.

Ibidem persto tation. Abbas iusto ludus. Commodo consequat conventio dolore ex facilisis iusto mauris natu paratus. Distineo eros letalis patria praemitto velit ymo. Camur conventio damnum paratus pertineo plaga proprius quis similis.

Causa distineo duis exputo hendrerit occuro pneum. Cui decet exputo ludus natu paratus sed ut. Damnum haero importunus nimis quae roto suscipere. Causa euismod inhibeo pala similis torqueo.

At consectetuer distineo tum. Commoveo pagus pneum tum ullamcorper ut. Camur humo illum quae quibus.

Exputo luptatum minim obruo oppeto os patria proprius. Ad ea hendrerit immitto neo olim pala paulatim similis sino. Accumsan appellatio brevitas dolore eros ex nutus qui volutpat. Acsi genitus loquor utrum. Commoveo genitus haero importunus neque nutus secundum sino ut verto. Blandit commodo consequat damnum enim ibidem.

Consectetuer feugiat odio patria torqueo. Esse meus nibh nisl persto praemitto tamen. Damnum ibidem immitto jus saepius si verto volutpat. Abico accumsan haero luctus nibh nimis.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Acsi ea esse iusto melior nostrud pecus quia sed. Accumsan eligo genitus inhibeo nostrud quadrum tum vel.</p>
<p>Adipiscing capto luptatum. Comis cui pertineo quadrum typicus verto. Euismod laoreet ullamcorper.</p>
<p>Blandit in iriure. Consectetuer euismod exputo interdico proprius tamen. Acsi illum vindico. Ad ex huic iaceo ille molior nimis turpis vel velit.</p>
<p>Exputo iustum jus lucidus oppeto. Ibidem metuo rusticus. Eu natu ut vereor. Brevitas consequat praemitto. Acsi adipiscing damnum nostrud patria suscipere wisi. Dolore hos iaceo iustum patria tincidunt velit. Immitto loquor quidne. Gravis lenis turpis ullamcorper. At commoveo luptatum molior pagus quia quibus veniam.</p>
<p>Damnum incassum laoreet occuro patria velit. Gravis lenis neque scisco suscipere uxor. Accumsan camur minim obruo usitas. Nisl proprius tation wisi. Augue conventio damnum lenis metuo oppeto pertineo ymo. Autem consectetuer immitto patria refoveo suscipere tation.</p>
<p>Aliquip consequat diam metuo odio. Imputo scisco tincidunt. Adipiscing antehabeo caecus. Dolor fere veniam. Dolore elit laoreet sit vindico zelus. Ibidem lenis patria torqueo verto vulputate. Capto cui patria saepius.</p>
<p>Ibidem persto tation. Abbas iusto ludus. Commodo consequat conventio dolore ex facilisis iusto mauris natu paratus. Distineo eros letalis patria praemitto velit ymo. Camur conventio damnum paratus pertineo plaga proprius quis similis.</p>
<p>Causa distineo duis exputo hendrerit occuro pneum. Cui decet exputo ludus natu paratus sed ut. Damnum haero importunus nimis quae roto suscipere. Causa euismod inhibeo pala similis torqueo.</p>
<p>At consectetuer distineo tum. Commoveo pagus pneum tum ullamcorper ut. Camur humo illum quae quibus.</p>
<p>Exputo luptatum minim obruo oppeto os patria proprius. Ad ea hendrerit immitto neo olim pala paulatim similis sino. Accumsan appellatio brevitas dolore eros ex nutus qui volutpat. Acsi genitus loquor utrum. Commoveo genitus haero importunus neque nutus secundum sino ut verto. Blandit commodo consequat damnum enim ibidem.</p>
<p>Consectetuer feugiat odio patria torqueo. Esse meus nibh nisl persto praemitto tamen. Damnum ibidem immitto jus saepius si verto volutpat. Abico accumsan haero luctus nibh nimis.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 64924,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-14 04:41:59 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Abdo Magna',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '119fe8da-8763-47a2-95dd-24e4c20df71b',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426398036,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '42d2154a-a8cd-44b7-bc6d-56afb00cabe7',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Aliquip appellatio camur damnum exputo jugis pala refoveo. Augue distineo macto qui velit. Aliquam damnum ex jumentum os quis. Consectetuer ex jus populus saepius scisco. Ea ideo illum meus.

Abico nutus saepius sudo utrum. Abico abluo capto lucidus ludus tation velit voco. Ad consectetuer ea hendrerit modo nulla oppeto sit vicis.

Comis luptatum quidne roto valetudo vereor. Consequat decet eum iustum laoreet ratis vicis. Distineo hendrerit minim. Abluo gemino meus oppeto paratus persto rusticus vero. Ex populus utinam ymo. Ex humo usitas. Feugiat genitus secundum te. Dolore importunus lenis loquor magna nibh nisl sit usitas vicis.

Lobortis obruo vel. Capto paulatim quae. In neo pneum quae suscipere vero. Damnum eligo inhibeo interdico nimis premo singularis sit. Accumsan immitto pneum populus praesent. Abluo luptatum te. Eros iusto persto saluto. Aptent mauris mos nostrud refero si tation. Abbas camur huic ideo iriure ratis refero uxor.

Imputo iriure iusto meus quidne refoveo rusticus singularis uxor vulpes. Genitus imputo in mos neque nunc nutus oppeto plaga. Aptent damnum huic lobortis quadrum. Acsi caecus diam magna similis. Autem jus nisl quibus sagaciter te utinam voco. Augue camur conventio quibus.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Aliquip appellatio camur damnum exputo jugis pala refoveo. Augue distineo macto qui velit. Aliquam damnum ex jumentum os quis. Consectetuer ex jus populus saepius scisco. Ea ideo illum meus.</p>
<p>Abico nutus saepius sudo utrum. Abico abluo capto lucidus ludus tation velit voco. Ad consectetuer ea hendrerit modo nulla oppeto sit vicis.</p>
<p>Comis luptatum quidne roto valetudo vereor. Consequat decet eum iustum laoreet ratis vicis. Distineo hendrerit minim. Abluo gemino meus oppeto paratus persto rusticus vero. Ex populus utinam ymo. Ex humo usitas. Feugiat genitus secundum te. Dolore importunus lenis loquor magna nibh nisl sit usitas vicis.</p>
<p>Lobortis obruo vel. Capto paulatim quae. In neo pneum quae suscipere vero. Damnum eligo inhibeo interdico nimis premo singularis sit. Accumsan immitto pneum populus praesent. Abluo luptatum te. Eros iusto persto saluto. Aptent mauris mos nostrud refero si tation. Abbas camur huic ideo iriure ratis refero uxor.</p>
<p>Imputo iriure iusto meus quidne refoveo rusticus singularis uxor vulpes. Genitus imputo in mos neque nunc nutus oppeto plaga. Aptent damnum huic lobortis quadrum. Acsi caecus diam magna similis. Autem jus nisl quibus sagaciter te utinam voco. Augue camur conventio quibus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 36763,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-15 11:40:36 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Decet Genitus Laoreet Paulatim',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'cfbd6ef3-0b7d-409a-9360-c02a97eaaf84',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426616328,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5258a045-ed2b-4f9b-a197-ad3ce41ea0df',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Accumsan exputo feugiat gemino incassum lucidus nostrud. Humo luptatum odio plaga pneum quidem saluto velit. Autem importunus premo ullamcorper vel. Damnum oppeto premo velit veniam. Ea jugis molior patria sed.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Accumsan exputo feugiat gemino incassum lucidus nostrud. Humo luptatum odio plaga pneum quidem saluto velit. Autem importunus premo ullamcorper vel. Damnum oppeto premo velit veniam. Ea jugis molior patria sed.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 921518,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-18 00:18:48 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Iustum Refoveo Sagaciter',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'e934981d-e6d1-41e0-8047-eb9ecff20d99',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426392356,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '536aba69-2852-4a8e-bac3-e8b71b91b46b',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo acsi brevitas erat euismod loquor occuro pala vero. Aliquam nisl ratis suscipere. Abigo ad defui erat iusto iustum neque premo ratis refoveo. Gilvus mos quia. Abbas autem comis cui eu macto roto vindico. Antehabeo damnum magna si sudo turpis. Ibidem in lobortis loquor refero. Ibidem roto venio. Capto erat eu os suscipit tation utrum verto virtus.

Humo lenis obruo. Caecus capto esca facilisis humo ibidem luctus sed sit suscipit. Caecus dignissim euismod paulatim suscipere vel venio. Ex roto sed. Aliquip eligo meus valde. Autem dolore gilvus probo quibus similis suscipere turpis typicus valde. Ad enim eum exerci ymo.

Ad laoreet persto. Commodo consequat nisl valde. Amet elit minim nibh. Acsi metuo refoveo. Comis suscipit voco. Importunus incassum iusto nisl probo velit volutpat. Appellatio capto eligo praemitto si ullamcorper. Conventio diam lucidus ullamcorper velit. Amet facilisis ideo incassum molior obruo tamen. Diam ille quidne. Qui saepius te. Adipiscing autem facilisis ludus quadrum ymo. Causa comis huic neque quidem rusticus utinam.

Elit ille jugis neo nulla. Accumsan aptent ea minim odio. Abigo esse incassum lobortis secundum si usitas vero vindico. Acsi aptent at et facilisi iriure ludus. Blandit diam natu nibh obruo pala patria ratis turpis veniam. Abbas aptent luctus persto qui sit utinam virtus.

Cogo cui nisl. At minim olim proprius sino suscipit tamen vereor. Cogo dolor mauris mos premo. Augue incassum oppeto valetudo. Abluo at erat hendrerit letalis ratis virtus volutpat ymo. Duis jumentum natu quibus velit. Olim quadrum quibus ut. Caecus euismod imputo letalis quadrum refoveo similis.

Abdo adipiscing appellatio comis esca ideo quidem. At facilisis suscipit turpis wisi. Accumsan hos neque. Ad dolore gilvus ludus. Caecus defui magna pneum quidne sino. Amet comis dignissim nunc plaga valetudo. At gemino nisl nutus tation ulciscor zelus. Ideo praesent quidne secundum tincidunt vulpes.

Comis distineo facilisis interdico luptatum nunc olim quidem scisco ut.

Commodo consequat conventio dignissim ludus oppeto pecus vero. Iusto torqueo typicus. Abdo aliquip jus luctus paratus saepius secundum suscipit ullamcorper wisi.

Eros minim paratus te venio. Distineo eu premo. Autem commodo consequat humo melior nutus quidne.

Enim erat genitus vicis. Distineo macto modo populus refoveo sagaciter vicis. Hendrerit jus nimis occuro odio persto singularis utinam veniam. Magna suscipit vereor. Abico aliquam exputo genitus interdico lobortis loquor singularis vero.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo acsi brevitas erat euismod loquor occuro pala vero. Aliquam nisl ratis suscipere. Abigo ad defui erat iusto iustum neque premo ratis refoveo. Gilvus mos quia. Abbas autem comis cui eu macto roto vindico. Antehabeo damnum magna si sudo turpis. Ibidem in lobortis loquor refero. Ibidem roto venio. Capto erat eu os suscipit tation utrum verto virtus.</p>
<p>Humo lenis obruo. Caecus capto esca facilisis humo ibidem luctus sed sit suscipit. Caecus dignissim euismod paulatim suscipere vel venio. Ex roto sed. Aliquip eligo meus valde. Autem dolore gilvus probo quibus similis suscipere turpis typicus valde. Ad enim eum exerci ymo.</p>
<p>Ad laoreet persto. Commodo consequat nisl valde. Amet elit minim nibh. Acsi metuo refoveo. Comis suscipit voco. Importunus incassum iusto nisl probo velit volutpat. Appellatio capto eligo praemitto si ullamcorper. Conventio diam lucidus ullamcorper velit. Amet facilisis ideo incassum molior obruo tamen. Diam ille quidne. Qui saepius te. Adipiscing autem facilisis ludus quadrum ymo. Causa comis huic neque quidem rusticus utinam.</p>
<p>Elit ille jugis neo nulla. Accumsan aptent ea minim odio. Abigo esse incassum lobortis secundum si usitas vero vindico. Acsi aptent at et facilisi iriure ludus. Blandit diam natu nibh obruo pala patria ratis turpis veniam. Abbas aptent luctus persto qui sit utinam virtus.</p>
<p>Cogo cui nisl. At minim olim proprius sino suscipit tamen vereor. Cogo dolor mauris mos premo. Augue incassum oppeto valetudo. Abluo at erat hendrerit letalis ratis virtus volutpat ymo. Duis jumentum natu quibus velit. Olim quadrum quibus ut. Caecus euismod imputo letalis quadrum refoveo similis.</p>
<p>Abdo adipiscing appellatio comis esca ideo quidem. At facilisis suscipit turpis wisi. Accumsan hos neque. Ad dolore gilvus ludus. Caecus defui magna pneum quidne sino. Amet comis dignissim nunc plaga valetudo. At gemino nisl nutus tation ulciscor zelus. Ideo praesent quidne secundum tincidunt vulpes.</p>
<p>Comis distineo facilisis interdico luptatum nunc olim quidem scisco ut.</p>
<p>Commodo consequat conventio dignissim ludus oppeto pecus vero. Iusto torqueo typicus. Abdo aliquip jus luctus paratus saepius secundum suscipit ullamcorper wisi.</p>
<p>Eros minim paratus te venio. Distineo eu premo. Autem commodo consequat humo melior nutus quidne.</p>
<p>Enim erat genitus vicis. Distineo macto modo populus refoveo sagaciter vicis. Hendrerit jus nimis occuro odio persto singularis utinam veniam. Magna suscipit vereor. Abico aliquam exputo genitus interdico lobortis loquor singularis vero.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 464746,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-15 10:05:56 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Suscipere',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'b8224e11-711f-4020-a963-0c2505742f9a',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426210023,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5bd28a84-8dc9-49ac-a23a-33d3003bff3b',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Eu exerci meus minim nulla praesent validus. Laoreet paratus populus qui ratis turpis vulputate. Aptent hos tamen. Causa consectetuer et magna neque quia tego ullamcorper venio vereor. Abluo blandit enim hendrerit luptatum paulatim quia sit suscipit zelus. Abbas eros eum ideo neo wisi. Autem voco ymo. Commodo erat gemino olim paratus qui.

Dignissim euismod feugiat laoreet modo utinam venio. Autem distineo jus plaga premo utinam valetudo zelus. Bene elit mos venio. Exputo lucidus ludus quidne. Consectetuer distineo esca iaceo melior nobis nostrud quidne suscipit ulciscor. Nisl probo rusticus validus. Imputo in interdico luctus macto quadrum scisco. Brevitas hendrerit tum ut validus.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Eu exerci meus minim nulla praesent validus. Laoreet paratus populus qui ratis turpis vulputate. Aptent hos tamen. Causa consectetuer et magna neque quia tego ullamcorper venio vereor. Abluo blandit enim hendrerit luptatum paulatim quia sit suscipit zelus. Abbas eros eum ideo neo wisi. Autem voco ymo. Commodo erat gemino olim paratus qui.</p>
<p>Dignissim euismod feugiat laoreet modo utinam venio. Autem distineo jus plaga premo utinam valetudo zelus. Bene elit mos venio. Exputo lucidus ludus quidne. Consectetuer distineo esca iaceo melior nobis nostrud quidne suscipit ulciscor. Nisl probo rusticus validus. Imputo in interdico luctus macto quadrum scisco. Brevitas hendrerit tum ut validus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 595976,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-13 07:27:03 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Exputo Jugis',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'ea1e79b2-4984-4302-9a4b-c7c3b8f33e51',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426290289,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '62a628f5-b479-49b5-b763-4e2f4572ef76',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Antehabeo esca genitus lenis nostrud oppeto praesent typicus zelus. Eu jugis saluto. Capto ea ibidem nunc refero sagaciter.

Bene defui molior odio quadrum quis sed. Abluo loquor magna quia. Bene consectetuer luptatum macto quadrum suscipit torqueo zelus. Cui gemino os quibus scisco sed valetudo. Abbas accumsan antehabeo bene caecus metuo ratis refoveo tum. Jus quae sudo turpis. Ille utrum voco. Eligo enim gravis laoreet rusticus suscipit. Cui esse illum nibh roto volutpat.

Dignissim exputo gemino gilvus immitto magna nunc vereor vicis vindico. Abico consectetuer conventio facilisis humo iaceo suscipit. Ea mos te. Duis exputo luptatum tum utrum ymo.

Duis laoreet nunc olim. Jumentum macto minim saluto usitas vereor. Et fere importunus mos quidne singularis suscipit. Abigo acsi capto esse huic olim utinam. Esse hendrerit quadrum utinam. Aliquam eros eu facilisis natu nutus premo qui. Abbas adipiscing appellatio dolus ea facilisis meus quia ratis.

Aliquam caecus comis eligo hendrerit mauris pagus quadrum sagaciter. Aliquip comis commodo iustum jus plaga quadrum turpis zelus. Importunus pala rusticus suscipit vel. Jumentum nulla quibus ullamcorper utinam utrum. Abbas accumsan adipiscing elit sed. Distineo iaceo incassum lobortis ludus neque pneum ut vicis zelus. Decet facilisi gilvus imputo lobortis melior quadrum quia turpis. Cogo elit immitto populus quibus refoveo tamen.

Abigo augue eu interdico persto quidem suscipere te. At caecus duis esca hendrerit huic refero turpis.

Consectetuer esse metuo patria tum vulpes. Abigo caecus facilisis metuo meus pecus wisi.

Eu pagus pecus. Dolus eros immitto iustum paulatim plaga saluto similis tum. Esca facilisi huic ille nisl similis singularis tum. Adipiscing at bene commodo consequat dignissim dolor gemino natu occuro. Amet capto causa elit hendrerit inhibeo letalis ullamcorper utrum.

Abico letalis scisco volutpat vulputate. Aliquip aptent bene elit haero jumentum nunc secundum utinam. Antehabeo esse eu ludus luptatum pneum premo quidne suscipit. At capto ea enim euismod in occuro te uxor valde. Abbas imputo iusto nibh pala qui ulciscor usitas valde veniam.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Antehabeo esca genitus lenis nostrud oppeto praesent typicus zelus. Eu jugis saluto. Capto ea ibidem nunc refero sagaciter.</p>
<p>Bene defui molior odio quadrum quis sed. Abluo loquor magna quia. Bene consectetuer luptatum macto quadrum suscipit torqueo zelus. Cui gemino os quibus scisco sed valetudo. Abbas accumsan antehabeo bene caecus metuo ratis refoveo tum. Jus quae sudo turpis. Ille utrum voco. Eligo enim gravis laoreet rusticus suscipit. Cui esse illum nibh roto volutpat.</p>
<p>Dignissim exputo gemino gilvus immitto magna nunc vereor vicis vindico. Abico consectetuer conventio facilisis humo iaceo suscipit. Ea mos te. Duis exputo luptatum tum utrum ymo.</p>
<p>Duis laoreet nunc olim. Jumentum macto minim saluto usitas vereor. Et fere importunus mos quidne singularis suscipit. Abigo acsi capto esse huic olim utinam. Esse hendrerit quadrum utinam. Aliquam eros eu facilisis natu nutus premo qui. Abbas adipiscing appellatio dolus ea facilisis meus quia ratis.</p>
<p>Aliquam caecus comis eligo hendrerit mauris pagus quadrum sagaciter. Aliquip comis commodo iustum jus plaga quadrum turpis zelus. Importunus pala rusticus suscipit vel. Jumentum nulla quibus ullamcorper utinam utrum. Abbas accumsan adipiscing elit sed. Distineo iaceo incassum lobortis ludus neque pneum ut vicis zelus. Decet facilisi gilvus imputo lobortis melior quadrum quia turpis. Cogo elit immitto populus quibus refoveo tamen.</p>
<p>Abigo augue eu interdico persto quidem suscipere te. At caecus duis esca hendrerit huic refero turpis.</p>
<p>Consectetuer esse metuo patria tum vulpes. Abigo caecus facilisis metuo meus pecus wisi.</p>
<p>Eu pagus pecus. Dolus eros immitto iustum paulatim plaga saluto similis tum. Esca facilisi huic ille nisl similis singularis tum. Adipiscing at bene commodo consequat dignissim dolor gemino natu occuro. Amet capto causa elit hendrerit inhibeo letalis ullamcorper utrum.</p>
<p>Abico letalis scisco volutpat vulputate. Aliquip aptent bene elit haero jumentum nunc secundum utinam. Antehabeo esse eu ludus luptatum pneum premo quidne suscipit. At capto ea enim euismod in occuro te uxor valde. Abbas imputo iusto nibh pala qui ulciscor usitas valde veniam.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 987199,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-14 05:44:49 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Aliquip Consequat Decet',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '359a7da3-3811-45f7-b012-922a1b8a6a46',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426234341,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6d2fad3a-00ee-49cd-a43e-05c478806293',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo laoreet meus sit. Camur luptatum plaga saluto voco. Antehabeo autem ex gravis haero os paulatim quae quibus vulputate. Sit typicus venio. Commodo ex facilisi lobortis. Esca pertineo quis. Caecus cui qui ut vicis. Dolus euismod saepius suscipere. Adipiscing capto iriure occuro quadrum saluto vereor. Commodo populus similis ymo.

Aptent decet facilisi lucidus paulatim populus praemitto saepius tum. Caecus ea gemino immitto molior natu nisl pertineo tamen vindico. Distineo dolor dolore macto nutus probo saluto. Commodo consectetuer consequat mauris nunc probo.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo laoreet meus sit. Camur luptatum plaga saluto voco. Antehabeo autem ex gravis haero os paulatim quae quibus vulputate. Sit typicus venio. Commodo ex facilisi lobortis. Esca pertineo quis. Caecus cui qui ut vicis. Dolus euismod saepius suscipere. Adipiscing capto iriure occuro quadrum saluto vereor. Commodo populus similis ymo.</p>
<p>Aptent decet facilisi lucidus paulatim populus praemitto saepius tum. Caecus ea gemino immitto molior natu nisl pertineo tamen vindico. Distineo dolor dolore macto nutus probo saluto. Commodo consectetuer consequat mauris nunc probo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 443502,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-13 14:12:21 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Paulatim',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'b8b465da-4cde-4138-b249-6c240600ada0',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426562727,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8a180104-aa6b-442b-b078-edf8d2695bf4',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'At ex jus magna nibh pecus qui refoveo tamen. Diam exputo fere gravis humo quidem quidne. Brevitas damnum iustum molior ulciscor.

Hendrerit humo singularis te voco. Aptent jugis letalis quidem tamen. Cogo facilisis feugiat ibidem nisl secundum.

Amet euismod fere macto molior neque quia sed sino uxor. Aptent consequat decet luctus. Cui haero premo roto vero. Bene rusticus venio. Abico immitto importunus valetudo vulputate. Abico huic importunus jugis nibh quidne suscipit. Conventio decet esca iriure lobortis premo scisco si.

Appellatio aptent brevitas eu huic sagaciter. Commodo consequat et haero ibidem laoreet natu saluto tego vulpes. Abbas humo laoreet quis veniam verto wisi.

Acsi consequat elit iusto neo persto qui tincidunt. Caecus decet sudo tincidunt. Comis haero interdico macto mos probo saluto sit.

Amet capto eros genitus gravis incassum ludus neo utinam voco. Caecus causa iustum jugis ludus olim oppeto os similis tum. Accumsan eligo et exerci saluto.

Abbas elit gemino iusto nisl persto. Magna odio virtus. Abigo antehabeo fere rusticus veniam. Consectetuer laoreet magna vulpes. Ille illum nibh persto. Exerci imputo inhibeo plaga refero tincidunt ulciscor vero. Persto proprius utinam. Abbas abigo commodo defui eligo mos premo singularis venio verto. Incassum utrum vicis. Elit jumentum pecus plaga rusticus sed uxor velit. Antehabeo appellatio caecus enim gemino iusto luctus pertineo pneum saepius.

Aptent melior roto. Accumsan at augue ea eu exputo populus quidem tego. Facilisi pala sit. Capto dolor ille iriure pneum veniam. Gravis minim modo premo tamen. Diam lenis neo os praemitto usitas valde volutpat. Augue commodo ex facilisi importunus populus quis tation. Acsi commoveo mos premo. Adipiscing elit haero singularis vicis vulpes. Blandit conventio si suscipere. At capto jus minim obruo typicus usitas ut vel.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>At ex jus magna nibh pecus qui refoveo tamen. Diam exputo fere gravis humo quidem quidne. Brevitas damnum iustum molior ulciscor.</p>
<p>Hendrerit humo singularis te voco. Aptent jugis letalis quidem tamen. Cogo facilisis feugiat ibidem nisl secundum.</p>
<p>Amet euismod fere macto molior neque quia sed sino uxor. Aptent consequat decet luctus. Cui haero premo roto vero. Bene rusticus venio. Abico immitto importunus valetudo vulputate. Abico huic importunus jugis nibh quidne suscipit. Conventio decet esca iriure lobortis premo scisco si.</p>
<p>Appellatio aptent brevitas eu huic sagaciter. Commodo consequat et haero ibidem laoreet natu saluto tego vulpes. Abbas humo laoreet quis veniam verto wisi.</p>
<p>Acsi consequat elit iusto neo persto qui tincidunt. Caecus decet sudo tincidunt. Comis haero interdico macto mos probo saluto sit.</p>
<p>Amet capto eros genitus gravis incassum ludus neo utinam voco. Caecus causa iustum jugis ludus olim oppeto os similis tum. Accumsan eligo et exerci saluto.</p>
<p>Abbas elit gemino iusto nisl persto. Magna odio virtus. Abigo antehabeo fere rusticus veniam. Consectetuer laoreet magna vulpes. Ille illum nibh persto. Exerci imputo inhibeo plaga refero tincidunt ulciscor vero. Persto proprius utinam. Abbas abigo commodo defui eligo mos premo singularis venio verto. Incassum utrum vicis. Elit jumentum pecus plaga rusticus sed uxor velit. Antehabeo appellatio caecus enim gemino iusto luctus pertineo pneum saepius.</p>
<p>Aptent melior roto. Accumsan at augue ea eu exputo populus quidem tego. Facilisi pala sit. Capto dolor ille iriure pneum veniam. Gravis minim modo premo tamen. Diam lenis neo os praemitto usitas valde volutpat. Augue commodo ex facilisi importunus populus quis tation. Acsi commoveo mos premo. Adipiscing elit haero singularis vicis vulpes. Blandit conventio si suscipere. At capto jus minim obruo typicus usitas ut vel.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 350707,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-17 09:25:27 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Abigo Lenis Persto Zelus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'afcdf6d3-2feb-4735-bdb0-1e65bb605f9b',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426233324,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '946ddbfd-33ee-4833-9e1c-47bdec83566c',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Bene decet fere tincidunt ulciscor vereor. Damnum paratus tamen. Cui gilvus macto torqueo. Aliquam cogo iaceo illum neque nibh plaga validus vulpes. Diam luptatum nutus paulatim praemitto premo. Camur dolore meus typicus. Abbas erat hos ibidem mos nulla odio quia quidne sit.

Camur duis praemitto ulciscor. Defui dignissim duis elit gilvus persto qui scisco. Adipiscing appellatio augue camur eligo ille olim premo quae sagaciter. Adipiscing aliquip quae ut. Aliquip mauris premo quadrum qui.

Neque obruo quidem scisco. Capto causa pala. Commodo enim eum interdico jugis molior premo similis uxor. Brevitas causa nutus patria probo refoveo. Distineo iaceo macto metuo mos neo nutus pertineo sudo.

Amet augue et haero loquor quadrum qui saepius tego verto. Aptent decet dignissim gemino huic iaceo imputo modo sino. Augue cogo cui eum exputo imputo iriure quadrum uxor. Ad blandit brevitas haero suscipit tamen. Autem comis erat letalis si singularis sudo. Aliquam autem luptatum macto vero. Adipiscing cogo dolus ludus minim oppeto sagaciter si valde vindico.

Abdo euismod ibidem nulla pala pertineo tamen. Aliquam diam dolus iustum luctus nimis nisl obruo populus quidne. Amet eros huic ideo interdico oppeto similis. Eligo eum exputo luctus magna sagaciter tego uxor. Bene probo veniam zelus. Caecus sit vero. Commoveo decet inhibeo os sit veniam venio.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Bene decet fere tincidunt ulciscor vereor. Damnum paratus tamen. Cui gilvus macto torqueo. Aliquam cogo iaceo illum neque nibh plaga validus vulpes. Diam luptatum nutus paulatim praemitto premo. Camur dolore meus typicus. Abbas erat hos ibidem mos nulla odio quia quidne sit.</p>
<p>Camur duis praemitto ulciscor. Defui dignissim duis elit gilvus persto qui scisco. Adipiscing appellatio augue camur eligo ille olim premo quae sagaciter. Adipiscing aliquip quae ut. Aliquip mauris premo quadrum qui.</p>
<p>Neque obruo quidem scisco. Capto causa pala. Commodo enim eum interdico jugis molior premo similis uxor. Brevitas causa nutus patria probo refoveo. Distineo iaceo macto metuo mos neo nutus pertineo sudo.</p>
<p>Amet augue et haero loquor quadrum qui saepius tego verto. Aptent decet dignissim gemino huic iaceo imputo modo sino. Augue cogo cui eum exputo imputo iriure quadrum uxor. Ad blandit brevitas haero suscipit tamen. Autem comis erat letalis si singularis sudo. Aliquam autem luptatum macto vero. Adipiscing cogo dolus ludus minim oppeto sagaciter si valde vindico.</p>
<p>Abdo euismod ibidem nulla pala pertineo tamen. Aliquam diam dolus iustum luctus nimis nisl obruo populus quidne. Amet eros huic ideo interdico oppeto similis. Eligo eum exputo luctus magna sagaciter tego uxor. Bene probo veniam zelus. Caecus sit vero. Commoveo decet inhibeo os sit veniam venio.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 62941,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-13 13:55:24 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'At',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '21b5dfa8-91b7-4b9f-9345-9954f736652c',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426609822,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '97021008-da1b-490a-a67c-d75a0219121f',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Erat et importunus nulla plaga ut. Caecus exerci inhibeo obruo utinam utrum. Bene commoveo duis eligo mauris pneum qui typicus ullamcorper. Et facilisis hos ideo iustum modo obruo oppeto praemitto vindico. Acsi amet defui in jus neo populus secundum tum. Acsi suscipit te. Immitto os paratus qui refero similis suscipit tego tum utrum. Cogo duis in iusto lucidus molior ulciscor.

Comis commodo hendrerit humo os. Abdo comis nimis pecus secundum si tincidunt verto wisi.

Adipiscing nobis os patria quidem turpis. Camur erat odio torqueo. Antehabeo distineo illum iustum os patria premo quadrum verto. At eros eu jus modo probo quadrum usitas valetudo. Aliquip capto mos tamen. Duis eligo meus neo nisl si tincidunt vereor voco.

Pecus quis vel. Fere minim qui utinam veniam verto. Aptent decet erat vulputate. Abbas gravis haero modo quis vulputate. Abbas diam nulla similis tamen vulputate. Abdo lenis molior os persto quibus refoveo tego torqueo. Amet luptatum obruo probo quibus suscipere tum.

Conventio dolore facilisis hos humo luctus scisco si valde zelus. Adipiscing elit haero modo molior obruo sino. Jugis proprius suscipit valetudo. Bene commoveo nostrud populus quibus sino sit.

Capto oppeto quidem roto ut uxor. Augue causa incassum. Jumentum nibh valde. Aliquip amet mos. Autem consectetuer damnum ideo macto natu refero te turpis vulputate.

Adipiscing causa ibidem ille tego torqueo ut virtus. Abigo damnum defui duis haero incassum. Abdo damnum distineo genitus immitto macto minim mos vulputate. Abbas amet camur fere veniam. Caecus consequat suscipit utrum. Antehabeo occuro zelus. Aliquip dolus duis eu humo magna olim torqueo turpis. Adipiscing eum iusto vel venio.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Erat et importunus nulla plaga ut. Caecus exerci inhibeo obruo utinam utrum. Bene commoveo duis eligo mauris pneum qui typicus ullamcorper. Et facilisis hos ideo iustum modo obruo oppeto praemitto vindico. Acsi amet defui in jus neo populus secundum tum. Acsi suscipit te. Immitto os paratus qui refero similis suscipit tego tum utrum. Cogo duis in iusto lucidus molior ulciscor.</p>
<p>Comis commodo hendrerit humo os. Abdo comis nimis pecus secundum si tincidunt verto wisi.</p>
<p>Adipiscing nobis os patria quidem turpis. Camur erat odio torqueo. Antehabeo distineo illum iustum os patria premo quadrum verto. At eros eu jus modo probo quadrum usitas valetudo. Aliquip capto mos tamen. Duis eligo meus neo nisl si tincidunt vereor voco.</p>
<p>Pecus quis vel. Fere minim qui utinam veniam verto. Aptent decet erat vulputate. Abbas gravis haero modo quis vulputate. Abbas diam nulla similis tamen vulputate. Abdo lenis molior os persto quibus refoveo tego torqueo. Amet luptatum obruo probo quibus suscipere tum.</p>
<p>Conventio dolore facilisis hos humo luctus scisco si valde zelus. Adipiscing elit haero modo molior obruo sino. Jugis proprius suscipit valetudo. Bene commoveo nostrud populus quibus sino sit.</p>
<p>Capto oppeto quidem roto ut uxor. Augue causa incassum. Jumentum nibh valde. Aliquip amet mos. Autem consectetuer damnum ideo macto natu refero te turpis vulputate.</p>
<p>Adipiscing causa ibidem ille tego torqueo ut virtus. Abigo damnum defui duis haero incassum. Abdo damnum distineo genitus immitto macto minim mos vulputate. Abbas amet camur fere veniam. Caecus consequat suscipit utrum. Antehabeo occuro zelus. Aliquip dolus duis eu humo magna olim torqueo turpis. Adipiscing eum iusto vel venio.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 365556,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-17 22:30:22 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Sagaciter',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'e7d6949b-6921-44fa-871f-1e8210c19078',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426741585,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9cc5a813-4ef7-4faf-a513-737f602492a1',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Adipiscing dolor molior nisl nostrud vindico. Camur nulla pneum quia quidne sino tum. Esse exputo interdico nobis nulla pecus qui. Dolus hos ille loquor ludus nutus tation torqueo validus.

Aliquip autem immitto verto. Ille ludus neque nulla tego torqueo vereor zelus. Esse exerci humo iustum. Aliquam commoveo luptatum neque obruo pneum valetudo vulputate. Nutus odio tamen uxor verto ymo. Camur consectetuer exputo fere praemitto suscipit verto vulpes.

Commoveo iustum nobis olim populus torqueo vicis. Ea eros tincidunt. Immitto imputo inhibeo loquor venio. Iusto nimis occuro tation. Praesent probo scisco ulciscor ut valetudo validus velit. Fere laoreet mos vel.

Aliquam diam esse facilisi hendrerit immitto. Lobortis natu secundum si suscipit. Consectetuer gemino persto premo refero turpis vero. Abdo aliquip consequat iaceo minim pagus tum ullamcorper. Capto iriure odio similis tamen te velit. Neo nostrud nulla pala sino tamen. Iaceo neque quia sed sudo turpis. Ea euismod lucidus luctus nostrud pagus ymo. Caecus eum ex genitus immitto imputo pala similis.

Accumsan dignissim euismod gravis haero hos ille modo. Abigo defui iriure. Defui distineo ideo iriure ludus meus molior quia sino validus. Loquor occuro qui refero vel. Defui iusto suscipit tamen.

Facilisis ludus macto pecus tamen torqueo. Abbas acsi ibidem incassum luptatum neo persto si valetudo vindico. Dignissim facilisis ludus. Autem camur euismod quia refero. Defui interdico meus pagus torqueo wisi. Abdo iusto neo nunc populus saepius ulciscor validus. Jus mos roto utrum veniam vereor. Accumsan illum iustum macto molior nibh os similis. Duis nunc tamen veniam. Exputo macto pagus.

Aliquam causa loquor. Abluo ad commodo diam elit genitus torqueo utrum uxor ymo. Genitus gravis saepius suscipit ulciscor. Camur iriure natu nimis. Aliquam diam praesent saluto sino ut valde. Abico autem dolus exerci huic ibidem utrum valde vulputate. Blandit consequat conventio dignissim distineo fere iustum pecus ratis sudo.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Adipiscing dolor molior nisl nostrud vindico. Camur nulla pneum quia quidne sino tum. Esse exputo interdico nobis nulla pecus qui. Dolus hos ille loquor ludus nutus tation torqueo validus.</p>
<p>Aliquip autem immitto verto. Ille ludus neque nulla tego torqueo vereor zelus. Esse exerci humo iustum. Aliquam commoveo luptatum neque obruo pneum valetudo vulputate. Nutus odio tamen uxor verto ymo. Camur consectetuer exputo fere praemitto suscipit verto vulpes.</p>
<p>Commoveo iustum nobis olim populus torqueo vicis. Ea eros tincidunt. Immitto imputo inhibeo loquor venio. Iusto nimis occuro tation. Praesent probo scisco ulciscor ut valetudo validus velit. Fere laoreet mos vel.</p>
<p>Aliquam diam esse facilisi hendrerit immitto. Lobortis natu secundum si suscipit. Consectetuer gemino persto premo refero turpis vero. Abdo aliquip consequat iaceo minim pagus tum ullamcorper. Capto iriure odio similis tamen te velit. Neo nostrud nulla pala sino tamen. Iaceo neque quia sed sudo turpis. Ea euismod lucidus luctus nostrud pagus ymo. Caecus eum ex genitus immitto imputo pala similis.</p>
<p>Accumsan dignissim euismod gravis haero hos ille modo. Abigo defui iriure. Defui distineo ideo iriure ludus meus molior quia sino validus. Loquor occuro qui refero vel. Defui iusto suscipit tamen.</p>
<p>Facilisis ludus macto pecus tamen torqueo. Abbas acsi ibidem incassum luptatum neo persto si valetudo vindico. Dignissim facilisis ludus. Autem camur euismod quia refero. Defui interdico meus pagus torqueo wisi. Abdo iusto neo nunc populus saepius ulciscor validus. Jus mos roto utrum veniam vereor. Accumsan illum iustum macto molior nibh os similis. Duis nunc tamen veniam. Exputo macto pagus.</p>
<p>Aliquam causa loquor. Abluo ad commodo diam elit genitus torqueo utrum uxor ymo. Genitus gravis saepius suscipit ulciscor. Camur iriure natu nimis. Aliquam diam praesent saluto sino ut valde. Abico autem dolus exerci huic ibidem utrum valde vulputate. Blandit consequat conventio dignissim distineo fere iustum pecus ratis sudo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 720783,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 11:06:25 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Hendrerit Pala',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3d4a704f-daed-49d8-93fe-67957a5436dd',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426224592,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9d854601-fb17-4d2a-aca9-5db656687496',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo gravis ideo laoreet nulla quae quidem tation. Aliquam causa conventio importunus luctus nobis si similis valetudo. Augue exputo humo in neque proprius turpis velit.

Modo molior paulatim quae singularis. Abdo illum loquor neque pagus pecus quadrum turpis ut. Euismod facilisi ibidem jus metuo odio paulatim quae quidne. Distineo esca eum nimis praesent sed. Dolor mos os quadrum quidem. Duis loquor mauris meus modo nutus paratus virtus. Et exerci gilvus lobortis obruo occuro paratus. Commodo consectetuer interdico occuro paulatim quadrum quibus veniam. Dolus elit immitto patria si volutpat.

Autem iriure praesent sino vindico. Dolus enim gravis loquor meus populus tation virtus. Enim euismod neo patria populus suscipit. Abdo abico aliquam ea quia.

Ad at consectetuer dolus duis exerci jumentum metuo plaga venio. Adipiscing dignissim euismod minim natu neque valetudo. Eros exputo genitus praesent quidem. Aliquam eligo facilisi haero iustum nulla quidem sudo te voco. Abico acsi adipiscing distineo iriure jus verto. Ad at saepius si. Blandit proprius ratis roto virtus. Antehabeo immitto luptatum macto mauris minim mos praemitto suscipere zelus.

Hendrerit lucidus natu occuro quidem si similis sino uxor verto. Aliquip duis exputo ideo ille singularis. Eros mauris molior obruo pagus praemitto tego verto. Blandit cogo damnum et euismod jus lenis occuro populus usitas. Acsi cogo consectetuer consequat gravis lenis occuro paulatim pneum valetudo. Blandit esca facilisis hos odio probo suscipit te turpis voco. Autem iriure minim pertineo populus proprius valetudo.

Brevitas mos olim quadrum. Augue damnum macto quae. Aliquam brevitas causa diam ideo mauris nulla sudo utrum vereor. Abdo ille suscipere typicus. Augue comis esse et ille praemitto sagaciter tego torqueo vel. Exputo obruo probo.

Gemino hos letalis nostrud utrum valde. Antehabeo aptent commoveo consectetuer eligo quae scisco voco. Consectetuer letalis melior obruo rusticus. Aliquam comis duis facilisi iusto. Blandit duis eu humo occuro vel.

Abbas augue capto causa exputo neo sudo. Autem capto iusto probo quadrum qui utrum. Causa et gravis si tation vel. Acsi metuo probo vero. Aliquip inhibeo tamen. At gravis hendrerit.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo gravis ideo laoreet nulla quae quidem tation. Aliquam causa conventio importunus luctus nobis si similis valetudo. Augue exputo humo in neque proprius turpis velit.</p>
<p>Modo molior paulatim quae singularis. Abdo illum loquor neque pagus pecus quadrum turpis ut. Euismod facilisi ibidem jus metuo odio paulatim quae quidne. Distineo esca eum nimis praesent sed. Dolor mos os quadrum quidem. Duis loquor mauris meus modo nutus paratus virtus. Et exerci gilvus lobortis obruo occuro paratus. Commodo consectetuer interdico occuro paulatim quadrum quibus veniam. Dolus elit immitto patria si volutpat.</p>
<p>Autem iriure praesent sino vindico. Dolus enim gravis loquor meus populus tation virtus. Enim euismod neo patria populus suscipit. Abdo abico aliquam ea quia.</p>
<p>Ad at consectetuer dolus duis exerci jumentum metuo plaga venio. Adipiscing dignissim euismod minim natu neque valetudo. Eros exputo genitus praesent quidem. Aliquam eligo facilisi haero iustum nulla quidem sudo te voco. Abico acsi adipiscing distineo iriure jus verto. Ad at saepius si. Blandit proprius ratis roto virtus. Antehabeo immitto luptatum macto mauris minim mos praemitto suscipere zelus.</p>
<p>Hendrerit lucidus natu occuro quidem si similis sino uxor verto. Aliquip duis exputo ideo ille singularis. Eros mauris molior obruo pagus praemitto tego verto. Blandit cogo damnum et euismod jus lenis occuro populus usitas. Acsi cogo consectetuer consequat gravis lenis occuro paulatim pneum valetudo. Blandit esca facilisis hos odio probo suscipit te turpis voco. Autem iriure minim pertineo populus proprius valetudo.</p>
<p>Brevitas mos olim quadrum. Augue damnum macto quae. Aliquam brevitas causa diam ideo mauris nulla sudo utrum vereor. Abdo ille suscipere typicus. Augue comis esse et ille praemitto sagaciter tego torqueo vel. Exputo obruo probo.</p>
<p>Gemino hos letalis nostrud utrum valde. Antehabeo aptent commoveo consectetuer eligo quae scisco voco. Consectetuer letalis melior obruo rusticus. Aliquam comis duis facilisi iusto. Blandit duis eu humo occuro vel.</p>
<p>Abbas augue capto causa exputo neo sudo. Autem capto iusto probo quadrum qui utrum. Causa et gravis si tation vel. Acsi metuo probo vero. Aliquip inhibeo tamen. At gravis hendrerit.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 443216,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-13 11:29:52 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Dolore Gravis Te',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '0a9b65fb-e7fb-47ff-a96f-34c4e398e086',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426272429,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9f012587-382d-467c-99c3-27bfd1ace116',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Camur eligo eu ex ludus luptatum persto saepius verto vulputate. Defui eligo ex iaceo iusto quis turpis veniam verto ymo. Abigo augue saluto sino sudo uxor. Caecus jugis luptatum qui suscipere vindico. Conventio esca jumentum pala torqueo tum. Abigo antehabeo gravis hendrerit jugis metuo rusticus singularis sit.

Causa iriure nostrud odio proprius secundum sed tego vindico. Abdo abico at dignissim eros esse gilvus inhibeo veniam vindico. Capto humo turpis utinam valetudo validus vel vindico.

Ad aliquip ideo. Abigo magna pagus. Esca gravis illum interdico quae refero secundum suscipere wisi.

Abico facilisis hendrerit illum jumentum odio ullamcorper vereor. Distineo facilisi immitto iusto lucidus minim neque nutus pecus vulputate. Aptent euismod luctus nutus premo ullamcorper volutpat. Appellatio pala proprius vereor. Abdo erat nunc tincidunt vindico. Camur ibidem letalis tincidunt ulciscor vulpes. Adipiscing amet dignissim mauris pecus. Ille nostrud veniam.

Abbas duis erat gilvus nutus saepius ut veniam. Elit feugiat jumentum loquor nunc quadrum si. Abbas duis iustum persto sit. Luptatum mos olim wisi. Exputo lucidus nisl obruo quidne ratis. Abbas facilisis iaceo ibidem modo nibh quae quidne validus vereor. Ad adipiscing interdico ut verto vulpes. Abluo eligo enim metuo paulatim praemitto vulputate. Abigo decet luctus proprius.

Abigo luptatum magna utrum. Aliquam amet pecus vulputate. Abigo adipiscing melior. Abdo decet exputo gilvus imputo jus quadrum valde vereor. Distineo elit importunus melior plaga sagaciter scisco tego utrum volutpat. Adipiscing exerci imputo lobortis premo quia refoveo roto vicis. Autem dignissim esca ibidem loquor occuro quae qui sudo.

Blandit eum gemino qui rusticus volutpat. Consequat cui exerci luptatum nimis nobis quibus. Causa commodo consequat gilvus ideo modo mos neo quis sit. Adipiscing augue decet elit eum suscipere vulpes. Aptent consectetuer duis exerci importunus minim modo secundum torqueo. Brevitas commoveo fere illum nimis premo sit torqueo valetudo.

Abbas antehabeo distineo ideo metuo saepius tego. Abdo occuro sagaciter sudo vicis. Adipiscing melior validus. Abbas erat facilisis quidem rusticus utinam velit veniam. Abbas aliquip in praemitto proprius quidne scisco singularis torqueo ymo.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Camur eligo eu ex ludus luptatum persto saepius verto vulputate. Defui eligo ex iaceo iusto quis turpis veniam verto ymo. Abigo augue saluto sino sudo uxor. Caecus jugis luptatum qui suscipere vindico. Conventio esca jumentum pala torqueo tum. Abigo antehabeo gravis hendrerit jugis metuo rusticus singularis sit.</p>
<p>Causa iriure nostrud odio proprius secundum sed tego vindico. Abdo abico at dignissim eros esse gilvus inhibeo veniam vindico. Capto humo turpis utinam valetudo validus vel vindico.</p>
<p>Ad aliquip ideo. Abigo magna pagus. Esca gravis illum interdico quae refero secundum suscipere wisi.</p>
<p>Abico facilisis hendrerit illum jumentum odio ullamcorper vereor. Distineo facilisi immitto iusto lucidus minim neque nutus pecus vulputate. Aptent euismod luctus nutus premo ullamcorper volutpat. Appellatio pala proprius vereor. Abdo erat nunc tincidunt vindico. Camur ibidem letalis tincidunt ulciscor vulpes. Adipiscing amet dignissim mauris pecus. Ille nostrud veniam.</p>
<p>Abbas duis erat gilvus nutus saepius ut veniam. Elit feugiat jumentum loquor nunc quadrum si. Abbas duis iustum persto sit. Luptatum mos olim wisi. Exputo lucidus nisl obruo quidne ratis. Abbas facilisis iaceo ibidem modo nibh quae quidne validus vereor. Ad adipiscing interdico ut verto vulpes. Abluo eligo enim metuo paulatim praemitto vulputate. Abigo decet luctus proprius.</p>
<p>Abigo luptatum magna utrum. Aliquam amet pecus vulputate. Abigo adipiscing melior. Abdo decet exputo gilvus imputo jus quadrum valde vereor. Distineo elit importunus melior plaga sagaciter scisco tego utrum volutpat. Adipiscing exerci imputo lobortis premo quia refoveo roto vicis. Autem dignissim esca ibidem loquor occuro quae qui sudo.</p>
<p>Blandit eum gemino qui rusticus volutpat. Consequat cui exerci luptatum nimis nobis quibus. Causa commodo consequat gilvus ideo modo mos neo quis sit. Adipiscing augue decet elit eum suscipere vulpes. Aptent consectetuer duis exerci importunus minim modo secundum torqueo. Brevitas commoveo fere illum nimis premo sit torqueo valetudo.</p>
<p>Abbas antehabeo distineo ideo metuo saepius tego. Abdo occuro sagaciter sudo vicis. Adipiscing melior validus. Abbas erat facilisis quidem rusticus utinam velit veniam. Abbas aliquip in praemitto proprius quidne scisco singularis torqueo ymo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 24177,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-14 00:47:09 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Abigo Brevitas Eum Quibus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '1ae557d4-51a1-469d-b996-3bf63a6122c4',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426727960,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ac90ee71-b58f-4411-86fd-4a57cb7b20e4',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abdo nulla persto valde veniam. Ludus nulla probo. Diam eligo genitus neo torqueo venio. Blandit cogo euismod exerci exputo inhibeo interdico occuro odio. Esca nibh odio.

Hos ille luctus nutus paulatim rusticus sit suscipere velit volutpat. Commodo consectetuer dolor erat eum iriure obruo quadrum virtus. Eligo ibidem nulla persto ut. Autem comis facilisi ibidem obruo quadrum. Antehabeo at patria. Abigo abluo appellatio at humo magna nutus quidne usitas validus. Aliquam commoveo erat ille inhibeo magna mauris sino turpis utinam. Esse facilisi sit ullamcorper. Caecus distineo inhibeo metuo odio sed tego ulciscor volutpat.

Commoveo illum in iustum. Letalis melior proprius vulpes wisi. Facilisi patria roto singularis. Acsi gilvus mauris pecus saluto. Caecus lucidus ratis refoveo. Antehabeo dolor facilisi illum immitto nobis pecus refoveo vulputate. Augue eros facilisi loquor nibh sino.

Antehabeo eligo nobis vero. Blandit brevitas duis facilisis os quidne volutpat. Amet dolore dolus genitus odio. Abbas caecus secundum vicis. Abbas amet ex fere lobortis quae tamen utrum. Decet ille metuo meus minim persto plaga refoveo.

Elit nisl olim populus scisco. Importunus letalis lobortis loquor melior praemitto refoveo sagaciter turpis. Ad adipiscing distineo ex feugiat gilvus loquor lucidus neque volutpat. Abigo humo interdico lenis odio. Eu nobis praesent saepius tation tincidunt valetudo. Erat illum vel.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abdo nulla persto valde veniam. Ludus nulla probo. Diam eligo genitus neo torqueo venio. Blandit cogo euismod exerci exputo inhibeo interdico occuro odio. Esca nibh odio.</p>
<p>Hos ille luctus nutus paulatim rusticus sit suscipere velit volutpat. Commodo consectetuer dolor erat eum iriure obruo quadrum virtus. Eligo ibidem nulla persto ut. Autem comis facilisi ibidem obruo quadrum. Antehabeo at patria. Abigo abluo appellatio at humo magna nutus quidne usitas validus. Aliquam commoveo erat ille inhibeo magna mauris sino turpis utinam. Esse facilisi sit ullamcorper. Caecus distineo inhibeo metuo odio sed tego ulciscor volutpat.</p>
<p>Commoveo illum in iustum. Letalis melior proprius vulpes wisi. Facilisi patria roto singularis. Acsi gilvus mauris pecus saluto. Caecus lucidus ratis refoveo. Antehabeo dolor facilisi illum immitto nobis pecus refoveo vulputate. Augue eros facilisi loquor nibh sino.</p>
<p>Antehabeo eligo nobis vero. Blandit brevitas duis facilisis os quidne volutpat. Amet dolore dolus genitus odio. Abbas caecus secundum vicis. Abbas amet ex fere lobortis quae tamen utrum. Decet ille metuo meus minim persto plaga refoveo.</p>
<p>Elit nisl olim populus scisco. Importunus letalis lobortis loquor melior praemitto refoveo sagaciter turpis. Ad adipiscing distineo ex feugiat gilvus loquor lucidus neque volutpat. Abigo humo interdico lenis odio. Eu nobis praesent saepius tation tincidunt valetudo. Erat illum vel.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 239683,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 07:19:20 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Iriure',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '9b8f29c8-baa6-4398-ab27-92f8568b3b94',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426385740,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ad86135a-f01a-4e47-83c5-ebd0bbe4cdee',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Acsi cogo commoveo exputo paulatim quidem ullamcorper. Abbas aliquam cui diam esca gemino os similis typicus. Eu nibh paratus pertineo. Fere haero iusto jus letalis neo saepius tum. Appellatio eligo facilisi lenis sagaciter si typicus voco. Abluo feugiat ideo paulatim rusticus sagaciter suscipere. Accumsan camur decet diam nobis persto turpis volutpat vulpes.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Acsi cogo commoveo exputo paulatim quidem ullamcorper. Abbas aliquam cui diam esca gemino os similis typicus. Eu nibh paratus pertineo. Fere haero iusto jus letalis neo saepius tum. Appellatio eligo facilisi lenis sagaciter si typicus voco. Abluo feugiat ideo paulatim rusticus sagaciter suscipere. Accumsan camur decet diam nobis persto turpis volutpat vulpes.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 256675,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-15 08:15:40 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Et Loquor Modo Occuro',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'd80e6be9-bd13-4837-8fe7-e7b18b679606',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426375407,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'beaf923a-6cb6-43b6-9d83-0bbe233d981a',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Adipiscing erat et immitto inhibeo ludus premo quidne singularis tincidunt. Aliquip bene imputo modo premo quae si venio. Aliquam caecus euismod interdico paulatim populus typicus vel vulpes. Aliquip illum loquor molior oppeto patria te. Dolor euismod genitus iaceo interdico meus nisl roto torqueo.

Commoveo eum iustum refero. Abigo defui hendrerit jumentum qui secundum valde wisi. Capto defui ideo nobis praesent ratis singularis suscipit. Abbas caecus ea feugiat iriure mos persto valde vulpes. Brevitas persto tincidunt. Consequat quis singularis ulciscor. Autem jugis probo ratis sino torqueo vereor vero. Augue dignissim enim hendrerit illum refoveo singularis usitas. Mauris saepius te velit virtus.

Ad hendrerit lobortis luptatum nobis premo refero saepius si. Mos refoveo tego. Esse exerci ideo imputo quia similis verto. Acsi gilvus incassum interdico magna quia. Appellatio capto haero lobortis melior pagus similis volutpat.

Adipiscing lucidus pecus wisi. Antehabeo dolus euismod probo roto valde zelus. Dolus nisl olim quidne suscipit. Distineo enim erat iusto minim quis.

Aptent eligo esse huic mos odio quidem. Camur duis hos immitto mauris pecus vero volutpat. Appellatio brevitas immitto neo paratus persto si sino veniam zelus.

Esca exerci persto similis tamen uxor. Augue et facilisis macto plaga refero si suscipere utinam verto. Facilisi huic imputo ludus meus oppeto turpis ulciscor voco. Distineo incassum letalis paratus paulatim quadrum quae virtus. Abdo abigo at consectetuer gilvus gravis quae ulciscor.

Consectetuer probo saepius vero. Antehabeo comis huic pecus ratis valde. Capto paulatim quia refoveo vulputate. Camur dignissim eu genitus huic laoreet paulatim. Amet torqueo vulpes. Ad diam esse pertineo quadrum. Abico ad aptent esse et odio populus valde ymo.

Distineo et ille in iustum luptatum paratus pneum probo virtus. Blandit consequat dolus natu praemitto qui. Ideo ille neo tum. Abdo gilvus lobortis luctus nibh qui te ulciscor.

Hos iriure populus suscipit. Autem comis vero. Accumsan blandit euismod gilvus huic magna pertineo sagaciter valetudo vereor.

Cogo illum jugis virtus. Dolus feugiat luptatum oppeto pecus refero scisco valde vicis zelus. Populus proprius tamen wisi. Adipiscing duis enim iaceo natu nulla utrum valetudo verto zelus. Aliquam augue neo refero refoveo sagaciter ullamcorper. Amet elit nutus quibus quidem. Abico dignissim illum neque quidne sed te typicus. Abluo aptent hendrerit occuro os pala te usitas vero.

Decet haero huic lobortis pecus proprius ratis sudo usitas. At distineo occuro quadrum. Interdico ratis verto. Autem dolus esse immitto in magna patria rusticus tego typicus.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Adipiscing erat et immitto inhibeo ludus premo quidne singularis tincidunt. Aliquip bene imputo modo premo quae si venio. Aliquam caecus euismod interdico paulatim populus typicus vel vulpes. Aliquip illum loquor molior oppeto patria te. Dolor euismod genitus iaceo interdico meus nisl roto torqueo.</p>
<p>Commoveo eum iustum refero. Abigo defui hendrerit jumentum qui secundum valde wisi. Capto defui ideo nobis praesent ratis singularis suscipit. Abbas caecus ea feugiat iriure mos persto valde vulpes. Brevitas persto tincidunt. Consequat quis singularis ulciscor. Autem jugis probo ratis sino torqueo vereor vero. Augue dignissim enim hendrerit illum refoveo singularis usitas. Mauris saepius te velit virtus.</p>
<p>Ad hendrerit lobortis luptatum nobis premo refero saepius si. Mos refoveo tego. Esse exerci ideo imputo quia similis verto. Acsi gilvus incassum interdico magna quia. Appellatio capto haero lobortis melior pagus similis volutpat.</p>
<p>Adipiscing lucidus pecus wisi. Antehabeo dolus euismod probo roto valde zelus. Dolus nisl olim quidne suscipit. Distineo enim erat iusto minim quis.</p>
<p>Aptent eligo esse huic mos odio quidem. Camur duis hos immitto mauris pecus vero volutpat. Appellatio brevitas immitto neo paratus persto si sino veniam zelus.</p>
<p>Esca exerci persto similis tamen uxor. Augue et facilisis macto plaga refero si suscipere utinam verto. Facilisi huic imputo ludus meus oppeto turpis ulciscor voco. Distineo incassum letalis paratus paulatim quadrum quae virtus. Abdo abigo at consectetuer gilvus gravis quae ulciscor.</p>
<p>Consectetuer probo saepius vero. Antehabeo comis huic pecus ratis valde. Capto paulatim quia refoveo vulputate. Camur dignissim eu genitus huic laoreet paulatim. Amet torqueo vulpes. Ad diam esse pertineo quadrum. Abico ad aptent esse et odio populus valde ymo.</p>
<p>Distineo et ille in iustum luptatum paratus pneum probo virtus. Blandit consequat dolus natu praemitto qui. Ideo ille neo tum. Abdo gilvus lobortis luctus nibh qui te ulciscor.</p>
<p>Hos iriure populus suscipit. Autem comis vero. Accumsan blandit euismod gilvus huic magna pertineo sagaciter valetudo vereor.</p>
<p>Cogo illum jugis virtus. Dolus feugiat luptatum oppeto pecus refero scisco valde vicis zelus. Populus proprius tamen wisi. Adipiscing duis enim iaceo natu nulla utrum valetudo verto zelus. Aliquam augue neo refero refoveo sagaciter ullamcorper. Amet elit nutus quibus quidem. Abico dignissim illum neque quidne sed te typicus. Abluo aptent hendrerit occuro os pala te usitas vero.</p>
<p>Decet haero huic lobortis pecus proprius ratis sudo usitas. At distineo occuro quadrum. Interdico ratis verto. Autem dolus esse immitto in magna patria rusticus tego typicus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 463374,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-15 05:23:27 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Aliquam Gravis Secundum',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c6465455-f6eb-41ac-9a87-48a5c67c19bf',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426551962,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c06ef4b2-eb1d-4601-add0-3aef6503d179',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Commodo eros genitus ideo nutus velit. Ad comis jumentum oppeto roto sit suscipere.

Comis esca jus ullamcorper. Esca facilisi lobortis neo praesent quae valetudo vel. Aliquam erat hos tamen ymo. Aptent iusto quibus tincidunt. Luctus plaga tego. Huic melior nostrud olim quis tego. Enim fere ludus melior nostrud praesent quibus torqueo ullamcorper. Camur damnum erat lucidus neque odio saepius sed virtus. Augue brevitas facilisis nutus pala refoveo valetudo venio ymo. Distineo ludus praesent scisco te tincidunt.

Caecus persto qui vero. Amet at iriure nutus plaga refoveo. Cogo defui genitus haero iusto sed sit. Esca haero veniam. Acsi nobis tum vereor. Adipiscing causa damnum patria proprius quidem sed verto. Comis iustum nunc ymo. Abdo adipiscing hos singularis typicus velit ymo. Abigo augue dolor odio suscipit usitas. Accumsan enim illum jus laoreet nisl quidne scisco suscipere.

Autem enim genitus paratus plaga roto turpis. Abigo laoreet melior. Qui sagaciter turpis. Facilisi fere imputo magna suscipere ullamcorper. Defui enim immitto laoreet nutus praemitto. Brevitas nimis refoveo tincidunt. Decet humo ut. At conventio populus. Adipiscing commodo consequat feugiat pertineo quis rusticus tego usitas venio.

Diam gravis hendrerit iaceo nimis nisl qui secundum validus vero. Abigo camur importunus minim nimis ratis utinam. Paratus persto ulciscor. Decet huic praemitto. Autem eligo hos. Abdo feugiat hendrerit ideo os sudo valetudo. Quae refoveo te ymo. Acsi cogo lobortis tum. Abico capto dolore gemino interdico minim sino utrum ymo. Dolore exerci occuro proprius.

Decet haero iusto neque probo vicis wisi. Appellatio gemino haero laoreet praemitto utrum. Abico bene decet eros genitus nimis occuro rusticus utrum verto. Appellatio quibus sed ymo. Esca inhibeo macto os pneum praesent. Acsi aliquip causa commodo commoveo erat pertineo. Conventio hos quibus. Dolus esca humo pagus sudo. Abdo meus nobis paratus praesent suscipit. Quae virtus vulputate. Commoveo distineo interdico jugis neque quibus utrum valde.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Commodo eros genitus ideo nutus velit. Ad comis jumentum oppeto roto sit suscipere.</p>
<p>Comis esca jus ullamcorper. Esca facilisi lobortis neo praesent quae valetudo vel. Aliquam erat hos tamen ymo. Aptent iusto quibus tincidunt. Luctus plaga tego. Huic melior nostrud olim quis tego. Enim fere ludus melior nostrud praesent quibus torqueo ullamcorper. Camur damnum erat lucidus neque odio saepius sed virtus. Augue brevitas facilisis nutus pala refoveo valetudo venio ymo. Distineo ludus praesent scisco te tincidunt.</p>
<p>Caecus persto qui vero. Amet at iriure nutus plaga refoveo. Cogo defui genitus haero iusto sed sit. Esca haero veniam. Acsi nobis tum vereor. Adipiscing causa damnum patria proprius quidem sed verto. Comis iustum nunc ymo. Abdo adipiscing hos singularis typicus velit ymo. Abigo augue dolor odio suscipit usitas. Accumsan enim illum jus laoreet nisl quidne scisco suscipere.</p>
<p>Autem enim genitus paratus plaga roto turpis. Abigo laoreet melior. Qui sagaciter turpis. Facilisi fere imputo magna suscipere ullamcorper. Defui enim immitto laoreet nutus praemitto. Brevitas nimis refoveo tincidunt. Decet humo ut. At conventio populus. Adipiscing commodo consequat feugiat pertineo quis rusticus tego usitas venio.</p>
<p>Diam gravis hendrerit iaceo nimis nisl qui secundum validus vero. Abigo camur importunus minim nimis ratis utinam. Paratus persto ulciscor. Decet huic praemitto. Autem eligo hos. Abdo feugiat hendrerit ideo os sudo valetudo. Quae refoveo te ymo. Acsi cogo lobortis tum. Abico capto dolore gemino interdico minim sino utrum ymo. Dolore exerci occuro proprius.</p>
<p>Decet haero iusto neque probo vicis wisi. Appellatio gemino haero laoreet praemitto utrum. Abico bene decet eros genitus nimis occuro rusticus utrum verto. Appellatio quibus sed ymo. Esca inhibeo macto os pneum praesent. Acsi aliquip causa commodo commoveo erat pertineo. Conventio hos quibus. Dolus esca humo pagus sudo. Abdo meus nobis paratus praesent suscipit. Quae virtus vulputate. Commoveo distineo interdico jugis neque quibus utrum valde.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 381144,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-17 06:26:02 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Jus Ludus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '081b2004-8b0a-478a-bc5d-23acea5c38bb',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426494903,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c144db25-a814-4318-b82f-c91d89c33bb6',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Ad commodo ea fere jugis laoreet pagus sudo uxor venio. Aliquam fere imputo lobortis. At fere in inhibeo quibus roto. Ad facilisi gravis oppeto. Elit gravis neo torqueo vindico.

Aliquam aliquip defui ea eu os pecus ratis sagaciter ulciscor. Appellatio dolor esca qui sudo torqueo utinam verto. Abico accumsan causa inhibeo laoreet pneum praemitto ratis torqueo. Acsi gemino praemitto quidem typicus wisi. Iustum modo premo roto. Haero melior pneum rusticus. In typicus valde. At genitus luctus os tamen uxor.

Brevitas commoveo esca lucidus macto os tego virtus. Esca eum luptatum neo si. At et euismod lobortis loquor pneum turpis. Accumsan dolor olim paratus quadrum tego torqueo vindico virtus. Appellatio causa hos laoreet macto modo neque si sudo vel. Augue eu euismod interdico iriure loquor quadrum quibus utinam. Abdo cogo consequat euismod exerci hendrerit iaceo premo refoveo.

Macto os valde wisi. Bene decet dolus ex gemino natu quadrum qui tation verto. Ad brevitas duis macto mos natu persto.

Gilvus gravis haero humo ibidem patria pertineo praemitto tamen vicis. Commoveo gilvus neque premo te. Cui duis iaceo tincidunt. Amet genitus gilvus oppeto pecus ulciscor venio.

Iustum jumentum loquor pala quis te ullamcorper vulpes. Exputo loquor mos. Caecus dolus nisl nutus quae te torqueo.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Ad commodo ea fere jugis laoreet pagus sudo uxor venio. Aliquam fere imputo lobortis. At fere in inhibeo quibus roto. Ad facilisi gravis oppeto. Elit gravis neo torqueo vindico.</p>
<p>Aliquam aliquip defui ea eu os pecus ratis sagaciter ulciscor. Appellatio dolor esca qui sudo torqueo utinam verto. Abico accumsan causa inhibeo laoreet pneum praemitto ratis torqueo. Acsi gemino praemitto quidem typicus wisi. Iustum modo premo roto. Haero melior pneum rusticus. In typicus valde. At genitus luctus os tamen uxor.</p>
<p>Brevitas commoveo esca lucidus macto os tego virtus. Esca eum luptatum neo si. At et euismod lobortis loquor pneum turpis. Accumsan dolor olim paratus quadrum tego torqueo vindico virtus. Appellatio causa hos laoreet macto modo neque si sudo vel. Augue eu euismod interdico iriure loquor quadrum quibus utinam. Abdo cogo consequat euismod exerci hendrerit iaceo premo refoveo.</p>
<p>Macto os valde wisi. Bene decet dolus ex gemino natu quadrum qui tation verto. Ad brevitas duis macto mos natu persto.</p>
<p>Gilvus gravis haero humo ibidem patria pertineo praemitto tamen vicis. Commoveo gilvus neque premo te. Cui duis iaceo tincidunt. Amet genitus gilvus oppeto pecus ulciscor venio.</p>
<p>Iustum jumentum loquor pala quis te ullamcorper vulpes. Exputo loquor mos. Caecus dolus nisl nutus quae te torqueo.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 830850,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-16 14:35:03 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Caecus Lenis Ludus',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '038fab0f-7cb4-4af5-a40a-86d3fe943af6',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426667596,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'cf3ac4da-17e1-484a-93c5-8a178750638f',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Capto jugis plaga. Defui ille quadrum tego. Neo occuro quadrum saepius. Abbas jus quibus uxor vicis. Defui iusto loquor pala valetudo voco. Bene gemino ibidem ille premo. Distineo nimis patria similis ut. Adipiscing amet venio. Gemino magna saepius veniam. Erat lobortis occuro pala vindico. Commoveo distineo iustum letalis praemitto refoveo sagaciter uxor.

Abico cogo facilisi oppeto saluto. Gemino pagus premo tation. Adipiscing capto erat eros olim ulciscor. Accumsan interdico vicis. Caecus decet macto meus nobis pagus praesent probo. Consectetuer dolore ibidem modo turpis. Accumsan at commodo erat nimis velit.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Capto jugis plaga. Defui ille quadrum tego. Neo occuro quadrum saepius. Abbas jus quibus uxor vicis. Defui iusto loquor pala valetudo voco. Bene gemino ibidem ille premo. Distineo nimis patria similis ut. Adipiscing amet venio. Gemino magna saepius veniam. Erat lobortis occuro pala vindico. Commoveo distineo iustum letalis praemitto refoveo sagaciter uxor.</p>
<p>Abico cogo facilisi oppeto saluto. Gemino pagus premo tation. Adipiscing capto erat eros olim ulciscor. Accumsan interdico vicis. Caecus decet macto meus nobis pagus praesent probo. Consectetuer dolore ibidem modo turpis. Accumsan at commodo erat nimis velit.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 334621,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-18 14:33:16 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Abluo Dolore Saluto Ut',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '914378be-090f-47db-b30f-8aa08e8044c3',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426527917,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e07f55bc-09d1-40b7-88c7-e68f68560e8b',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Camur jus lenis. Damnum nibh sagaciter uxor. Bene cogo ex fere gravis lucidus neo sed. At ludus magna refero uxor. Defui dolore dolus genitus meus nisl sit. Causa immitto paulatim refero tincidunt. Caecus fere huic nibh nobis odio olim premo vero wisi.

At eu humo nunc sagaciter singularis. Dolore neque praesent sed utrum uxor vereor vicis. Abigo brevitas exputo genitus huic incassum jus pecus sed usitas. Capto persto proprius quadrum suscipit. Commoveo distineo fere nobis suscipit turpis ulciscor vicis.

Ad autem euismod gemino gilvus luctus nisl suscipere tum vicis. Autem damnum facilisi letalis luptatum metuo ratis virtus. Causa defui eligo feugiat genitus interdico iusto nutus quia secundum. Conventio ea nostrud refero suscipit ymo. Bene neo neque pertineo rusticus.

Conventio diam ideo ille nimis persto saepius sudo. Cui eum immitto. Camur minim vero verto. Mauris metuo odio pala quidne utrum. Abluo amet antehabeo iaceo oppeto pertineo roto validus. Autem cui ea eros jugis nunc quidne tego torqueo utrum.

Defui genitus haero uxor. Capto diam distineo exputo humo obruo saepius venio. Amet cui importunus persto premo zelus.

Distineo molior torqueo ulciscor valde. Abbas distineo huic humo magna pagus praemitto proprius quidem. Abigo aptent augue blandit ibidem praemitto quis tamen. Adipiscing ille nimis nobis quae ratis si. Humo laoreet suscipere tincidunt usitas volutpat. Jugis nostrud nunc usitas vel.

Abico duis importunus in lucidus tincidunt verto. Pecus praesent valde. Blandit commoveo illum saepius. Fere loquor vulpes. Autem cogo cui humo patria praesent quae vel vereor ymo. Blandit brevitas genitus ibidem nostrud typicus valde virtus voco.

At ibidem tamen ymo. Haero jumentum nibh paulatim ratis rusticus tego ulciscor ut. Brevitas exerci oppeto proprius rusticus torqueo ulciscor ullamcorper ut vulpes. Consectetuer letalis torqueo vindico. Dolus iustum secundum. Haero ibidem nulla typicus. Adipiscing imputo populus praemitto. Capto lucidus valde. Abico blandit gemino imputo jugis ludus praesent quae sed.

Eros molior oppeto uxor. Distineo immitto natu veniam venio. Imputo jumentum neque nibh tincidunt validus volutpat zelus. Aptent commoveo dolus iaceo meus neque tego. Conventio dolus facilisi haero quadrum rusticus suscipere veniam vero. Acsi in refero singularis veniam. Abdo eros facilisi meus quidne sudo tum.

Aliquip causa enim exerci huic odio. Decet gemino os. Capto ille qui roto. Commoveo jus lenis nunc paratus patria pneum quadrum. Aptent ideo nibh sit tation usitas. Amet illum quidne tation venio.

Bene ratis te vulputate. Abigo eum facilisis illum jus nunc praesent quis. Loquor magna populus quidem te vereor voco vulputate.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Camur jus lenis. Damnum nibh sagaciter uxor. Bene cogo ex fere gravis lucidus neo sed. At ludus magna refero uxor. Defui dolore dolus genitus meus nisl sit. Causa immitto paulatim refero tincidunt. Caecus fere huic nibh nobis odio olim premo vero wisi.</p>
<p>At eu humo nunc sagaciter singularis. Dolore neque praesent sed utrum uxor vereor vicis. Abigo brevitas exputo genitus huic incassum jus pecus sed usitas. Capto persto proprius quadrum suscipit. Commoveo distineo fere nobis suscipit turpis ulciscor vicis.</p>
<p>Ad autem euismod gemino gilvus luctus nisl suscipere tum vicis. Autem damnum facilisi letalis luptatum metuo ratis virtus. Causa defui eligo feugiat genitus interdico iusto nutus quia secundum. Conventio ea nostrud refero suscipit ymo. Bene neo neque pertineo rusticus.</p>
<p>Conventio diam ideo ille nimis persto saepius sudo. Cui eum immitto. Camur minim vero verto. Mauris metuo odio pala quidne utrum. Abluo amet antehabeo iaceo oppeto pertineo roto validus. Autem cui ea eros jugis nunc quidne tego torqueo utrum.</p>
<p>Defui genitus haero uxor. Capto diam distineo exputo humo obruo saepius venio. Amet cui importunus persto premo zelus.</p>
<p>Distineo molior torqueo ulciscor valde. Abbas distineo huic humo magna pagus praemitto proprius quidem. Abigo aptent augue blandit ibidem praemitto quis tamen. Adipiscing ille nimis nobis quae ratis si. Humo laoreet suscipere tincidunt usitas volutpat. Jugis nostrud nunc usitas vel.</p>
<p>Abico duis importunus in lucidus tincidunt verto. Pecus praesent valde. Blandit commoveo illum saepius. Fere loquor vulpes. Autem cogo cui humo patria praesent quae vel vereor ymo. Blandit brevitas genitus ibidem nostrud typicus valde virtus voco.</p>
<p>At ibidem tamen ymo. Haero jumentum nibh paulatim ratis rusticus tego ulciscor ut. Brevitas exerci oppeto proprius rusticus torqueo ulciscor ullamcorper ut vulpes. Consectetuer letalis torqueo vindico. Dolus iustum secundum. Haero ibidem nulla typicus. Adipiscing imputo populus praemitto. Capto lucidus valde. Abico blandit gemino imputo jugis ludus praesent quae sed.</p>
<p>Eros molior oppeto uxor. Distineo immitto natu veniam venio. Imputo jumentum neque nibh tincidunt validus volutpat zelus. Aptent commoveo dolus iaceo meus neque tego. Conventio dolus facilisi haero quadrum rusticus suscipere veniam vero. Acsi in refero singularis veniam. Abdo eros facilisi meus quidne sudo tum.</p>
<p>Aliquip causa enim exerci huic odio. Decet gemino os. Capto ille qui roto. Commoveo jus lenis nunc paratus patria pneum quadrum. Aptent ideo nibh sit tation usitas. Amet illum quidne tation venio.</p>
<p>Bene ratis te vulputate. Abigo eum facilisis illum jus nunc praesent quis. Loquor magna populus quidem te vereor voco vulputate.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 44856,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-16 23:45:17 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Mos Patria Quadrum Vulpes',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3d4d67ca-9cb7-45ab-92ed-e088364da440',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426261072,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e70b47e2-5daa-43ad-b391-7517b932722c',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Iusto refero vero vulputate. Diam hos nulla saepius. Adipiscing genitus pagus singularis veniam. Abluo exputo quadrum si vero. Aliquam plaga saepius ymo. Brevitas ille immitto nimis oppeto utinam. Abigo accumsan blandit capto dignissim hendrerit melior molior populus rusticus.

Feugiat hos macto oppeto paratus praemitto saluto vicis. Exerci lucidus neo torqueo vicis.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Iusto refero vero vulputate. Diam hos nulla saepius. Adipiscing genitus pagus singularis veniam. Abluo exputo quadrum si vero. Aliquam plaga saepius ymo. Brevitas ille immitto nimis oppeto utinam. Abigo accumsan blandit capto dignissim hendrerit melior molior populus rusticus.</p>
<p>Feugiat hos macto oppeto paratus praemitto saluto vicis. Exerci lucidus neo torqueo vicis.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 35747,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-13 21:37:52 +0600',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Tation Uxor',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '2b5b8a08-9f4e-4d4a-a9fd-e889a3248daf',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426403056,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f050b471-79b4-4cf4-a22d-6d0d47ec21a7',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Commoveo distineo dolore letalis lobortis luctus neo rusticus singularis veniam. At brevitas comis distineo incassum jus odio quadrum similis vulputate. Adipiscing genitus nulla occuro typicus ullamcorper veniam. Bene eros imputo zelus. Accumsan adipiscing erat imputo lucidus secundum te turpis ymo.

Conventio euismod gravis nostrud populus proprius. Adipiscing causa eu euismod ex facilisis in praemitto refero. Aliquip amet autem ille odio pertineo suscipit vel. Antehabeo enim metuo. Commodo consequat dolus eros gemino gravis similis vereor.

At decet hos nobis utinam. Aliquam conventio molior utinam volutpat. At eligo eros neo tamen valetudo. Aliquam aptent brevitas gemino modo oppeto premo singularis torqueo vel. Duis elit et ludus melior refoveo sagaciter suscipere turpis veniam. Erat gravis inhibeo mos verto. Defui eros fere gravis iusto natu premo ullamcorper validus.

Bene consequat gemino mos nunc odio plaga quia. Abdo caecus capto commodo eligo odio pala ymo. Abdo dolore inhibeo mauris nisl persto quibus sit. Caecus et fere feugiat olim os populus.

Ad decet elit esca ideo macto nostrud tego veniam vicis. Abdo adipiscing augue camur esse lucidus obruo pneum validus.

Augue commodo haero ideo occuro olim. Appellatio comis enim nutus patria sagaciter tamen ut verto. Dignissim eros gilvus nutus oppeto sit. Camur exerci magna nostrud typicus. Blandit brevitas ea eligo eros genitus luptatum suscipere validus.

Exerci ibidem typicus. Blandit dolor erat exerci iriure lobortis obruo premo quis validus. Commoveo esse mos paulatim plaga quibus si. Appellatio ibidem incassum nunc volutpat. Abigo at ex incassum oppeto probo ulciscor. Accumsan amet appellatio feugiat huic immitto lucidus rusticus sit.

Augue damnum diam feugiat gilvus metuo premo refero ymo. Accumsan autem camur capto fere huic iusto luctus molior. Distineo hendrerit jugis modo pneum vero vicis vulpes. Aptent ideo imputo jus neque nobis pertineo secundum. Abigo comis eligo ex iustum obruo refero scisco typicus virtus. Causa modo utinam.

Augue blandit caecus feugiat refoveo saepius sudo torqueo. Aptent conventio eu nulla tation utinam veniam. Erat exerci ibidem ludus odio refero tego ut verto vulputate. Accumsan aliquam appellatio commoveo consequat nutus vicis. Abico aliquip capto et nobis praesent sino vereor. Damnum decet exerci nimis oppeto populus quibus sit vereor vulpes. Illum jugis loquor quibus refoveo valde. Abluo capto cui gravis nostrud nulla nunc refero suscipit uxor.

Augue damnum dolore iriure lenis lucidus metuo obruo tum ulciscor. Bene neo vulpes. Dolus genitus ille interdico uxor. Brevitas iustum quia sagaciter vulpes. Consectetuer hendrerit quae. Aliquam fere quae. Abdo eros laoreet minim oppeto patria quidem tego ut. Brevitas loquor tum validus. Eum facilisis incassum interdico iustum loquor nostrud valde.

Ad letalis nutus tation ulciscor virtus. Adipiscing amet dolus minim similis utrum. Abigo autem brevitas commoveo humo ibidem uxor veniam verto. Accumsan bene camur ex iriure nostrud proprius te ut. Augue genitus gilvus nisl occuro os roto sed. Abdo at commoveo ideo mos vulpes.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Commoveo distineo dolore letalis lobortis luctus neo rusticus singularis veniam. At brevitas comis distineo incassum jus odio quadrum similis vulputate. Adipiscing genitus nulla occuro typicus ullamcorper veniam. Bene eros imputo zelus. Accumsan adipiscing erat imputo lucidus secundum te turpis ymo.</p>
<p>Conventio euismod gravis nostrud populus proprius. Adipiscing causa eu euismod ex facilisis in praemitto refero. Aliquip amet autem ille odio pertineo suscipit vel. Antehabeo enim metuo. Commodo consequat dolus eros gemino gravis similis vereor.</p>
<p>At decet hos nobis utinam. Aliquam conventio molior utinam volutpat. At eligo eros neo tamen valetudo. Aliquam aptent brevitas gemino modo oppeto premo singularis torqueo vel. Duis elit et ludus melior refoveo sagaciter suscipere turpis veniam. Erat gravis inhibeo mos verto. Defui eros fere gravis iusto natu premo ullamcorper validus.</p>
<p>Bene consequat gemino mos nunc odio plaga quia. Abdo caecus capto commodo eligo odio pala ymo. Abdo dolore inhibeo mauris nisl persto quibus sit. Caecus et fere feugiat olim os populus.</p>
<p>Ad decet elit esca ideo macto nostrud tego veniam vicis. Abdo adipiscing augue camur esse lucidus obruo pneum validus.</p>
<p>Augue commodo haero ideo occuro olim. Appellatio comis enim nutus patria sagaciter tamen ut verto. Dignissim eros gilvus nutus oppeto sit. Camur exerci magna nostrud typicus. Blandit brevitas ea eligo eros genitus luptatum suscipere validus.</p>
<p>Exerci ibidem typicus. Blandit dolor erat exerci iriure lobortis obruo premo quis validus. Commoveo esse mos paulatim plaga quibus si. Appellatio ibidem incassum nunc volutpat. Abigo at ex incassum oppeto probo ulciscor. Accumsan amet appellatio feugiat huic immitto lucidus rusticus sit.</p>
<p>Augue damnum diam feugiat gilvus metuo premo refero ymo. Accumsan autem camur capto fere huic iusto luctus molior. Distineo hendrerit jugis modo pneum vero vicis vulpes. Aptent ideo imputo jus neque nobis pertineo secundum. Abigo comis eligo ex iustum obruo refero scisco typicus virtus. Causa modo utinam.</p>
<p>Augue blandit caecus feugiat refoveo saepius sudo torqueo. Aptent conventio eu nulla tation utinam veniam. Erat exerci ibidem ludus odio refero tego ut verto vulputate. Accumsan aliquam appellatio commoveo consequat nutus vicis. Abico aliquip capto et nobis praesent sino vereor. Damnum decet exerci nimis oppeto populus quibus sit vereor vulpes. Illum jugis loquor quibus refoveo valde. Abluo capto cui gravis nostrud nulla nunc refero suscipit uxor.</p>
<p>Augue damnum dolore iriure lenis lucidus metuo obruo tum ulciscor. Bene neo vulpes. Dolus genitus ille interdico uxor. Brevitas iustum quia sagaciter vulpes. Consectetuer hendrerit quae. Aliquam fere quae. Abdo eros laoreet minim oppeto patria quidem tego ut. Brevitas loquor tum validus. Eum facilisis incassum interdico iustum loquor nostrud valde.</p>
<p>Ad letalis nutus tation ulciscor virtus. Adipiscing amet dolus minim similis utrum. Abigo autem brevitas commoveo humo ibidem uxor veniam verto. Accumsan bene camur ex iriure nostrud proprius te ut. Augue genitus gilvus nisl occuro os roto sed. Abdo at commoveo ideo mos vulpes.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 339452,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-03-15 13:04:16 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Quidem',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4c38fa5b-9451-4b42-8467-4c22ec7bffc5',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426730697,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f1f41e0a-2501-44a7-85c6-1927976515ae',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abigo conventio decet erat eum inhibeo meus sit tum vicis. Ad commodo consequat ideo jugis lobortis natu plaga tego. Distineo eu genitus praemitto quis sagaciter tamen ut valde veniam. Ad defui distineo immitto luptatum magna mauris occuro torqueo. Diam occuro paratus quadrum volutpat.

Consequat hos laoreet os velit veniam venio. At damnum ideo ille illum lenis olim tincidunt valetudo. Acsi imputo persto suscipere wisi. Abbas consequat duis genitus lobortis paratus paulatim. Ex in sed uxor. Dolore lobortis neo tamen.

Exerci lucidus melior mos quidne si tum. Cogo duis esca metuo mos quibus refero si. Facilisi hos huic mos pecus singularis. At bene dignissim haero iusto jus mos ut. Caecus consectetuer refoveo. Abluo autem distineo dolore duis gravis persto premo refoveo validus. Aliquip cogo ludus modo. Erat ibidem lenis quae roto si vicis. Cogo duis facilisis hos loquor oppeto paulatim tum verto voco.

Causa immitto jus meus neo vel. Exerci fere haero magna quibus sed. Adipiscing aliquam conventio nisl olim quadrum quia vicis. Enim inhibeo mauris minim pertineo premo probo quae ratis vel. Adipiscing esca ex iusto laoreet neque quidne ulciscor.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Abigo conventio decet erat eum inhibeo meus sit tum vicis. Ad commodo consequat ideo jugis lobortis natu plaga tego. Distineo eu genitus praemitto quis sagaciter tamen ut valde veniam. Ad defui distineo immitto luptatum magna mauris occuro torqueo. Diam occuro paratus quadrum volutpat.</p>
<p>Consequat hos laoreet os velit veniam venio. At damnum ideo ille illum lenis olim tincidunt valetudo. Acsi imputo persto suscipere wisi. Abbas consequat duis genitus lobortis paratus paulatim. Ex in sed uxor. Dolore lobortis neo tamen.</p>
<p>Exerci lucidus melior mos quidne si tum. Cogo duis esca metuo mos quibus refero si. Facilisi hos huic mos pecus singularis. At bene dignissim haero iusto jus mos ut. Caecus consectetuer refoveo. Abluo autem distineo dolore duis gravis persto premo refoveo validus. Aliquip cogo ludus modo. Erat ibidem lenis quae roto si vicis. Cogo duis facilisis hos loquor oppeto paulatim tum verto voco.</p>
<p>Causa immitto jus meus neo vel. Exerci fere haero magna quibus sed. Adipiscing aliquam conventio nisl olim quadrum quia vicis. Enim inhibeo mauris minim pertineo premo probo quae ratis vel. Adipiscing esca ex iusto laoreet neque quidne ulciscor.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 374395,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 08:04:57 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Abico Fere Nulla',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '07636a37-eec7-4116-b4f6-f875386ce167',
  'type' => 'product',
  'language' => 'und',
  'created' => 1426738270,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f548ea22-4d33-489b-934e-508182f52af5',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Accumsan distineo mauris oppeto pertineo sed vel. Augue autem molior nostrud utrum. Gravis iaceo praemitto proprius utinam virtus. Feugiat macto os populus roto torqueo tum. Causa diam esca qui saepius secundum. Aliquip feugiat humo ibidem jugis neque nostrud sed validus. Commodo eu incassum iriure premo quibus valetudo.

Abbas huic luctus neque torqueo. Causa defui nisl roto te valetudo. Eum huic mos nisl patria praesent sed. Abdo abigo magna nibh pagus sit utrum veniam. Abbas causa cui distineo et lobortis ludus plaga.

Commoveo typicus wisi. Accumsan enim gravis lenis mos odio validus. Appellatio brevitas erat scisco. Abluo aliquip aptent eu oppeto proprius velit. Bene nulla veniam. Aliquam bene gilvus hendrerit jumentum luptatum persto praesent. Abico appellatio defui ex neque probo tation tego typicus utinam. Conventio jugis olim plaga tum. Blandit causa comis metuo nisl quibus si tum veniam.

Adipiscing duis exerci feugiat immitto interdico nutus refoveo sed valde. Aliquam brevitas diam haero macto paulatim persto quae sed singularis. Defui esse luctus utrum vulputate. Camur et facilisis fere genitus immitto mauris. Abdo abico abigo ad huic pecus quia refero usitas. Brevitas eu mauris modo oppeto usitas. Si sino valetudo.

Aliquip amet damnum ille letalis meus modo neque obruo ulciscor. Caecus cui feugiat scisco. Exerci patria quae utrum uxor.

Autem duis luctus olim quibus quidne veniam. Meus minim molior. Interdico occuro os premo quae ratis tego vereor voco. Interdico molior suscipere. Autem commoveo esca exerci hendrerit interdico proprius vulpes. Incassum interdico nobis pneum verto.

',
        'summary' => NULL,
        'format' => 'plain_text',
        'safe_value' => '<p>Accumsan distineo mauris oppeto pertineo sed vel. Augue autem molior nostrud utrum. Gravis iaceo praemitto proprius utinam virtus. Feugiat macto os populus roto torqueo tum. Causa diam esca qui saepius secundum. Aliquip feugiat humo ibidem jugis neque nostrud sed validus. Commodo eu incassum iriure premo quibus valetudo.</p>
<p>Abbas huic luctus neque torqueo. Causa defui nisl roto te valetudo. Eum huic mos nisl patria praesent sed. Abdo abigo magna nibh pagus sit utrum veniam. Abbas causa cui distineo et lobortis ludus plaga.</p>
<p>Commoveo typicus wisi. Accumsan enim gravis lenis mos odio validus. Appellatio brevitas erat scisco. Abluo aliquip aptent eu oppeto proprius velit. Bene nulla veniam. Aliquam bene gilvus hendrerit jumentum luptatum persto praesent. Abico appellatio defui ex neque probo tation tego typicus utinam. Conventio jugis olim plaga tum. Blandit causa comis metuo nisl quibus si tum veniam.</p>
<p>Adipiscing duis exerci feugiat immitto interdico nutus refoveo sed valde. Aliquam brevitas diam haero macto paulatim persto quae sed singularis. Defui esse luctus utrum vulputate. Camur et facilisis fere genitus immitto mauris. Abdo abico abigo ad huic pecus quia refero usitas. Brevitas eu mauris modo oppeto usitas. Si sino valetudo.</p>
<p>Aliquip amet damnum ille letalis meus modo neque obruo ulciscor. Caecus cui feugiat scisco. Exerci patria quae utrum uxor.</p>
<p>Autem duis luctus olim quibus quidne veniam. Meus minim molior. Interdico occuro os premo quae ratis tego vereor voco. Interdico molior suscipere. Autem commoveo esca exerci hendrerit interdico proprius vulpes. Incassum interdico nobis pneum verto.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_catalogs' => array(),
  'field_cost' => array(
    'und' => array(
      0 => array(
        'value' => 237189,
      ),
    ),
  ),
  'field_pictures' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-03-19 10:11:10 +0600',
);
  return $nodes;
}
